/* Shared ceramic animal banks. The selection changes appearance only, never savings. */
(function(){
const animals={pig:['Pig','🐷','#edb1bb','#a25372'],dog:['Dog','🐶','#c89966','#684530'],cat:['Cat','🐱','#d9cbbb','#716254'],lion:['Lion','🦁','#dfb458','#825330'],giraffe:['Giraffe','🦒','#e7bd6d','#92612e'],rhino:['Rhino','🦏','#a6b6bd','#536b78']};let serial=0;
function selected(){try{const k=localStorage.getItem('cb:bank-animal');return animals[k]?k:'pig';}catch{return 'pig';}}
function art(k){const keys=Object.keys(animals),i=Math.max(0,keys.indexOf(k)),x=i%3*600,y=i<3?0:570,h=i<3?560:639;const slots=[[203,159,110,16],[778,185,90,17],[1380,196,90,18],[171,795,80,17],[775,843,68,17],[1353,786,96,15]],slot=slots[i],clip="bankCrop"+(++serial);return `<g class="piggy-body save-pig-body"><svg x="0" y="0" width="220" height="170" viewBox="${x} ${y} 600 ${h}" overflow="hidden"><defs><clipPath id="${clip}"><rect x="${x}" y="${y}" width="600" height="${h}"/></clipPath></defs><image href="assets/banks/ceramic-atlas.jpg" width="1800" height="1209" clip-path="url(#${clip})"/><rect class="piggy-slot" x="${slot[0]}" y="${slot[1]}" width="${slot[2]}" height="${slot[3]}" fill="transparent" stroke="none" rx="6"/></svg></g>`;}
function mount(svg,choices){function draw(k){svg.setAttribute('viewBox','0 0 220 170');svg.innerHTML=art(k);svg.dataset.animal=k;svg.setAttribute('aria-label',animals[k][0]+' ceramic bank');choices?.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.animal===k)));}if(choices){choices.replaceChildren();for(const [k,[name,emoji]]of Object.entries(animals)){const b=document.createElement('button');b.type='button';b.dataset.animal=k;b.textContent=emoji+' '+name;b.onclick=()=>{try{localStorage.setItem('cb:bank-animal',k);}catch{}draw(k);document.dispatchEvent(new CustomEvent('bank-animal-change',{detail:k}));};choices.append(b);}}draw(selected());}
function deposit(ghost,point,reduced){if(reduced){ghost.remove();return;}const r=ghost.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;ghost.style.transition='none';ghost.style.left=0;ghost.style.top=0;ghost.style.pointerEvents='none';const animation=ghost.animate([{transform:`translate(${x-r.width/2}px,${y-r.height/2}px)`,opacity:1},{transform:`translate(${point.x-r.width/2}px,${point.y-r.height-16}px) rotate(-12deg)`,opacity:1,offset:.55},{transform:`translate(${point.x-r.width/2}px,${point.y-r.height*.7}px) scaleX(.2)`,opacity:1,offset:.75},{transform:`translate(${point.x-r.width/2}px,${point.y-r.height*.3}px) scale(.16,0)`,opacity:0}],{duration:620,easing:'cubic-bezier(.3,.05,.4,1)',fill:'forwards'});animation.onfinish=()=>ghost.remove();setTimeout(()=>ghost.remove(),800);}
window.BankArt={art,mount,selected,deposit};
})();
