import * as T from './vendor/three.module.js';
import {PARTS,DEF,COLORS,LAYER,LIMIT,IDEAS,size,placementError,autoLayer,settle,validProject} from './blocks-engine.js';
import {brickMesh,brickGeometry,brickMaterial} from './blocks-models.js';
const $=s=>document.querySelector(s),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),KEY='cb:blocks3d:v1',id=()=>crypto.randomUUID();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const newBuild=name=>({id:id(),name,parts:[],idea:null,step:0});
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.v===1&&Array.isArray(s.projects)){s.projects=s.projects.filter(p=>typeof p.id==='string'&&validProject(p.parts)).slice(0,8);if(s.projects.length){s.projects.forEach(p=>{p.name=String(p.name||'My creation').slice(0,32);if(!IDEAS[p.idea])p.idea=null;p.step=clamp(Number(p.step)||0,0,p.idea?IDEAS[p.idea].parts.length:0);});s.active=s.projects.some(p=>p.id===s.active)?s.active:s.projects[0].id;return s;}}}catch{}const p=newBuild('My first creation');return {v:1,active:p.id,projects:[p]};}
const state=load();let project=state.projects.find(p=>p.id===state.active),selected=null,kind='two',color='mint',rotation=0,pending=null,category='Bricks',undo=[],redo=[];
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='Saved on this device';}catch{$('#saveStatus').textContent='Could not save. Keep this tab open.';}}
function tell(text){$('#hint').textContent=text;}
window.SFX?.bind($('#blockSound'));window.SFX?.ambience('off');
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{$('#loading').innerHTML='This device could not start 3D. <a href="classic.html">Open Classic</a>';throw Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;$('#blockViewport').append(renderer.domElement);$('#loading').remove();
const scene=new T.Scene();scene.background=new T.Color('#bdd2c1');scene.fog=new T.Fog('#bdd2c1',45,95);scene.add(new T.HemisphereLight('#fcfff0','#69846c',2));const sun=new T.DirectionalLight('#fff1d7',3);sun.position.set(-10,20,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15});sun.shadow.normalBias=.02;scene.add(sun);
const camera=new T.PerspectiveCamera(42,1,.1,100);let yaw=.45,pitch=.72,distance=innerWidth<600?38:29;const mat=new T.Mesh(new T.BoxGeometry(21,.4,21),new T.MeshStandardMaterial({color:'#558574',roughness:.6}));mat.position.y=-.24;mat.receiveShadow=true;scene.add(mat);const floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:'#c2d3b7',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.5;floor.receiveShadow=true;scene.add(floor);
const studs=new T.InstancedMesh(new T.CylinderGeometry(.14,.16,.07,8),new T.MeshStandardMaterial({color:'#739d81',roughness:.65}),400);const matrix=new T.Matrix4();for(let x=0;x<20;x++)for(let z=0;z<20;z++){matrix.makeTranslation(x-9.5,.025,z-9.5);studs.setMatrixAt(x*20+z,matrix);}scene.add(studs);const grid=new T.GridHelper(20,20,'#729a80','#729a80');grid.position.y=-.01;scene.add(grid);
const pieces=new T.Group();scene.add(pieces);let ghost=null;const validMaterial=new T.MeshStandardMaterial({color:'#b3e96b',transparent:true,opacity:.6,roughness:.4,depthWrite:false}),invalidMaterial=new T.MeshStandardMaterial({color:'#e86b60',transparent:true,opacity:.5,depthWrite:false});const outline=new T.BoxHelper(new T.Mesh(new T.BoxGeometry(1,1,1)), '#fff2a6');outline.visible=false;scene.add(outline);
function rebuild(){pieces.clear();for(const p of project.parts)pieces.add(brickMesh(p));renderer.shadowMap.needsUpdate=true;renderCollection();renderGuide();$('#buildStats').textContent=project.parts.length+' / '+LIMIT+' pieces. Every piece is free.';$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length;const found=pieces.children.find(m=>m.userData.id===selected);outline.visible=!!found;if(found)outline.setFromObject(found);}
function checkpoint(){undo.push(JSON.stringify({parts:project.parts,idea:project.idea,step:project.step}));if(undo.length>40)undo.shift();redo=[];}
function finish(){rebuild();save();window.SFX?.snap();}
function currentWithout(){return pending?.moving?project.parts.filter(p=>p.id!==pending.moving):project.parts;}
function showPreview(x=0,z=0,y=0,auto=true){const p={id:pending?.moving||id(),kind,x:Math.round(x),z:Math.round(z),y:Math.round(y),rot:rotation,color};if(auto)p.y=autoLayer(currentWithout(),p);pending={...pending,piece:p};if(ghost)scene.remove(ghost);const error=placementError(currentWithout(),p);ghost=brickMesh(p,error?invalidMaterial:validMaterial);ghost.castShadow=false;scene.add(ghost);$('#snap').disabled=!!error;$('#posX').value=p.x;$('#posZ').value=p.z;$('#posY').value=p.y;tell(error||DEF[kind].name+' ready at layer '+p.y+'. Tap Snap it here.');highlightPart();}
function choose(next){kind=next;pending={};selected=null;outline.visible=false;showPreview(0,0,0,true);window.SFX?.tap();}
function clearPreview(){if(ghost)scene.remove(ghost);ghost=null;pending=null;$('#snap').disabled=true;}
$('#snap').onclick=()=>{if(!pending?.piece)return;const p=pending.piece,others=currentWithout();const error=placementError(others,p);if(error){tell(error);return;}if(!pending.moving&&project.parts.length>=LIMIT){tell('This mat holds '+LIMIT+' pieces. Put some away or start another creation.');return;}checkpoint();const wasMove=!!pending.moving;project.parts=settle([...others,{...p}]);selected=p.id;const idea=IDEAS[project.idea],target=idea?.parts[project.step];const matched=target&&['kind','x','y','z','rot','color'].every(k=>target[k]===p[k]);if(matched)project.step++;finish();if(matched){clearPreview();if(project.step<idea.parts.length)guideNext();else tell('Your creation is complete! Build more, or save a picture.');return;}if(wasMove){clearPreview();tell('Moved and snapped.');}else{pending={};showPreview(p.x,p.z,p.y,true);tell('Click! Your piece is connected. Add another or choose a new shape.');}};
$('#cancel').onclick=()=>{clearPreview();tell('Choose a piece, or select one you already placed.');};$('#rotatePiece').onclick=()=>{rotation=(rotation+1)%4;if(pending?.piece){const p=pending.piece;showPreview(p.x,p.z,p.y,$('#autoStack').checked);}else tell('Choose a piece to turn.');};
$('#previewPosition').onclick=()=>{if(!pending)pending={};showPreview(Number($('#posX').value),Number($('#posZ').value),Number($('#posY').value),$('#autoStack').checked);};
function renderCollection(){$('#collection').replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent=project.parts.length?'Choose a piece':'No pieces yet';$('#collection').append(empty);project.parts.forEach((p,i)=>{const o=document.createElement('option');o.value=p.id;o.textContent=(i+1)+'. '+DEF[p.kind].name+' · '+p.color+' · layer '+p.y;$('#collection').append(o);});$('#collection').value=selected||'';}
function select(pid){clearPreview();selected=pid;rebuild();const p=project.parts.find(p=>p.id===pid);if(p)tell(DEF[p.kind].name+' selected. Move it, copy it, paint it, or put it away.');}
$('#collection').onchange=e=>select(e.target.value);$('#movePiece').onclick=()=>{const p=project.parts.find(p=>p.id===selected);if(!p){tell('Choose a placed piece first.');return;}kind=p.kind;color=p.color;rotation=p.rot;pending={moving:p.id};paintPalette();showPreview(p.x,p.z,p.y,false);};$('#copyPiece').onclick=()=>{const p=project.parts.find(p=>p.id===selected);if(!p){tell('Choose a placed piece first.');return;}kind=p.kind;color=p.color;rotation=p.rot;pending={};paintPalette();showPreview(p.x,p.z,p.y,true);};$('#paintPiece').onclick=()=>{const p=project.parts.find(p=>p.id===selected);if(!p){tell('Choose a placed piece, then a color.');return;}checkpoint();p.color=color;finish();tell('New color, same creation.');};$('#removePiece').onclick=()=>{if(!selected)return;checkpoint();project.parts=settle(project.parts.filter(p=>p.id!==selected));selected=null;clearPreview();finish();tell('Put away. Pieces above it settled onto their supports. Undo brings it back.');};
function restore(from,to){if(!from.length)return;to.push(JSON.stringify({parts:project.parts,idea:project.idea,step:project.step}));Object.assign(project,JSON.parse(from.pop()));selected=null;clearPreview();rebuild();save();window.SFX?.tap();}$('#undo').onclick=()=>restore(undo,redo);$('#redo').onclick=()=>restore(redo,undo);
function paintPalette(){for(const b of $('#palette').children)b.setAttribute('aria-pressed',String(b.dataset.color===color));}for(const [name,value] of Object.entries(COLORS)){const b=document.createElement('button');b.dataset.color=name;b.style.background=value;b.setAttribute('aria-label',name+' pieces');b.onclick=()=>{color=name;paintPalette();if(pending?.piece){const p=pending.piece;showPreview(p.x,p.z,p.y,false);}renderShelf();};$('#palette').append(b);}paintPalette();
let thumbnailRenderer=null,previews=[],lastThumb=0;function thumbScene(k){const s=new T.Scene();s.add(new T.HemisphereLight('#fffef6','#7c9674',2));const l=new T.DirectionalLight('#fff1cf',3);l.position.set(-3,6,5);s.add(l);const m=new T.Mesh(brickGeometry(k),brickMaterial(color));m.position.y=-DEF[k].h*LAYER/2;s.add(m);return {s,m};}
function renderShelf(){const cats=[...new Set(PARTS.map(p=>p.group))];$('#partTabs').replaceChildren();for(const c of cats){const b=document.createElement('button');b.textContent=c;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(c===category));b.onclick=()=>{category=c;renderShelf();};$('#partTabs').append(b);}if(!thumbnailRenderer){thumbnailRenderer=new T.WebGLRenderer({alpha:true,antialias:true});thumbnailRenderer.setSize(200,140);thumbnailRenderer.outputColorSpace=T.SRGBColorSpace;thumbnailRenderer.toneMapping=T.ACESFilmicToneMapping;}previews=[];$('#partShelf').replaceChildren();for(const d of PARTS.filter(p=>p.group===category)){const b=document.createElement('button');b.className='part-card';b.dataset.kind=d.id;b.setAttribute('aria-label',d.name+', free');const canvas=document.createElement('canvas');canvas.width=200;canvas.height=140;canvas.setAttribute('aria-hidden','true');const strong=document.createElement('strong');strong.textContent=d.name;const small=document.createElement('small');small.textContent=d.w+' × '+d.d+' · FREE';b.append(canvas,strong,small);b.onclick=()=>choose(d.id);$('#partShelf').append(b);const {s,m}=thumbScene(d.id),c=new T.PerspectiveCamera(35,200/140,.1,50),dist=Math.max(d.w,d.d,d.h*LAYER)*2.2;c.position.set(dist*.7,dist*.6,dist);c.lookAt(0,0,0);previews.push({b,canvas,ctx:canvas.getContext('2d'),s,m,c});}highlightPart();drawThumbs(1000,true);}
function highlightPart(){for(const b of $('#partShelf').children)b.classList.toggle('chosen',b.dataset.kind===kind);}
function drawThumbs(now,force=false){if(!thumbnailRenderer||(!force&&now-lastThumb<110))return;lastThumb=now;for(const p of previews){const r=p.b.getBoundingClientRect();if(!force&&(r.bottom<0||r.top>innerHeight))continue;p.m.rotation.y=reduced?.2:Math.sin(now*.00035)*.6;thumbnailRenderer.render(p.s,p.c);p.ctx.clearRect(0,0,200,140);p.ctx.drawImage(thumbnailRenderer.domElement,0,0);}}
const ray=new T.Raycaster(),ndc=new T.Vector2();function tap(e){const r=renderer.domElement.getBoundingClientRect();ndc.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(ndc,camera);const hit=ray.intersectObjects([...pieces.children,mat],false)[0];if(!hit)return;if(!pending){if(hit.object.userData.id)select(hit.object.userData.id);return;}const shape=size({kind,rot:rotation});showPreview(Math.round(hit.point.x-shape.w/2),Math.round(hit.point.z-shape.d/2),Math.round(hit.point.y/LAYER),$('#autoStack').checked);}
let down=null,pointers=new Map(),pinch=0;renderer.domElement.onpointerdown=e=>{renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);down={x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY,moved:false};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);down.moved=true;}};renderer.domElement.onpointermove=e=>{if(!down||!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);distance=clamp(distance+(pinch-d)*.06,9,50);pinch=d;down.moved=true;return;}if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)down.moved=true;if(down.moved){yaw-=(e.clientX-down.lx)*.007;pitch=clamp(pitch+(e.clientY-down.ly)*.005,.16,1.5);}down.lx=e.clientX;down.ly=e.clientY;};renderer.domElement.onpointerup=e=>{pointers.delete(e.pointerId);if(down&&!down.moved&&!pointers.size)tap(e);down=null;};renderer.domElement.onpointercancel=()=>{down=null;pointers.clear();};renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance+e.deltaY*.02,9,50);},{passive:false});
function resize(){const r=$('#blockViewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=r.width<600?57:42;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('#blockViewport'));$('#homeView').onclick=()=>{yaw=.45;pitch=.72;distance=innerWidth<600?38:29;};$('#topView').onclick=()=>{pitch=1.5;yaw=0;};$('#orbit').onclick=()=>yaw+=Math.PI/4;$('#zoomIn').onclick=()=>distance=clamp(distance-2,9,50);$('#zoomOut').onclick=()=>distance=clamp(distance+2,9,50);
function renderProjects(){$('#projects').replaceChildren();for(const p of state.projects){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('#projects').append(o);}$('#projects').value=project.id;$('#projectName').value=project.name;}
function switchProject(pid){project=state.projects.find(p=>p.id===pid);state.active=pid;selected=null;undo=[];redo=[];clearPreview();renderProjects();rebuild();save();}
function createProject(name,idea=null){if(state.projects.length>=8){tell('Eight creations are saved. Open one below to keep building it.');return;}const p=newBuild(name);p.idea=idea;state.projects.push(p);switchProject(p.id);if(idea)guideNext();}
$('#projects').onchange=e=>switchProject(e.target.value);$('#projectName').onchange=e=>{project.name=e.target.value.trim().slice(0,32)||'My creation';renderProjects();save();};$('#newProject').onclick=()=>createProject('My creation '+(state.projects.length+1));for(const b of document.querySelectorAll('[data-idea]'))b.onclick=()=>createProject(IDEAS[b.dataset.idea].name,b.dataset.idea);
function renderGuide(){const idea=IDEAS[project.idea];$('#guide').hidden=!idea;if(!idea)return;$('#guideTitle').textContent=idea.name+' · '+Math.min(project.step,idea.parts.length)+' / '+idea.parts.length;$('#guideText').textContent=project.step>=idea.parts.length?'Your idea is built! Add your own colors, towers, and details.':idea.hint;$('#nextGuide').disabled=project.step>=idea.parts.length;}
function guideNext(){const idea=IDEAS[project.idea],p=idea?.parts[project.step];if(!p)return;kind=p.kind;color=p.color;rotation=p.rot;pending={};category=DEF[kind].group;paintPalette();renderShelf();showPreview(p.x,p.z,p.y,false);tell('Step '+(project.step+1)+': '+DEF[kind].name+'. Inspect the preview, then snap it in.');}$('#nextGuide').onclick=guideNext;$('#leaveGuide').onclick=()=>{checkpoint();project.idea=null;clearPreview();finish();};
$('#savePicture').onclick=()=>{if(!project.parts.length){tell('Add a few pieces before taking a picture.');return;}const was=ghost?.visible;if(ghost)ghost.visible=false;outline.visible=false;renderer.render(scene,camera);const a=document.createElement('a');a.download=(project.name.replace(/[^a-z0-9 -]/gi,'')||'My build')+'.png';a.href=renderer.domElement.toDataURL('image/png');a.click();if(ghost)ghost.visible=was;rebuild();tell('Your picture is ready to save.');};
$('#help').onclick=()=>{$('#sheetBody').innerHTML='<h2>Real pieces, playful rules.</h2><p>Every piece is free. Tap a shape and a color, tap the mat, and use Snap it here. Green previews fit; red previews explain what needs to change. Copy, paint, and undo are always available.</p><p>Blocks need a mat or exposed stud connection. Supports are simplified for creative play. This is not a structural engineering model. Smooth roofs and paving cannot hold studs on top.</p><p>Eight creations can be saved in this browser. Classic worlds are preserved separately. No accounts, payments, or uploads.</p>';$('#sheet').showModal();};$('#closeSheet').onclick=()=>$('#sheet').close();addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||$('#sheet').open)return;if(e.key==='Escape')clearPreview();if(e.key.toLowerCase()==='r')$('#rotatePiece').click();if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?$('#redo').click():$('#undo').click();}});
function animate(now){requestAnimationFrame(animate);if(document.hidden)return;camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,2+Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,2,0);const r=renderer.domElement.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)renderer.render(scene,camera);drawThumbs(now);}
renderProjects();renderShelf();rebuild();resize();save();choose('two');requestAnimationFrame(animate);
