import {mountSavings} from './savings-ui.js';
import * as T from './vendor/three.module.js';
import {CATALOG,DEFINITIONS as D,makeModel,makePerson,mesh,orb,block,material,disposeModel} from './chilltopia-models.js?v=reef3';
import {displayTank,clearTanks,tickTanks} from './reef-shop.js?v=reef3';
import {scannedMaterial,loadLighting,reflectiveWater} from './realism.js?v=20260907-sunlit';
const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.min(b,Math.max(a,v)), rand=(a,b)=>a+Math.random()*(b-a);
const KEY='cb:chilltopia3d:v1', reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const entry=(kind,x,z,s=1,y=0)=>({uid:uid(),kind,x,z,y,s,rot:0,paid:0});
function fresh(){return {v:1,active:'reef',goal:null,jobs:0,cooldown:0,lastFeed:0,worlds:{reef:[entry('rock',-3,-1,1.5),entry('rock',3,-1.4,1.4),entry('cave',0,-.8,1.3),entry('grass',-3.6,.2,1.3),entry('grass',3.8,-1.8,1.3),entry('grass',2.8,.7),entry('pinkcoral',-2.3,.9),entry('fan',2.5,-1.7,1.3),entry('anemone',1.4,1.1),entry('bubbles',-4,-1.7),entry('clown',-1,0),entry('clown',0,0),entry('chromis',1,0)],town:[entry('townhouse',-3,-2),entry('townhouse',0,-3),entry('townhouse',3,-2),entry('tree',-4,1),entry('tree',4,1),entry('tree',-4,-3),entry('flowers',2,-.5),entry('bench',-2,.5),entry('car',0,2)]}}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.v!==1||!s.worlds)return fresh();for(const w of ['reef','town']){if(!Array.isArray(s.worlds[w]))return fresh();s.worlds[w]=s.worlds[w].filter(i=>D[i.kind]?.world===w).slice(0,65).map(i=>({...i,uid:typeof i.uid==='string'?i.uid:uid(),x:clamp(Number(i.x)||0,w==='reef'?-7.8:-4.3,w==='reef'?7.8:4.3),z:clamp(Number(i.z)||0,w==='reef'?-4.1:-2.3,w==='reef'?4.1:2.3),y:clamp(Number(i.y)||0,0,2),s:clamp(Number(i.s)||1,.6,1.6),rot:Number(i.rot)||0,paid:clamp(Number(i.paid)||0,0,D[i.kind].price)}));}s.active=s.active==='town'?'town':'reef';s.jobs=Math.max(0,Number(s.jobs)||0);s.cooldown=Number(s.cooldown)||0;return s;}catch{return fresh()}}
const state=load();let world=state.active, selected=null,pending=null,category=world==='reef'?'Habitat':'Garden',paused=reduced,sound=window.SFX?.on??true,follow=false,followIndex=-1,job=null,feedingUntil=0,lastFrame=0,elapsed=0,dirty=false;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='● Saved on this device';}catch{$('#saveStatus').textContent='Storage full. Keep this tab open.'}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3300)}
function blip(name='tap'){if(sound)try{window.SFX?.[name]?.()}catch{}}
let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{ $('#loading').innerHTML='This device could not start 3D.<br><a href="classic.html">Play the classic builder</a>';throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('#viewport').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#bce1d5');scene.fog=new T.Fog('#bce1d5',24,65);
const camera=new T.PerspectiveCamera(38,1,.1,100);const target=new T.Vector3(0,1.1,0);let yaw=.28,pitch=.31,distance=18;
scene.add(new T.HemisphereLight('#d4efe7','#556349',.9));loadLighting(renderer,scene,'studio');const sun=new T.DirectionalLight('#fff6d6',2.5);sun.position.set(-5,12,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.bias=-.001;sun.shadow.normalBias=.03;scene.add(sun);const rim=new T.DirectionalLight('#7ce8dc',1.3);rim.position.set(4,5,-6);scene.add(rim);
const ambient=new T.Group(),floorGroup=new T.Group(),decor=new T.Group(),fishGroup=new T.Group(),effects=new T.Group(),jobGroup=new T.Group();scene.add(ambient,floorGroup,decor,fishGroup,effects,jobGroup);
const objects=new Map(),fish=[],bubbles=[],plants=[];
const jobMarkers=document.createElement('div');jobMarkers.id='jobMarkers';$('#game').append(jobMarkers);
function collectLitter(id){if(job?.type!=='clean')return;const root=jobGroup.children.find(o=>o.userData.cleanId===id);if(!root)return;jobGroup.remove(root);disposeModel(root);jobMarkers.querySelector('[data-litter="'+id+'"]')?.remove();job.progress++;blip('pop');updateJobText();}
function positionJobMarkers(){if(job?.type!=='clean')return;const rect=renderer.domElement.getBoundingClientRect();for(const g of jobGroup.children){const b=jobMarkers.querySelector('[data-litter="'+g.userData.cleanId+'"]');if(!b)continue;const v=g.position.clone().add(new T.Vector3(0,.28,0)).project(camera);b.style.left=((v.x+1)*.5*rect.width)+'px';b.style.top=((-v.y+1)*.5*rect.height)+'px';b.hidden=v.z>1||Math.abs(v.x)>1||Math.abs(v.y)>1;}}const ground=mesh(ambient,new T.PlaneGeometry(200,200),'#b9d9c6',0,-.85,0);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;
const selectionRing=new T.Mesh(new T.TorusGeometry(.7,.025,8,48),new T.MeshBasicMaterial({color:'#e8cd62'}));selectionRing.rotation.x=-Math.PI/2;selectionRing.visible=false;scene.add(selectionRing);
const person=makePerson();scene.add(person);const car=makeModel('car');scene.add(car);let player={x:1,z:2.6,angle:Math.PI,driving:false};let autoRoute=[];const keys=new Set();
function disposeGroup(g){disposeModel(g)}
let sandMaterial,aquariumSurface=null;
function environment(){aquariumSurface?.disposeReflection?.();aquariumSurface=null;disposeGroup(floorGroup);disposeGroup(effects);bubbles.length=0;const reef=world==='reef';floorGroup.scale.set(reef?1.65:1,1,reef?1.55:1);
scene.background.set(reef?'#bce1d5':'#cfe4bb');scene.fog.color.copy(scene.background);ground.material=material(reef?'#b9d9c6':'#c5d8ae');
block(floorGroup,reef?'#527e6d':'#7a9768',0,-.52,0,11.6,.5,7.2);block(floorGroup,reef?'#87ae97':'#a0b778',0,-.27,0,11.4,.12,7.0);
const geo=new T.PlaneGeometry(11,6.6,55,33);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,reef?Math.sin(x*1.2+z)*.055+Math.sin(z*3+x)*.025:0);}geo.computeVertexNormals();sandMaterial=reef?scannedMaterial('coast_sand_01',[4,3],'#ddd5b6'):new T.MeshStandardMaterial({color:'#a8bf80',roughness:.95});sandMaterial.onBeforeCompile=s=>{s.uniforms.uTime={value:0};sandMaterial.userData.shader=s;s.vertexShader='varying vec3 vWorld;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvWorld = position;');s.fragmentShader='uniform float uTime; varying vec3 vWorld;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>\nfloat a=sin(vWorld.x*5.0+sin(vWorld.z*3.0+uTime*.35))*sin(vWorld.z*5.0+sin(vWorld.x*2.0-uTime*.3));float b=pow(1.0-abs(a),24.0);diffuseColor.rgb = ${reef?'mix(vec3(.72,.66,.48),diffuseColor.rgb,.35)':'diffuseColor.rgb'};diffuseColor.rgb += vec3(b*${reef?'.19':'.02'});`)};mesh(floorGroup,geo,sandMaterial,0,-.13,0);
if(reef){aquariumSurface=reflectiveWater(new T.PlaneGeometry(11.2,6.7).rotateX(-Math.PI/2),{aquarium:true});aquariumSurface.position.y=4.22;floorGroup.add(aquariumSurface);const glass=new T.MeshPhysicalMaterial({color:'#82d9c8',transparent:true,opacity:.12,roughness:.06,metalness:.1,clearcoat:1,envMapIntensity:1.3,side:T.DoubleSide,depthWrite:false});block(floorGroup,'#244d4a',0,2,-3.43,11.3,4.5,.06);block(floorGroup,glass,0,2.0,-3.4,11.3,4.5,.055);for(const x of [-5.62,5.62])for(const z of [-3.4,3.4])block(floorGroup,'#354b42',x,2.1,z,.045,4.5,.045);for(const z of [-3.4,3.4])block(floorGroup,'#354b42',0,4.3,z,11.3,.08,.08);for(const x of [-5.62,5.62])block(floorGroup,glass,x,2,0,.05,4.5,6.8);const edge=new T.LineBasicMaterial({color:'#5d9d91',transparent:true,opacity:.45});const eg=new T.EdgesGeometry(new T.BoxGeometry(11.3,4.5,6.8));const lines=new T.LineSegments(eg,edge);lines.position.y=2;floorGroup.add(lines);
for(let i=0;i<160;i++){const r=.01+Math.random()*.025;orb(floorGroup,i%3?'#baa979':'#f5e8bc',rand(-5.3,5.3),-.06,rand(-3.1,3.1),r,r*.6,r)}
for(let i=0;i<42;i++){const b=new T.Mesh(new T.SphereGeometry(.035,8,6),new T.MeshBasicMaterial({color:'#e4fff2',transparent:true,opacity:.3,depthWrite:false}));b.position.set(rand(-5,5),rand(.2,4),rand(-2.9,2.9));b.userData.speed=rand(.04,.11);effects.add(b);bubbles.push(b)}
}else{block(floorGroup,'#d7cdb0',0,-.075,1.6,10.7,.05,1.3);block(floorGroup,'#d7cdb0',0,-.074,-.8,1.3,.05,5.2);for(let i=-5;i<=5;i++)block(floorGroup,'#faf2d5',i,-.04,1.6,.38,.02,.04);for(let i=0;i<10;i++)orb(floorGroup,'#8eaa6c',rand(-5.4,5.4),0,rand(-3,3),.06,.05,.06)}
}
function addObject(it){const g=makeModel(it.kind);g.position.set(it.x,it.y,it.z);g.rotation.y=it.rot;g.scale.setScalar(it.s);g.userData.item=it;g.traverse(o=>{o.userData.itemUid=it.uid});objects.set(it.uid,g);
if(D[it.kind].fish){fishGroup.add(g);g.position.y=D[it.kind].crawler?.04:rand(.8,3.4);fish.push({g,it,heading:rand(0,6.28),speed:rand(.35,.65),target:new T.Vector3(rand(-4,4),rand(.6,3.4),rand(-2,2)),next:rand(2,10),phase:rand(0,6.28)});}else{decor.add(g);if(['grass','anemone','fan','pinkcoral'].includes(it.kind))plants.push(g)}return g}
function rebuild(){objects.clear();fish.length=0;plants.length=0;disposeGroup(decor);disposeGroup(fishGroup);environment();state.worlds[world].forEach(addObject);person.visible=world==='town'&&!player.driving;car.visible=world==='town'&&player.driving;selected=null;selectionRing.visible=false;$('#selection').hidden=true;updateCount()}
function resize(){const r=$('#viewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=r.width<600?58:38;camera.updateProjectionMatrix();if(r.width<600)distance=Math.max(distance,21)}new ResizeObserver(resize).observe($('#viewport'));
function cameraPosition(dt=1){const desired=new T.Vector3(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.position.lerp(desired,Math.min(1,dt*6));camera.lookAt(target)}
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-lastFrame)/1000||.016);lastFrame=now;if(document.hidden)return;tickTanks(now,paused);elapsed+=dt;updatePlayer(dt);if(!paused){aquariumSurface?.userData.tick(elapsed);if(sandMaterial?.userData.shader)sandMaterial.userData.shader.uniforms.uTime.value=elapsed;
for(const f of fish){f.next-=dt;if(f.next<0){const portals=[...objects.values()].filter(g=>g.userData.portal);if(portals.length&&Math.random()<.35){const p=portals[Math.floor(Math.random()*portals.length)];f.target.copy(p.localToWorld(p.userData.portal.clone()));}else f.target.set(rand(-7.7,7.7),rand(.6,3.6),rand(-4,4));f.next=rand(5,12)}if(feedingUntil>elapsed)f.target.set(Math.sin(f.phase)*1.2,3.7,Math.cos(f.phase)*.7);
if(D[f.it.kind].crawler)f.target.y=.04;const delta=f.target.clone().sub(f.g.position);for(const g of decor.children){const def=D[g.userData.item.kind];if(def.portal||['grass','bubbles','flowers'].includes(def.id))continue;const offset=f.g.position.clone().sub(g.position);const r=def.r*g.scale.x+.3;if(offset.length()<r&&f.g.position.y<g.position.y+g.scale.x*1.5)delta.add(offset.normalize().multiplyScalar(2));}
if(delta.length()>.15){delta.normalize();f.g.position.addScaledVector(delta,dt*f.speed);const angle=Math.atan2(-delta.z,delta.x);f.g.rotation.y+=Math.atan2(Math.sin(angle-f.g.rotation.y),Math.cos(angle-f.g.rotation.y))*Math.min(1,dt*3);f.g.rotation.z=clamp(delta.y*.3,-.3,.3);}f.g.position.x=clamp(f.g.position.x,-8.1,8.1);f.g.position.z=clamp(f.g.position.z,-4.3,4.3);f.g.position.y=D[f.it.kind].crawler?.04:clamp(f.g.position.y,.35,3.9);if(f.g.userData.tail)f.g.userData.tail.rotation.y=Math.sin(elapsed*7+f.phase)*.35;f.g.userData.fins?.forEach((fin,i)=>fin.rotation.y=(i?1:-1)*(.6+Math.sin(elapsed*5+f.phase)*.15));if(f.g.userData.legs)f.g.userData.legs.forEach((l,i)=>l.rotation.y=Math.sin(elapsed*8+f.phase+i)*.12);}
for(const p of plants)p.rotation.z=Math.sin(elapsed*1.4+p.position.x)*.025;for(const b of bubbles){b.position.y+=dt*b.userData.speed*3;if(b.position.y>4)b.position.y=.1;}
for(const g of decor.children)if(g.userData.bubbler){if(Math.random()<dt*5)spawnBubble(g.position);}
for(let i=effects.children.length-1;i>=0;i--){const p=effects.children[i];if(!p.userData.life)continue;p.userData.life-=dt;p.position.y+=dt*(p.userData.food?-.5:.6);if(p.userData.life<=0){effects.remove(p);p.geometry.dispose();p.material.dispose();}}
}
if(follow&&world==='reef'&&fish.length){target.lerp(fish[(followIndex+fish.length)%fish.length].g.position,.03);distance=T.MathUtils.lerp(distance,5,dt*2);yaw+=paused?0:dt*.035;}else if(world==='town'&&job?.type==='delivery'){target.lerp(new T.Vector3(player.x,.6,player.z),.04);}else target.lerp(new T.Vector3(0,world==='reef'?1.2:.3,0),.03);
if(selected){const g=objects.get(selected.uid);if(g){selectionRing.position.set(g.position.x,selected.y+.06,g.position.z);selectionRing.scale.setScalar((D[selected.kind].r||.5)*selected.s*1.6)}}
if(job)tickJob();cameraPosition(dt);positionJobMarkers();const visibleRect=renderer.domElement.getBoundingClientRect();if(visibleRect.bottom>0&&visibleRect.top<innerHeight)renderer.render(scene,camera)}
function spawnBubble(pos){const b=new T.Mesh(new T.SphereGeometry(.065,8,6),new T.MeshStandardMaterial({color:'#bfffea',transparent:true,opacity:.5,roughness:.1}));b.position.copy(pos).add(new T.Vector3(rand(-.15,.15),.2,rand(-.15,.15)));b.userData.life=5;effects.add(b)}
function updateCount(){$('#itemCount').textContent=state.worlds[world].length}
function updateWallet(){$('#balance').textContent=Wallet.get()+' bucks';const n=Wallet.billCount();$('#billBadge').hidden=!n;$('#billBadge').textContent=n+' to save';if(state.goal&&!job){const d=D[state.goal];if(d){$('#questLabel').textContent='SAVING FOR '+d.name.toUpperCase();$('#questText').textContent=Math.min(Wallet.get(),d.price)+' / '+d.price+' bucks';$('#questDetail').textContent=Wallet.get()>=d.price?'You did it! Find it in the shop.':'Do a job, then put your bill in the piggy.';}}}
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);function rayAt(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera)}
function floorPoint(e,y=0){rayAt(e);plane.constant=-y;return ray.ray.intersectPlane(plane,new T.Vector3())}
let down=null,gesture=new Map(),pinchDistance=0;
renderer.domElement.addEventListener('pointerdown',e=>{renderer.domElement.setPointerCapture(e.pointerId);gesture.set(e.pointerId,[e.clientX,e.clientY]);down={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false,id:e.pointerId};if(gesture.size===2){const a=[...gesture.values()];pinchDistance=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);down.moved=true;}});
renderer.domElement.addEventListener('pointermove',e=>{if(!down||!gesture.has(e.pointerId))return;gesture.set(e.pointerId,[e.clientX,e.clientY]);if(gesture.size===2){const a=[...gesture.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);distance=clamp(distance+(pinchDistance-d)*.035,5,42);pinchDistance=d;down.moved=true;follow=false;return}if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)down.moved=true;if(down.moved){yaw-=(e.clientX-down.lastX)*.007;pitch=clamp(pitch+(e.clientY-down.lastY)*.004,.06,1.25);follow=false;}down.lastX=e.clientX;down.lastY=e.clientY});
renderer.domElement.addEventListener('pointerup',e=>{gesture.delete(e.pointerId);if(down&&!down.moved&&!gesture.size)tapWorld(e);down=null});renderer.domElement.addEventListener('pointercancel',()=>{down=null;gesture.clear()});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance+e.deltaY*.015,5,42);follow=false;},{passive:false});
function tapWorld(e){rayAt(e);if(job?.type==='clean'){const hit=ray.intersectObjects(jobGroup.children,true)[0];if(hit){const id=hit.object.userData.cleanId;const root=jobGroup.children.find(o=>o.userData.cleanId===id);if(root)collectLitter(id);return}}
if(pending){const p=floorPoint(e,pending.moving?selected.y:0);if(p)place(p.x,p.z);return}
const hits=ray.intersectObjects([...decor.children,...fishGroup.children],true);if(hits.length){const id=hits[0].object.userData.itemUid;selectItem(state.worlds[world].find(i=>i.uid===id));}else deselect();}
function selectItem(it){if(!it)return;selected=it;follow=false;$('#selection').hidden=false;$('#selectionName').textContent=D[it.kind].name;const isFish=!!D[it.kind].fish;for(const id of ['moveItem','turnItem','raiseItem','lowerItem','smallerItem','biggerItem'])$('#'+id).hidden=isFish;$('#removeItem').textContent=it.paid?'Return · '+it.paid+' bucks':'Put away';selectionRing.visible=!isFish;blip();}
function deselect(){selected=null;selectionRing.visible=false;$('#selection').hidden=true}
function pendingItem(kind){if(job){toast('Finish or leave your job first.');return}const d=D[kind];if(state.worlds[world].length>=65){toast('Your world is full. Put away a piece to make room.');return}if(d.fish&&fish.length>=28){toast('This tank has room for 28 animals.');return}if(Wallet.get()<d.price){state.goal=kind;save();updateWallet();toast('Saving goal set: '+d.name+'. Earn bucks with a job.');return}deselect();pending={kind};$('#placement').hidden=false;$('#placementText').textContent=d.fish?'Tap the water to welcome your fish':'Tap the '+(world==='reef'?'sand':'grass')+' to place '+d.name.toLowerCase();}
function place(x,z){if(!pending)return;const isMove=pending.moving;const d=D[pending.kind];const margin=(d.r||.6)*.3;const bx=world==='reef'?8:4.5,bz=world==='reef'?4.1:2.4;x=clamp(x,-bx+margin,bx-margin);z=clamp(z,-bz,bz);if(isMove&&selected){selected.x=x;selected.z=z;objects.get(selected.uid).position.set(x,selected.y,z);}else{if(Wallet.get()<d.price){toast('You need more saved bucks.');cancelPlacement();return}const it=entry(d.id,x,z);it.paid=d.price;Wallet.add(-d.price);state.worlds[world].push(it);addObject(it);selectItem(it);if(state.goal===d.id){state.goal=null;defaultQuest();}toast(d.name+' added!');}cancelPlacement();updateCount();save();blip('pop');}
function cancelPlacement(){pending=null;$('#placement').hidden=true}
function changeSelected(fn){if(!selected)return;fn(selected);const g=objects.get(selected.uid);g.position.set(selected.x,selected.y,selected.z);g.rotation.y=selected.rot;g.scale.setScalar(selected.s);save();}
$('#moveItem').onclick=()=>{pending={kind:selected.kind,moving:true};$('#placement').hidden=false;$('#placementText').textContent='Tap a new place for '+D[selected.kind].name.toLowerCase()};$('#turnItem').onclick=()=>changeSelected(i=>i.rot+=Math.PI/4);$('#smallerItem').onclick=()=>changeSelected(i=>i.s=clamp(i.s-.15,.6,1.6));$('#biggerItem').onclick=()=>changeSelected(i=>i.s=clamp(i.s+.15,.6,1.6));$('#raiseItem').onclick=()=>changeSelected(i=>i.y=clamp(i.y+.2,0,2));$('#lowerItem').onclick=()=>changeSelected(i=>i.y=clamp(i.y-.2,0,2));$('#closeSelection').onclick=deselect;$('#cancelPlace').onclick=cancelPlacement;$('#centerPlace').onclick=()=>place(0,.6);
$('#removeItem').onclick=()=>{if(!selected)return;const it=selected;state.worlds[world]=state.worlds[world].filter(i=>i.uid!==it.uid);if(it.paid)Wallet.add(it.paid);rebuild();save();toast(it.paid?'Returned. '+it.paid+' bucks back in your piggy.':'Put away. Free pieces are always in the shop.');};
const thumbs=new Map();let thumbRenderer;function thumbnail(id){if(thumbs.has(id))return thumbs.get(id);try{if(!thumbRenderer){thumbRenderer=new T.WebGLRenderer({alpha:true,antialias:true});thumbRenderer.setSize(220,150);thumbRenderer.setPixelRatio(1);thumbRenderer.outputColorSpace=T.SRGBColorSpace;thumbRenderer.toneMapping=T.ACESFilmicToneMapping;thumbRenderer.toneMappingExposure=1.5;}const s=new T.Scene();s.add(new T.HemisphereLight('#ffffff','#809575',3));const l=new T.DirectionalLight('#fff3db',3);l.position.set(-3,5,5);s.add(l);const m=makeModel(id);s.add(m);const b=new T.Box3().setFromObject(m),center=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3());m.position.sub(center);const c=new T.PerspectiveCamera(35,220/150,.1,30);const r=Math.max(size.x/1.4,size.y,size.z)*2.4;c.position.set(r*.65,r*.38,r);c.lookAt(0,0,0);thumbRenderer.render(s,c);const url=thumbRenderer.domElement.toDataURL('image/png');thumbs.set(id,url);disposeModel(m);return url;}catch{return ''}}
function catalog(){clearTanks();document.querySelector('.shop').classList.toggle('aquatics',world==='reef');document.querySelector('.shop h2').textContent=world==='reef'?'Welcome to Chilltopia Aquatics':'What will you build?';const cats=[...new Set(CATALOG.filter(d=>d.world===world).map(d=>d.category))];if(!cats.includes(category))category=cats[0];$('#shopTabs').replaceChildren();for(const c of cats){const b=document.createElement('button');b.textContent=c;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(c===category));b.onclick=()=>{category=c;catalog()};$('#shopTabs').append(b)}$('#catalog').replaceChildren();for(const d of CATALOG.filter(d=>d.world===world&&d.category===category)){if(world==='reef'){$('#catalog').append(displayTank(d,pendingItem));continue;}const b=document.createElement('button');b.className='card';b.setAttribute('aria-label',d.name+', '+(d.price?d.price+' bucks':'free'));const img=document.createElement('img');img.alt='';img.src=thumbnail(d.id);b.append(img);const name=document.createElement('span');name.className='card-name';name.textContent=d.name;const price=document.createElement('span');price.className='card-price';price.textContent=d.price?d.price+' bucks':'FREE TO BUILD';const plus=document.createElement('span');plus.className='plus';plus.textContent='+';b.append(name,price,plus);b.onclick=()=>pendingItem(d.id);$('#catalog').append(b)}}
function defaultQuest(){$('#questLabel').textContent='MAKE YOURSELF AT HOME';$('#questText').textContent=world==='reef'?'Pick a piece. Give it a place.':'Your town. Your next adventure.';$('#questDetail').textContent=world==='reef'?'Start with free rocks, plants, and a fish cave.':'Use arrow keys or the arrows to explore.';}
function switchWorld(w){if(job){toast('Finish or leave your job before changing worlds.');return}world=w;state.active=w;window.SFX?.ambience(w==='reef'?'water':'off');player.driving=false;autoRoute=[];player.x=1;player.z=2.6;follow=false;cancelPlacement();category=w==='reef'?'Habitat':'Garden';resetCamera();rebuild();catalog();$('#reefWorld').classList.toggle('active',w==='reef');$('#townWorld').classList.toggle('active',w==='town');$('#reefWorld').setAttribute('aria-pressed',String(w==='reef'));$('#townWorld').setAttribute('aria-pressed',String(w==='town'));$('#worldTitle').innerHTML=w==='reef'?'A little ocean.<br>A lot of possibility.':'A little town.<br>Built around you.';$('#worldSubtitle').textContent=w==='reef'?'Make a home for your imagination.':'Explore. Earn. Make yourself at home.';$('#feedBtn').innerHTML=w==='reef'?'◌ <span>Feed fish</span>':'◌ <span>Drive / walk</span>';$('#followBtn').innerHTML=w==='reef'?'◎ <span>Follow a fish</span>':'◎ <span>Visit your home</span>';$('#drivePad').hidden=w==='reef';$('#shopVisit').textContent=w==='reef'?'🐠 🛍️ Visit the fish store':'🛠️ ＋ Build my town';defaultQuest();updateWallet();save();}
function resetCamera(){follow=false;if(world==='reef')$('#followBtn').innerHTML='◎ <span>Follow a fish</span>';$('#game').classList.remove('chilling');yaw=.28;pitch=world==='reef'?.31:.65;distance=world==='reef'?(innerWidth<600?32:27):(innerWidth<600?23:18);target.set(0,world==='reef'?1.2:.3,0)}
$('#reefWorld').onclick=()=>switchWorld('reef');$('#townWorld').onclick=()=>switchWorld('town');$('#homeView').onclick=resetCamera;$('#leftView').onclick=()=>{follow=false;yaw-=.35};$('#rightView').onclick=()=>{follow=false;yaw+=.35};$('#zoomIn').onclick=()=>{follow=false;distance=clamp(distance-2,5,42)};$('#zoomOut').onclick=()=>{follow=false;distance=clamp(distance+2,5,42)};
$('#motionBtn').onclick=()=>{paused=!paused;$('#motionBtn').textContent=paused?'Resume motion':'Pause motion';$('#motionBtn').setAttribute('aria-pressed',String(paused));};$('#motionBtn').textContent=paused?'Resume motion':'Pause motion';
function paintSound(){sound=!!window.SFX?.on;$('#soundBtn').textContent=sound?'🔊':'🔇';$('#soundBtn').setAttribute('aria-pressed',String(sound));$('#soundBtn').title=sound?'Sound on. Tap to mute.':'Sound off. Tap to hear your world.';}$('#soundBtn').onclick=()=>{window.SFX?.toggle();paintSound();};document.addEventListener('soundchange',paintSound);paintSound();
function updatePlayer(dt){if(world!=='town')return;if(keys.size)autoRoute=[];if(autoRoute.length&&!$('#sheet').open){const p=autoRoute[0],dx=p.x-player.x,dz=p.z-player.z,len=Math.hypot(dx,dz);if(len<.1)autoRoute.shift();else{player.angle=Math.atan2(dx,dz);const step=Math.min(len,dt*2.4);player.x+=dx/len*step;player.z+=dz/len*step;}}const turn=(keys.has('left')?1:0)-(keys.has('right')?1:0),move=(keys.has('forward')?1:0)-(keys.has('back')?1:0);player.angle+=turn*dt*2.1;let nx=player.x+Math.sin(player.angle)*move*dt*(player.driving?2.8:1.6),nz=player.z+Math.cos(player.angle)*move*dt*(player.driving?2.8:1.6);const blocked=decor.children.some(g=>['townhouse','tower','tree','pool'].includes(g.userData.item.kind)&&Math.hypot(nx-g.position.x,nz-g.position.z)<D[g.userData.item.kind].r*.55*g.scale.x);if(!blocked){player.x=clamp(nx,-5,5);player.z=clamp(nz,-2.9,2.9)}person.visible=!player.driving;car.visible=player.driving;const parked=decor.children.find(g=>g.userData.item.kind==='car');if(parked)parked.visible=!player.driving;const p=player.driving?car:person;p.position.set(player.x,0,player.z);p.rotation.y=player.angle+(player.driving?-Math.PI/2:0);}
const keyMap={ArrowUp:'forward',w:'forward',W:'forward',ArrowDown:'back',s:'back',S:'back',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};addEventListener('keydown',e=>{if(e.key==='Escape'){cancelPlacement();deselect();return}if(world==='town'&&keyMap[e.key]&&!e.target.matches('input,select,textarea,[contenteditable]')&&!$('#sheet').open){e.preventDefault();keys.add(keyMap[e.key]);}});addEventListener('keyup',e=>keys.delete(keyMap[e.key]));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());for(const b of document.querySelectorAll('[data-drive]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.drive)};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.drive);}
$('#feedBtn').onclick=()=>{if(world==='town'){if(!state.worlds.town.some(i=>i.kind==='car')){toast('Add a roadster from the shop to drive.');return}if(player.driving){const parked=state.worlds.town.find(i=>i.kind==='car');if(parked){parked.x=player.x;parked.z=player.z;parked.rot=player.angle-Math.PI/2;const g=objects.get(parked.uid);g.position.set(parked.x,parked.y,parked.z);g.rotation.y=parked.rot;save();}player.x=clamp(player.x+.65,-5,5);}player.driving=!player.driving;toast(player.driving?'Drive with the arrows. Follow the road!':'Back on your feet.');return}if(!fish.length){toast('Welcome an animal before feeding.');return}if(!Wallet.canWork('feed')){toast('Feeding is finished for today. Their tummies have enough.');return}if(Date.now()-(state.lastFeed||0)<3500){toast('Watch them eat before the next small portion.');return}const day=new Date().toDateString();if(state.feedDay!==day){state.feedDay=day;state.feedPortions=0;}state.feedPortions=Math.min(3,(state.feedPortions||0)+1);state.lastFeed=Date.now();feedingUntil=elapsed+8;for(let i=0;i<8;i++){const p=new T.Mesh(new T.SphereGeometry(.035,6,6),new T.MeshStandardMaterial({color:'#ae7445'}));p.position.set(rand(-1,1),4,rand(-.6,.6));p.userData.life=7;p.userData.food=true;effects.add(p)}save();blip('splash');if(state.feedPortions<3)toast('Small portion '+state.feedPortions+' of 3. Watch them eat, then feed again.');else Wallet.completeWork('feed').then(pay=>{toast(pay?'Three small portions, with time to eat. 5 bucks earned!':'Feeding is already paid today.');if(pay)piggy();});};
$('#followBtn').onclick=()=>{if(world==='town'){player.x=0;player.z=-1;resetCamera();toast('Welcome home.');return}if(!fish.length){toast('Add a fish from the shop first.');return}followIndex=(followIndex+1)%fish.length;follow=true;$('#game').classList.add('chilling');$('#followBtn').innerHTML='◎ <span>Next animal</span>';toast('Meet your '+D[fish[followIndex].it.kind].name+'. Tap Next animal to explore.');};
function openSheet(label,html){keys.clear();$('#sheetLabel').textContent=label;$('#sheetBody').innerHTML=html;$('#sheet').showModal();}$('#closeSheet').onclick=()=>$('#sheet').close();$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const r=$('#sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#sheet').close()}});
$('#helpBtn').onclick=()=>openSheet('A LITTLE HELP','<h2>Your world, your way.</h2><ol class="help-list"><li>Pick something from the shop. Free pieces are always yours to use.</li><li>Tap the sand or grass to place it. Tap a placed piece to move, turn, resize, or put it away.</li><li>Drag the view to look around. Use the camera buttons to zoom or return home.</li><li>Choose Earn bucks. Finish the job, then drag your paycheck into your piggy bank.</li><li>Save for a favorite fish or decoration. When you have enough, bring it home!</li></ol><p class="note">Keyboard: Tab through buttons; Enter to choose. Use Place in center if you cannot tap the world. Your collection lets you select every piece.</p>');
$('#grownupsBtn').onclick=()=>openSheet('FOR GROWN-UPS','<h2>A world for learning.</h2><p>Chilltopia connects completing work, depositing a paycheck, saving toward a goal, and choosing what to buy. All bucks are pretend. There are no purchases, accounts, ads, or uploads.</p><p>This aquarium is a creative animal sandbox, not a real fish-care or species-compatibility guide. Crayfish are freshwater animals; this make-believe collection does not mean they belong in a saltwater reef. Fish never die, and there is no punishment for taking a break.</p><p>Progress stays in this browser on this device. Clearing site data removes it. Classic worlds are kept separately, and the piggy bank is shared with the rest of Chillion Bucks.</p><p class="note">The 3D world uses the open-source Three.js library, included with the site. No game server or paid API is used.</p><a href="classic.html">Open the classic builder</a>');
$('#collectionBtn').onclick=()=>{openSheet('YOUR COLLECTION','<h2>Everything in your world.</h2><p>Choose a piece to move or put away.</p><div class="owned-list" id="ownedList"></div>');for(const it of state.worlds[world]){const b=document.createElement('button');b.textContent=D[it.kind].name;b.onclick=()=>{$('#sheet').close();selectItem(it)};$('#ownedList').append(b)}};
function piggy(){openSheet('WORK → SAVE → BUILD','<div id="savingsGame"></div>');mountSavings($('#savingsGame'),Wallet,window.SFX);}
$('#walletBtn').onclick=piggy;
function workMenu(){if(job){openSheet('JOB IN PROGRESS','<h2>Keep going!</h2><p>'+job.progress+' of '+job.total+' done.</p><button class="wide-button" id="resumeJob">Back to the job</button><button class="wide-button" id="leaveJob">Leave this job</button>');$('#resumeJob').onclick=()=>$('#sheet').close();$('#leaveJob').onclick=()=>{endJob(false);$('#sheet').close()};return}openSheet('A LITTLE WORK. A LITTLE CLOSER.','<h2>Choose a helpful job.</h2><p>Small portions feed your animals. Cleaning keeps their home clear. Choose what to do, then save for something you like.</p><button class="job-choice" id="feedJob" '+(!Wallet.canWork('feed')?'disabled':'')+'>🐠 Feeding <b>5 bucks</b><small>Three small portions, with a pause between each. Once per day.</small></button><button class="job-choice" id="cleanJob" '+(!Wallet.canWork('clean')?'disabled':'')+'>🫧 Aquarium cleanup <b>10 bucks</b><small>Collect 10 bits of litter. Once per day.</small></button><a class="job-choice" href="seafood.html">🦞 Seafood Scoop <b>10 bucks</b><small>Tap to close your underwater claw. Catch five. Once per day; free practice anytime.</small></a><button class="job-choice" id="deliveryJob" '+(!Wallet.canWork('delivery')?'disabled':'')+'>📦 Neighborhood delivery <b>10 bucks</b><small>Deliver four packages. '+Wallet.workInfo('delivery').left+' paid trips left today.</small></button><p class="note">Up to 45 bucks across all jobs each day. Building stays open after the work is done. No streaks to lose, and no penalties for taking a break.</p>');$('#feedJob').onclick=()=>{$('#sheet').close();switchWorld('reef');toast('Tap Feed fish for each of three small portions.');};$('#cleanJob').onclick=()=>startJob('clean');$('#deliveryJob').onclick=()=>startJob('delivery');}
$('#workBtn').onclick=workMenu;
function startJob(type){if(!Wallet.canWork(type)||job)return;$('#sheet').close();switchWorld(type==='clean'?'reef':'town');cancelPlacement();deselect();job={type,progress:0,total:type==='clean'?10:4,started:Date.now(),stop:0};if(type==='clean'){for(let i=0;i<10;i++){const g=new T.Group();g.userData.cleanId=i;const m=orb(g,'#dfad69',0,0,0,.18,.14,.15);m.userData.cleanId=i;const top=block(g,'#f0d499',0,.12,0,.19,.03,.19);top.userData.cleanId=i;g.position.set(-6.5+(i%5)*3.25,.18,-2.5+Math.floor(i/5)*5);jobGroup.add(g);const b=document.createElement('button');b.dataset.litter=i;b.setAttribute('aria-label','Collect litter '+(i+1));b.textContent='♻';b.onclick=()=>collectLitter(i);jobMarkers.append(b)}}else{player.driving=true;player.x=0;player.z=2.6;player.angle=Math.PI;makeDeliveryStop();}updateJobText();toast(type==='clean'?'Tap the golden litter pieces to tidy the reef.':'Use the arrows, or tap Drive to next stop.');}
const stops=[[-3,1.6],[3,1.6],[0,-1.1],[-3,1.6]];
function makeDeliveryStop(){disposeGroup(jobGroup);jobMarkers.replaceChildren();const assist=document.createElement('button');assist.className='delivery-assist';assist.textContent='📦 Drive to next stop';assist.onclick=()=>{if(job?.type!=='delivery')return;const [tx,tz]=stops[job.progress];autoRoute=[{x:player.x,z:1.6},{x:tx,z:1.6},{x:tx,z:tz}];};jobMarkers.append(assist);const [x,z]=stops[job.progress];const ring=mesh(jobGroup,new T.TorusGeometry(.6,.08,8,40),new T.MeshBasicMaterial({color:'#fff3a5'}),x,.12,z);ring.rotation.x=-Math.PI/2;const p=block(jobGroup,'#e7b466',x,.65,z,.35,.35,.35);p.rotation.y=.4;block(jobGroup,'#fff2c1',x,.66,z,.1,.36,.36)}
function updateJobText(){$('#questLabel').textContent=job.type==='clean'?'REEF CLEANUP':'NEIGHBORHOOD DELIVERY';$('#questText').textContent=job.progress+' / '+job.total+(job.type==='clean'?' pieces collected':' packages delivered');$('#questDetail').textContent=job.type==='clean'?'Tap the golden litter. Earn bucks opens the job menu.':'Steer with arrows, or tap Drive to next stop.';}
function tickJob(){if(job.type==='delivery'){const [x,z]=stops[job.progress];if(Math.hypot(player.x-x,player.z-z)<.65&&!keys.has('forward')&&!keys.has('back')&&!autoRoute.length){if(!job.stop)job.stop=Date.now();if(Date.now()-job.stop>1100){job.progress++;job.stop=0;blip('chaChing');if(job.progress<job.total)makeDeliveryStop();updateJobText();}}else job.stop=0;}if(job.progress>=job.total){if(Date.now()-job.started<12000){$('#questDetail').textContent='Nice work! Checking your job…';return}endJob(true)}}
async function endJob(success){const type=job?.type;disposeGroup(jobGroup);jobMarkers.replaceChildren();autoRoute=[];job=null;defaultQuest();if(success){state.jobs++;save();const paid=await Wallet.completeWork(type);if(paid){blip('cheer');toast(type==='clean'?'You collected every piece. 10 bucks earned!':'Four packages delivered. 10 bucks earned!');piggy();}else toast('That job is already paid today. Enjoy your world!');}updateWallet();}
document.addEventListener('wallet',updateWallet);
switchWorld(new URLSearchParams(location.search).get('world')==='town'?'town':new URLSearchParams(location.search).get('world')==='reef'?'reef':world);resize();cameraPosition();$('#loading').remove();requestAnimationFrame(animate);

if(new URLSearchParams(location.search).has('work'))workMenu();

$('#shopVisit').onclick=()=>{document.querySelector('.shop').scrollIntoView({behavior:'auto',block:'start'});window.SFX?.tap();};

if(new URLSearchParams(location.search).has("bank"))piggy();
