import * as T from './vendor/three.module.js';
export function makeCar(){
 const car=new T.Group(),body=new T.Group();car.add(body);const paint=new T.MeshPhysicalMaterial({color:'#c3d2df',metalness:.7,roughness:.26,clearcoat:1,clearcoatRoughness:.14}),blue=new T.MeshStandardMaterial({color:'#205ccc',metalness:.55,roughness:.27}),dark=new T.MeshStandardMaterial({color:'#142333',metalness:.35,roughness:.23}),rubber=new T.MeshStandardMaterial({color:'#182126',roughness:.9}),chrome=new T.MeshStandardMaterial({color:'#cdd5dd',metalness:.95,roughness:.2}),red=new T.MeshStandardMaterial({color:'#c72335',emissive:'#ed2333',emissiveIntensity:.7}),white=new T.MeshStandardMaterial({color:'#edffff',emissive:'#b9eaff',emissiveIntensity:1});
 function box(w,h,d,x,y,z,m=paint){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;body.add(o);return o;}
 // Local forward is +Z. A broad, angular coupe with a long hood and rear wing.
 box(1.95,.45,4.55,0,.68,0);box(2.03,.22,4.2,0,.49,0);box(1.92,.15,1.35,0,.96,1.46);box(1.91,.13,.95,0,.98,-1.73);
 const shape=new T.Shape();shape.moveTo(-1.36,0);shape.lineTo(-.78,.64);shape.lineTo(.47,.64);shape.lineTo(1.12,0);shape.closePath();const cabinGeo=new T.ExtrudeGeometry(shape,{depth:1.65,bevelEnabled:false});cabinGeo.rotateY(-Math.PI/2);cabinGeo.translate(.825,1.01,0);const cabin=new T.Mesh(cabinGeo,dark);cabin.castShadow=true;body.add(cabin);box(1.73,.085,1.25,0,1.68,-.15);
 for(const side of [-1,1]){box(.055,.56,.085,side*.86,1.34,-.17,paint);box(.25,.14,.32,side*1.075,1.17,.72);box(.055,.025,.19,side*.995,.97,-.45,chrome);box(.07,.16,3.3,side*1.035,.43,0,blue);box(.03,.02,1.5,side*.98,.91,-.25,dark);}
 for(const x of [-.32,.32]){box(.18,.013,1.38,x,1.044,1.45,blue);box(.18,.013,.95,x,1.052,-1.73,blue);box(.18,.013,1.25,x,1.73,-.15,blue);}
 box(1.42,.18,.045,0,.62,2.3,dark);box(.8,.17,.055,0,.44,2.3,dark);for(let x=-.5;x<=.5;x+=.14)box(.045,.15,.058,x,.62,2.33,chrome);
 for(const x of [-.7,.7]){box(.49,.16,.04,x,.86,2.29,white);box(.22,.1,.045,x,.5,2.3,white);}
 box(1.75,.27,.055,0,.83,-2.295,dark);for(const side of [-1,1])for(const x of [.47,.77]){const lamp=new T.Mesh(new T.CylinderGeometry(.105,.105,.05,24),red);lamp.rotation.x=Math.PI/2;lamp.position.set(side*x,.86,-2.34);body.add(lamp);}
 for(const x of [-.65,.65])box(.07,.4,.12,x,1.22,-1.98,dark);box(2.05,.09,.42,0,1.45,-1.98);for(const x of [-1.02,1.02])box(.04,.21,.48,x,1.46,-1.98,blue);
 const exhaust=new T.Mesh(new T.CylinderGeometry(.09,.09,.25,16),chrome);exhaust.rotation.x=Math.PI/2;exhaust.position.set(-.65,.43,-2.35);body.add(exhaust);
 const wheels=[];for(const x of [-1,1])for(const z of [-1.43,1.4]){const pivot=new T.Group();pivot.position.set(x,.43,z);body.add(pivot);const spin=new T.Group();pivot.add(spin);const tire=new T.Mesh(new T.CylinderGeometry(.43,.43,.28,32),rubber);tire.rotation.z=Math.PI/2;spin.add(tire);const rim=new T.Mesh(new T.CylinderGeometry(.31,.31,.29,24),dark);rim.rotation.z=Math.PI/2;spin.add(rim);for(let a=0;a<6;a++){const spoke=new T.Mesh(new T.BoxGeometry(.305,.055,.57),chrome);spoke.rotation.x=a*Math.PI/3;spin.add(spoke);}wheels.push({pivot,spin,front:z>0});}
 const shadow=new T.Mesh(new T.PlaneGeometry(2.8,5.2),new T.MeshBasicMaterial({color:'#0b1820',transparent:true,opacity:.15,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.015;car.add(shadow);
 return {car,body,paint,wheels};
}
export class Motor{
 constructor(){this.a=null;this.on=false;}
 start(){if(!window.SFX?.on)return;try{if(!this.a){const a=this.a=new(window.AudioContext||window.webkitAudioContext)(),master=this.master=a.createGain();master.gain.value=0;const compressor=a.createDynamicsCompressor();master.connect(compressor).connect(a.destination);this.oscs=[1,2,3].map((n,i)=>{const o=a.createOscillator(),g=a.createGain();o.type=i?'triangle':'sawtooth';g.gain.value=[.19,.08,.035][i];const f=a.createBiquadFilter();f.type='lowpass';f.frequency.value=850;o.connect(g).connect(f).connect(master);o.start();return o;});const buffer=a.createBuffer(1,a.sampleRate*2,a.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const n=a.createBufferSource();n.buffer=buffer;n.loop=true;const filter=a.createBiquadFilter();filter.type='bandpass';filter.frequency.value=1800;filter.Q.value=2;this.hiss=a.createGain();this.hiss.gain.value=0;n.connect(filter).connect(this.hiss).connect(master);n.start();this.turbo=a.createOscillator();this.turbo.type='sine';this.turboGain=a.createGain();this.turboGain.gain.value=.018;this.turbo.connect(this.turboGain).connect(master);this.turbo.start();}this.a.resume().catch(()=>{});}catch{}}
 update(speed,drift,running,time){if(!this.a)return;const t=this.a.currentTime,active=running&&window.SFX?.on&&!document.hidden;this.master.gain.setTargetAtTime(active?.38:0,t,.12);const gear=Math.floor(speed/6),rev=45+(speed%6)*13+Math.sin(time*8)*1.3+(drift?16:0);this.oscs.forEach((o,i)=>o.frequency.setTargetAtTime(rev*(i+1),t,.07));this.turbo.frequency.setTargetAtTime(1100+speed*65,t,.12);this.hiss.gain.setTargetAtTime(drift?.13:.013,t,.12);if(this.gear!==undefined&&gear!==this.gear&&active)window.SFX?.noise(.12,.02,1400);this.gear=gear;}
 quiet(){if(this.a){this.master.gain.setValueAtTime(0,this.a.currentTime);this.a.suspend().catch(()=>{});}}
}

export function driftStep(state,{held,running,turn,dt}){const sliding=held&&running&&Math.abs(turn)>.045;const angle=state.angle+((sliding?Math.sign(turn)*.53:0)-state.angle)*(1-Math.exp(-dt*5));let seconds=state.seconds,awarded=state.awarded,award=false;if(sliding){seconds+=dt;if(seconds>1&&!awarded){awarded=true;award=true;}}else if(!held){seconds=0;awarded=false;}return {angle,seconds,awarded,award,sliding};}
