import * as T from './vendor/three.module.js';
import {PRESETS,copy,curveFor,validate,editPoints,ribbon,WIDTH} from './driving-track.js?v=handling3';
import {makeCar,Motor,driftStep} from './driving-car.js?v=handling3';
import {CHECKPOINTS,crossedCheckpoints} from './driving-adventure.js';
import {loadLighting,scannedMaterial} from './realism.js?v=estates4';
const $=s=>document.querySelector(s),KEY='cb:drive:v1',clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let custom=null,active='meadow',color='#c3d2df',pace='cruise';try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.v===1){if(s.custom&&!validate(s.custom))custom=copy(s.custom);if(PRESETS[s.active]||(s.active==='custom'&&custom))active=s.active;if(/^#[0-9a-f]{6}$/i.test(s.color))color=s.color;if(['gentle','cruise','zoom'].includes(s.pace))pace=s.pace;}}catch{}
let points=copy(active==='custom'?custom:PRESETS[active].points),curve,length,editing=false,selected=0,history=[],running=false,driftHeld=false,driftAmount=0,driftVelocity=0,driftSeconds=0,driftAwarded=false,drifts=0,laps=0,travel=0,speed=0,lane=0,steer=0,view=reduced?2:0,last=0;
let starGates=[],lapStars=0,mapPoints=[],trackCenter=new T.Vector3(),trackSpan={x:1,z:1},mapBounds=null;
function tell(s){$('#message').textContent=s;}function save(){try{localStorage.setItem(KEY,JSON.stringify({v:1,active,custom,color,pace}));$('#save').textContent='✓ Your custom track is saved on this device.';}catch{$('#save').textContent='Storage is unavailable. Keep this tab open to keep playing.';}}
window.SFX?.bind($('#sound'));window.SFX?.ambience('off');const motor=new Motor();
new ResizeObserver(([entry])=>document.documentElement.style.setProperty('--drive-header',entry.target.getBoundingClientRect().height+'px')).observe(document.querySelector('header'));
const host=$('#viewport');let renderer;try{renderer=new T.WebGLRenderer({antialias:true});}catch{$('#loading').innerHTML='This device could not start 3D. <a href="classic.html">Play Classic</a>';throw Error('WebGL unavailable');}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Driving world. Space to drift, arrow keys to move.');host.append(renderer.domElement);$('#loading').remove();
const scene=new T.Scene();scene.background=new T.Color('#bbdcec');scene.fog=new T.Fog('#bbd4c5',170,420);const camera=new T.PerspectiveCamera(48,1,.5,600);scene.add(new T.HemisphereLight('#eef9ff','#626d43',.6));const sun=new T.DirectionalLight('#fff0cb',3);sun.position.set(-55,95,35);sun.castShadow=true;sun.shadow.mapSize.set(innerWidth<650?1024:2048,innerWidth<650?1024:2048);Object.assign(sun.shadow.camera,{left:-105,right:105,top:105,bottom:-105,far:240});sun.shadow.normalBias=.05;scene.add(sun);loadLighting(renderer,scene,'park');
const mat=(color,roughness=.8)=>new T.MeshStandardMaterial({color,roughness});
const ground=new T.Mesh(new T.PlaneGeometry(1200,1200),scannedMaterial('leafy_grass',[140,140],'#a9b795'));ground.rotation.x=-Math.PI/2;ground.position.y=-.18;ground.receiveShadow=true;scene.add(ground);
function mesh(g,m,x,y,z,parent=scene){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
const asphalt=mat('#424b51'),verge=mat('#c8b88c'),lineMat=mat('#faf2d4'),supportMat=mat('#c1c5b8'),archMat=mat('#173f47'),red=mat('#e26450'),white=mat('#fff9e5');
// Original repeating asphalt grain, without an external asset request.
const grain=document.createElement('canvas');grain.width=grain.height=128;const gx=grain.getContext('2d');gx.fillStyle='#7a7e80';gx.fillRect(0,0,128,128);for(let i=0;i<6000;i++){const v=100+Math.random()*65;gx.fillStyle=`rgb(${v},${v},${v})`;gx.fillRect(Math.random()*128,Math.random()*128,1,1);}const gt=new T.CanvasTexture(grain);gt.wrapS=gt.wrapT=T.RepeatWrapping;asphalt.map=gt;
const road=new T.Group(),dots=new T.Group(),scenery=new T.Group();scene.add(road,dots,scenery);const dotGeo=new T.SphereGeometry(2,16,12),dotMat=mat('#ffdb58'),selectedMat=mat('#96ff55');
const {car,body,paint,wheels}=makeCar();scene.add(car);paint.color.set(color);
const smoke=[];for(let i=0;i<28;i++){const p=mesh(new T.SphereGeometry(.4,8,6),new T.MeshBasicMaterial({color:'#fff8e5',transparent:true,opacity:0,depthWrite:false}),0,-10,0);p.castShadow=false;p.visible=false;smoke.push({mesh:p,life:0});}let smokeIndex=0,smokeClock=0;
function disposeGroup(group){for(const child of [...group.children]){child.traverse(o=>{if(o.isMesh&&o.geometry!==dotGeo)o.geometry.dispose();if(o.isSprite)o.material.map?.dispose();if(o.userData.disposableMaterial||group===scenery)o.material?.dispose();});group.remove(child);}}
function marker(text){const c=document.createElement('canvas');c.width=128;c.height=128;const x=c.getContext('2d');x.fillStyle='#163f42';x.beginPath();x.arc(64,64,54,0,7);x.fill();x.fillStyle='#fff';x.font='bold 65px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,64,68);const m=new T.SpriteMaterial({map:new T.CanvasTexture(c),depthTest:false}),s=new T.Sprite(m);s.scale.set(9,9,1);s.userData.disposableMaterial=true;return s;}
function rebuild(){
 curve=curveFor(points);length=curve.getLength();disposeGroup(road);disposeGroup(dots);
 for(const [a,b,m,lift] of [[-5.1,-4,verge,-.025],[4,5.1,verge,-.025],[-4,4,asphalt,0],[-3.8,-3.68,lineMat,.025],[3.68,3.8,lineMat,.025]]){const o=new T.Mesh(ribbon(curve,a,b,500,lift),m);o.receiveShadow=true;road.add(o);}
 const segs=Math.ceil(length/2);for(let i=0;i<segs;i++){const t=i/segs,p=curve.getPointAt(t),d=curve.getTangentAt(t),n=new T.Vector3(-d.z,0,d.x).normalize();for(const side of [-1,1]){const o=mesh(new T.BoxGeometry(.52,.11,length/segs*1.04),i%2?white:red,p.x+n.x*4.2*side,p.y+.03,p.z+n.z*4.2*side,road);o.rotation.y=Math.atan2(d.x,d.z);o.rotation.x=-Math.asin(d.y);o.castShadow=false;}if(i%8===0&&p.y>1.5){const pier=mesh(new T.BoxGeometry(6,p.y-.5,.85),supportMat,p.x,(p.y-.5)/2-.05,p.z,road);pier.rotation.y=Math.atan2(d.x,d.z);}}
 const start=curve.getPointAt(0),dir=curve.getTangentAt(0),arch=new T.Group();arch.position.copy(start);arch.rotation.y=Math.atan2(dir.x,dir.z);road.add(arch);for(const x of [-5.5,5.5])mesh(new T.BoxGeometry(.4,7,.4),supportMat,x,3.5,0,arch);mesh(new T.BoxGeometry(11.5,1.15,.35),archMat,0,7,0,arch);
 for(let x=0;x<14;x++)for(let y=0;y<2;y++){const o=mesh(new T.BoxGeometry(.78,.48,.06),(x+y)%2?white:asphalt,(x-6.5)*.78,6.77+y*.48,.21,arch);o.castShadow=false;const back=o.clone();back.position.z=-.21;arch.add(back);}
 for(let x=0;x<10;x++)for(let z=0;z<2;z++){const o=mesh(new T.BoxGeometry(.8,.025,.8),(x+z)%2?white:asphalt,(x-4.5)*.8,.04,z*.8,arch);o.castShadow=false;}
 points.forEach((p,i)=>{const dot=new T.Mesh(dotGeo,i===selected?selectedMat:dotMat);dot.position.set(p[0],p[1]+1.1,p[2]);dot.scale.setScalar(2);dot.userData.index=i;dots.add(dot);const label=marker(String(i+1));label.position.set(p[0],p[1]+5,p[2]);dots.add(label);});dots.visible=editing;
 $('#piece').replaceChildren(...points.map((_,i)=>{const o=document.createElement('option');o.value=i;o.textContent='● '+(i+1);return o;}));$('#piece').value=selected;$('#undo').disabled=!history.length;
 buildScenery();buildStarGates();cacheTrack();renderTracks();$('#trackName').textContent=editing?'My track workshop':active==='custom'?'My own track':PRESETS[active].name;
}
function buildScenery(){disposeGroup(scenery);const scenerySamples=curve.getSpacedPoints(120),near=(x,z)=>scenerySamples.some(p=>Math.hypot(p.x-x,p.z-z)<11);
 if(active==='coast'){const water=mesh(new T.PlaneGeometry(280,800),new T.MeshPhysicalMaterial({color:'#39b9c9',metalness:.25,roughness:.19}),235,-.12,0,scenery);water.rotation.x=-Math.PI/2;water.castShadow=false;}
 const bark=mat('#78664b'),leaves=mat('#427d57'),leaves2=mat('#72945d');
 for(let i=0;i<70;i++){const angle=i*2.3999,r=28+((i*37)%80),x=Math.sin(angle)*r,z=Math.cos(angle)*r;if(near(x,z))continue;const tree=new T.Group();tree.position.set(x,0,z);scenery.add(tree);mesh(new T.CylinderGeometry(.16,.3,3,6),bark,0,1.5,0,tree);for(let j=0;j<3;j++)mesh(new T.IcosahedronGeometry(1.7+j*.2,1),j%2?leaves:leaves2,Math.sin(j*2)*.6,3.4+j*.6,Math.cos(j*2)*.6,tree);}
 for(let i=0;i<16;i++){const a=i/16*Math.PI*2,r=180+(i%3)*28,m=mesh(new T.ConeGeometry(40+(i%4)*12,30+(i%5)*12,7),mat(i%2?'#91a486':'#9aab8b'),Math.cos(a)*r,7,Math.sin(a)*r,scenery);m.rotation.y=i*.9;}
 // Spectator terraces and bright sunshades outside the racing line.
 for(let i=0;i<3;i++){const x=-70,z=-28+i*20;if(near(x,z))continue;for(let j=0;j<4;j++)mesh(new T.BoxGeometry(10,.6,1.8),j%2?mat('#6995b2'):supportMat,x,j*.7+1,z+j*1.7,scenery);mesh(new T.BoxGeometry(12,.2,9),mat(i%2?'#e8b356':'#518d9b'),x,6,z+3,scenery);for(const dx of [-5,5])mesh(new T.CylinderGeometry(.09,.09,6,6),supportMat,x+dx,3,z+3,scenery);}
}
function cacheTrack(){
 mapPoints=curve.getSpacedPoints(100);
 const xs=mapPoints.map(p=>p.x),zs=mapPoints.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);
 mapBounds={x:(minX+maxX)/2,z:(minZ+maxZ)/2,scale:Math.min(150/(maxX-minX),100/(maxZ-minZ))};
 trackCenter.set((minX+maxX)/2,points.reduce((v,p)=>v+p[1],0)/points.length,(minZ+maxZ)/2);
 trackSpan={x:maxX-minX+18,z:maxZ-minZ+22};
}
function updateStars(){
 $('#starCount').textContent='★ '.repeat(lapStars)+'☆ '.repeat(5-lapStars);
 $('#starCount').setAttribute('aria-label',lapStars+' of 5 stars collected');
 $('#starHint').textContent=lapStars===5?'All five! Head for the finish.':'Star trail · '+lapStars+' of 5';
}
function buildStarGates(){
 starGates=[];lapStars=0;updateStars();
 for(const [index,t] of CHECKPOINTS.entries()){
  const p=curve.getPointAt(t),d=curve.getTangentAt(t),g=new T.Group();g.position.copy(p);g.rotation.y=Math.atan2(d.x,d.z);road.add(g);
  const glow=new T.MeshStandardMaterial({color:'#ffe78a',emissive:'#ffc44f',emissiveIntensity:.3,roughness:.5});
  const ring=mesh(new T.TorusGeometry(3.5,.1,6,40,Math.PI),glow,0,.12,0,g);ring.castShadow=false;ring.userData.disposableMaterial=true;
  const shape=new T.Shape();for(let i=0;i<10;i++){const angle=Math.PI/2+i*Math.PI/5,r=i%2?.29:.63;const x=Math.cos(angle)*r,y=Math.sin(angle)*r;i?shape.lineTo(x,y):shape.moveTo(x,y);}shape.closePath();
  const star=mesh(new T.ExtrudeGeometry(shape,{depth:.16,bevelEnabled:false}),glow,0,3.7,-.08,g);star.castShadow=false;
  const badge=marker(String(index+1));badge.scale.set(1.05,1.05,1);badge.position.set(-3.8,1,0);g.add(badge);
  g.visible=!editing;starGates.push({g,star,index,collected:false});
 }
}

function trackSvg(p){const c=curveFor(p),v=c.getSpacedPoints(80);return '<svg viewBox="-110 -65 220 130" aria-hidden="true"><path d="M'+v.map(q=>q.x+','+q.z).join(' L')+' Z" fill="none" stroke="#f7f2d9" stroke-width="12" stroke-linejoin="round"/><path d="M'+v.map(q=>q.x+','+q.z).join(' L')+' Z" fill="none" stroke="#4b6263" stroke-width="7"/></svg>';}
function renderTracks(){$('#tracks').replaceChildren();for(const [key,def] of Object.entries({...PRESETS,...(custom?{custom:{name:'My own track',icon:'🛠️',points:custom}}:{})})){const b=document.createElement('button');b.className='track-card';b.setAttribute('aria-pressed',String(active===key));b.setAttribute('aria-label',def.name);b.innerHTML=trackSvg(def.points)+'<span>'+def.icon+' '+def.name+'</span>';b.onclick=()=>{if(editing)return;active=key;points=copy(def.points);selected=0;reset();rebuild();save();tell('Tap GO to explore '+def.name+'.');$('#game').scrollIntoView({behavior:'smooth'});};$('#tracks').append(b);}}
function reset(){travel=0;lapStars=0;for(const gate of starGates){gate.collected=false;gate.g.visible=!editing;}updateStars();speed=0;running=false;driftHeld=false;driftSeconds=0;driftAwarded=false;lane=0;driftAmount=0;driftVelocity=0;$('#drift').setAttribute('aria-pressed','false');$('#go').textContent=editing?'👍 Drive!':'👍 GO!';motor.quiet();cameraReady=false;}
function begin(){if(editing){leaveBuild();return;}running=!running;$('#go').textContent=running?'⏸ Pause':'👍 GO!';if(running){renderer.domElement.focus({preventScroll:true});motor.start();window.SFX?.unlock();tell('You are driving! Hold 💨 to drift through a corner.');}else{releaseDrift();motor.quiet();tell('Parked. Tap GO whenever you are ready.');}}
$('#go').onclick=begin;$('#restart').onclick=()=>{reset();tell('Back at the start. Ready when you are!');};
const names=['📷 Chase view','🚘 Driver view','🦅 Aerial view','🚙 Look at my car'];function setCamera(){view=(view+1)%4;$('#camera').textContent=names[view];cameraReady=false;}$('#camera').textContent=names[view];$('#camera').onclick=setCamera;
function holdDrift(e){e?.preventDefault();if(!running||editing){tell('Tap GO first, then hold DRIFT.');return;}motor.start();driftHeld=true;$('#drift').setAttribute('aria-pressed','true');if(e?.pointerId!==undefined)$('#drift').setPointerCapture(e.pointerId);}
function releaseDrift(){driftHeld=false;$('#drift').setAttribute('aria-pressed','false');driftSeconds=0;driftAwarded=false;}
$('#drift').onpointerdown=holdDrift;$('#drift').onkeydown=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(!e.repeat)holdDrift();}};$('#drift').onkeyup=e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();releaseDrift();}};for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#drift').addEventListener(event,releaseDrift);
for(const [id,value] of [['left',-1],['right',1]]){$('#'+id).onpointerdown=e=>{e.preventDefault();steer=value;e.target.setPointerCapture(e.pointerId);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('#'+id).addEventListener(ev,()=>steer=0);}$('.steer').hidden=false;
addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea,button')||$('#helpSheet').open)return;if(e.code==='Space'){e.preventDefault();if(!e.repeat)holdDrift();}if(e.key==='ArrowLeft'){e.preventDefault();steer=-1;}if(e.key==='ArrowRight'){e.preventDefault();steer=1;}});addEventListener('keyup',e=>{if(e.code==='Space')releaseDrift();if(e.key.startsWith('Arrow'))steer=0;});
function pauseForAway(){running=false;releaseDrift();steer=0;$('#go').textContent=editing?'👍 Drive!':'👍 GO!';motor.quiet();}addEventListener('blur',pauseForAway);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseForAway();});document.addEventListener('soundchange',()=>{if(window.SFX?.on&&running)motor.start();else motor.quiet();});
$('#pace').value=pace;$('#pace').onchange=e=>{pace=e.target.value;save();};for(const [name,c] of [['Sky silver','#c3d2df'],['Ocean blue','#245dd5'],['Sunshine yellow','#ecc348'],['Cherry red','#d64c55'],['Mint green','#78c4a9']]){const b=document.createElement('button');b.style.background=c;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String(c===color));b.onclick=()=>{color=c;paint.color.set(c);for(const x of $('#colors').children)x.setAttribute('aria-pressed',String(x===b));save();};$('#colors').append(b);}
function enterBuild(){reset();editing=true;document.body.classList.add('editing');if(!custom)custom=copy(points);active='custom';points=copy(custom);selected=0;history=[];$('#garage').hidden=true;$('#workshop').hidden=false;$('#go').textContent='👍 Drive!';rebuild();save();cameraReady=false;tell('Tap a numbered dot, then choose a track piece below.');$('#workshop').scrollIntoView({behavior:'smooth',block:'start'});}
function leaveBuild(){editing=false;document.body.classList.remove('editing');$('#garage').hidden=false;$('#workshop').hidden=true;custom=copy(points);rebuild();save();reset();$('#game').scrollIntoView({behavior:'smooth'});begin();}
$('#build').onclick=enterBuild;$('#done').onclick=leaveBuild;
function selectPiece(i){selected=(i+points.length)%points.length;$('#piece').value=selected;for(const d of dots.children)if(d.isMesh)d.material=d.userData.index===selected?selectedMat:dotMat;$('#builderMessage').textContent='Piece '+(selected+1)+' selected. Pick a shape below.';}
$('#piece').onchange=e=>selectPiece(Number(e.target.value));$('#previous').onclick=()=>selectPiece(selected-1);$('#next').onclick=()=>selectPiece(selected+1);
const actions=[['straight','━','Straight piece'],['left','↰','Bend left'],['right','↱','Bend right'],['widen','↔','Make it longer'],['hill','⛰️','Add a hill'],['lower','⤵','Lower the hill'],['shrink','↦','Bring it closer'],['remove','↶','Remove piece']];for(const [action,icon,name] of actions){const b=document.createElement('button');b.innerHTML='<b aria-hidden="true">'+icon+'</b>'+name;b.onclick=()=>{const result=editPoints(points,selected,action);if(result.error){$('#builderMessage').textContent=result.error;tell(result.error);window.SFX?.buzz();return;}history.push({points:copy(points),selected});if(history.length>30)history.shift();points=result.points;selected=result.index;custom=copy(points);rebuild();save();window.SFX?.snap();$('#builderMessage').textContent='✓ '+name+' connected! Your track is ready.';tell('Connected! Tap Drive when you are ready.');};$('#pieces').append(b);}
$('#undo').onclick=()=>{const old=history.pop();if(!old)return;points=old.points;selected=old.selected;custom=copy(points);rebuild();save();$('#builderMessage').textContent='Undone. Your loop is still connected.';};
const ray=new T.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>{if(!editing)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(dots.children.filter(d=>d.isMesh))[0];if(hit){selectPiece(hit.object.userData.index);$('#workshop').scrollIntoView({behavior:'smooth'});}});
$('#help').onclick=()=>{pauseForAway();$('#helpSheet').showModal();};$('#closeHelp').onclick=()=>$('#helpSheet').close();
const map=$('#map').getContext('2d');function drawMap(t){map.clearRect(0,0,180,130);const pts=mapPoints,cx=mapBounds.x,cz=mapBounds.z,s=mapBounds.scale;map.beginPath();pts.forEach((p,i)=>map[i?'lineTo':'moveTo'](90+(p.x-cx)*s,65+(p.z-cz)*s));map.strokeStyle='#eef5d7';map.lineWidth=4;map.stroke();const p=curve.getPointAt(t);map.beginPath();map.arc(90+(p.x-cx)*s,65+(p.z-cz)*s,5,0,7);map.fillStyle='#a1ff5b';map.fill();for(const gate of starGates){if(gate.collected)continue;const q=curve.getPointAt(CHECKPOINTS[gate.index]);map.beginPath();map.arc(90+(q.x-cx)*s,65+(q.z-cz)*s,3,0,7);map.fillStyle='#ffdc60';map.fill();}}
let cameraReady=false;function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);
const targetPos=new T.Vector3(),look=new T.Vector3(),up=new T.Vector3(0,1,0);let mapClock=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000||0,.05);last=now;if(document.hidden)return;const t=travel/length%1,p=curve.getPointAt(t),d=curve.getTangentAt(t),future=curve.getTangentAt((t+8/length)%1),turn=d.z*future.x-d.x*future.z,corner=Math.abs(turn);const target=running&&!editing?({gentle:8,cruise:13,zoom:19}[pace])*(1-Math.min(.5,corner*.7)):0;speed+=(target-speed)*(1-Math.exp(-dt*2));if(running&&!editing){const before=travel,previousLap=Math.floor(travel/length);travel+=speed*dt;
 for(const hit of crossedCheckpoints(before,travel,length)){const gate=starGates[hit.index];gate.collected=true;gate.g.visible=false;lapStars=Math.min(5,lapStars+1);updateStars();window.SFX?.ding();tell(lapStars===5?'🌟 All five stars! Bring them to the finish line.':'⭐ Star '+lapStars+' found! Follow the next golden gate.');}
 if(Math.floor(travel/length)>previousLap){laps++;$('#laps').textContent=laps;window.SFX?.fanfare();tell('🏁 Five stars, one happy lap! Explore again whenever you like.');lapStars=0;for(const gate of starGates){gate.collected=false;gate.g.visible=true;}updateStars();}}
 const slide=driftStep({angle:driftAmount,seconds:driftSeconds,awarded:driftAwarded,velocity:driftVelocity},{held:driftHeld,running,turn,steer,dt});const sideways=slide.sliding;driftAmount=slide.angle;driftVelocity=slide.velocity;driftSeconds=slide.seconds;driftAwarded=slide.awarded;if(slide.award){drifts++;$('#drifts').textContent=drifts;window.SFX?.ding();tell('✨ Lovely drift! Let go to straighten up.');}
 lane+=(clamp(-steer*1.2+driftAmount*1.6,-1.5,1.5)-lane)*(1-Math.exp(-dt*3));const normal=new T.Vector3(-d.z,0,d.x).normalize();car.position.copy(p).addScaledVector(normal,lane);car.position.y+=.04;car.rotation.set(-Math.asin(d.y),Math.atan2(d.x,d.z)+driftAmount,0,'YXZ');body.rotation.z=-driftAmount*.06;wheels.forEach(w=>{w.spin.rotation.x+=speed*dt/.43;if(w.front)w.pivot.rotation.y=turn*.3-driftAmount*.65;});
 smokeClock+=dt;if(sideways&&smokeClock>.08&&!reduced){smokeClock=0;for(const x of [-.9,.9]){const q=smoke[smokeIndex++%smoke.length];q.life=1;const loc=car.localToWorld(new T.Vector3(x,.2,-1.5));q.mesh.position.copy(loc);q.mesh.visible=true;}}for(const q of smoke){if(q.life>0){q.life-=dt*.8;q.mesh.position.y+=dt*.55;q.mesh.scale.setScalar(1+(1-q.life)*3);q.mesh.material.opacity=Math.max(0,q.life*.25);q.mesh.visible=q.life>0;}}
 car.visible=!editing;const center=trackCenter;if(editing||view===2){const sx=trackSpan.x,sz=trackSpan.z,dist=Math.max(sz,sx/camera.aspect)/(2*Math.tan(T.MathUtils.degToRad(24)));targetPos.copy(center).add(new T.Vector3(0,dist,dist*.3));look.copy(center);}else if(view===3){const a=reduced?0:now*.00015;targetPos.copy(p).add(new T.Vector3(Math.sin(a)*6.5,2.3,Math.cos(a)*6.5));look.copy(p);look.y+=.65;}else if(view===1){targetPos.copy(p).addScaledVector(d,1.4);targetPos.y+=1.65;look.copy(curve.getPointAt((t+20/length)%1));look.y+=1.4;car.visible=false;}else{targetPos.copy(p).addScaledVector(d,-14);targetPos.y+=7;look.copy(p).addScaledVector(d,1);look.y+=1.2;}
 if(!cameraReady){camera.position.copy(targetPos);cameraReady=true;}else camera.position.lerp(targetPos,1-Math.exp(-dt*5));camera.up.copy(up);camera.lookAt(look);motor.update(speed,sideways,running,now/1000);mapClock+=dt;if(mapClock>.1){drawMap(t);$('#lapProgress').value=t;mapClock=0;}const rect=host.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight)renderer.render(scene,camera);}
rebuild();resize();requestAnimationFrame(frame);
