import * as T from './vendor/three.module.js';
import {mergeVertices} from './vendor/BufferGeometryUtils.js';
import {scannedMaterial,loadLighting} from './realism.js';
import {parkAmbience} from './park-ambience.js?v=expansion2';
const mobile=matchMedia('(max-width: 650px)').matches,$=id=>document.getElementById(id);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.75));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('view').append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#bdd1d2');scene.fog=new T.Fog('#b4c8c6',55,125);const camera=new T.PerspectiveCamera(49,innerWidth/innerHeight,.08,180);
scene.add(new T.HemisphereLight('#e7f3ff','#5d674c',.65));const sun=new T.DirectionalLight('#fff0d6',3.1);sun.position.set(-18,31,19);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:30,bottom:-30,near:1,far:90});sun.shadow.normalBias=.025;scene.add(sun);loadLighting(renderer,scene,'park',()=>{$('loading').remove();});
let seed=3729;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
const stone=scannedMaterial('concrete_pavement',[2,2],'#b7a98d'),sand=scannedMaterial('coast_sand_01',[5,5],'#b6af95'),grass=scannedMaterial('leafy_grass',[14,14],'#8c986d');
const wood=new T.MeshStandardMaterial({color:'#73614a',roughness:.86}),metal=new T.MeshStandardMaterial({color:'#a1b0af',metalness:.85,roughness:.24});
function mesh(geo,mat,x=0,y=0,z=0){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
function box(w,h,d,x,y,z,mat=stone){return mesh(new T.BoxGeometry(w,h,d),mat,x,y,z);}
// The deck is built around an open excavation. Nothing fills the pool volume.
box(100,.5,35,0,-.35,32,grass);box(100,.5,35,0,-.35,-32,grass);box(36,.5,29,-26,-.35,0,grass);box(36,.5,29,26,-.35,0,grass);
box(6,.45,32,-10,-.18,0);box(6,.45,32,10,-.18,0);box(14,.45,3,0,-.18,14.5);box(14,.45,3,0,-.18,-14.5);
const tile=new T.MeshStandardMaterial({color:'#b7d3c4',roughness:.37});tile.onBeforeCompile=s=>{s.uniforms.clock={value:0};tile.userData.shader=s;s.vertexShader='varying vec3 tileP;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\ntileP=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader='varying vec3 tileP;uniform float clock;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
vec2 q=tileP.xz+vec2(tileP.y*.7);vec2 f=abs(fract(q*4.)-.5);float grout=smoothstep(.465,.495,max(f.x,f.y));diffuseColor.rgb*=mix(1.,.67,grout);float a=sin(q.x*5.+sin(q.y*4.+clock*.6));float b=sin(q.y*5.-sin(q.x*3.-clock*.5));float c=pow(max(0.,1.-abs(a+b)*2.5),4.);diffuseColor.rgb+=c*.13;`);};
box(14,.2,26,0,-1.65,0,tile);box(.22,1.7,26,-6.9,-.78,0,tile);box(.22,1.7,26,6.9,-.78,0,tile);box(14,1.7,.22,0,-.78,12.9,tile);box(14,1.7,.22,0,-.78,-12.9,tile);
for(let i=0;i<5;i++)box(5,.24*(5-i),.65,0,-1.53+.12*(5-i),11.9-i*.64,tile);
// Individual coping stones and narrow joints establish a readable human scale.
for(let z=-12.5;z<13;z+=.8)for(const x of [-7,7])box(.65,.16,.77,x,.11,z);
for(let x=-6.4;x<7;x+=.8)for(const z of [-13,13])box(.77,.16,.65,x,.11,z);
const waterMat=new T.MeshPhysicalMaterial({color:'#c9f2ee',roughness:.065,metalness:0,transmission:0,thickness:1.4,ior:1.333,attenuationColor:'#369da5',attenuationDistance:7,envMapIntensity:1.4,side:T.DoubleSide});
const refraction=new T.WebGLRenderTarget(Math.round(innerWidth*.65),Math.round(innerHeight*.65));refraction.depthTexture=new T.DepthTexture(refraction.width,refraction.height);const screenSize=new T.Vector2();renderer.getDrawingBufferSize(screenSize);const clipUnderwater=new T.Plane(new T.Vector3(0,-1,0),-.115);
waterMat.onBeforeCompile=s=>{s.uniforms.poolRefraction={value:refraction.texture};s.uniforms.poolDepth={value:refraction.depthTexture};s.uniforms.poolScreen={value:screenSize};s.uniforms.clock={value:0};waterMat.userData.shader=s;s.vertexShader='varying vec3 waterP;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nwaterP=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader='varying vec3 waterP;uniform float clock;uniform sampler2D poolRefraction;uniform sampler2D poolDepth;uniform vec2 poolScreen;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_begin>',`#include <normal_fragment_begin>
vec2 p=waterP.xz;vec2 slope=vec2(cos(p.x*3.1+p.y*1.3+clock*.85)*.027+cos(p.x*8.1-p.y*3.-clock*1.5)*.012,cos(p.y*3.7-p.x*.8-clock*.7)*.024+sin(p.y*9.+p.x*2.+clock)*.009);normal=normalize(mat3(viewMatrix)*vec3(-slope.x,1.,-slope.y));`);s.fragmentShader=s.fragmentShader.replace('#include <opaque_fragment>',`vec2 poolUV=gl_FragCoord.xy/poolScreen+slope*.075;float dep=texture2D(poolDepth,poolUV).x;float floorDistance=(.08*180.)/(180.-dep*(180.-.08));float path=max(0.,floorDistance-vViewPosition.z)*length(vViewPosition)/max(.01,vViewPosition.z);vec3 absorb=exp(-vec3(.24,.055,.035)*min(path,8.));vec3 beneath=texture2D(poolRefraction,poolUV).rgb*absorb+vec3(.02,.17,.18)*(1.-absorb);float fresnel=.0204+.9796*pow(1.-max(0.,dot(normal,normalize(vViewPosition))),5.);outgoingLight=beneath*(1.-fresnel)+reflectedLight.directSpecular+reflectedLight.indirectSpecular;
#include <opaque_fragment>`);};
const water=mesh(new T.PlaneGeometry(13.6,25.6,1,1).rotateX(-Math.PI/2),waterMat,0,-.12,0);water.castShadow=false;
// Weathered rock mass has a traversable vaulted interior rather than a solid mound.
const rockMat=scannedMaterial('rock_face',[1,1],'#c6c1b5');
function rock(x,y,z,sx,sy,sz){let geo=new T.IcosahedronGeometry(1,5);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const a=p.getX(i),b=p.getY(i),c=p.getZ(i),n=1+.09*Math.sin(a*9+b*7)*Math.cos(c*8)+.045*Math.sin(b*23+c*12);p.setXYZ(i,a*n,b*n,c*n);}geo.deleteAttribute('normal');geo=mergeVertices(geo);geo.computeVertexNormals();const r=mesh(geo,rockMat,x,y,z);r.scale.set(sx,sy,sz);r.rotation.set(rand()*.25,rand()*6,rand()*.2);return r;}
for(let z=-12;z<-4;z+=1.75)for(let i=0;i<=8;i++){const a=i/8*Math.PI;rock(Math.cos(a)*5,Math.sin(a)*3.8+.2,z,1.25+rand()*.5,.9+rand()*.45,1.4);}
for(let i=0;i<30;i++){const side=i%2?1:-1;rock(side*(7.6+rand()*3),.25+rand()*.35,-13+rand()*13,1+rand(),.5+rand()*.9,.8+rand());}
for(const z of [-10,-6]){const lamp=new T.PointLight('#ffe0a2',14,7,2);lamp.position.set(4.1,.9,z);scene.add(lamp);mesh(new T.SphereGeometry(.07,12,8),new T.MeshBasicMaterial({color:'#ffe1a3'}),4.1,.9,z);}
// Fine leaf silhouettes, varied branches, and dense low planting soften the rock boundary.
const leafGeo=new T.SphereGeometry(1,8,4),leafMat=new T.MeshStandardMaterial({color:'#496743',roughness:.92});const leaves=new T.InstancedMesh(leafGeo,leafMat,6200);leaves.castShadow=true;leaves.receiveShadow=true;scene.add(leaves);let li=0;const dummy=new T.Object3D();
function leaf(x,y,z,s=.2){dummy.position.set(x,y,z);dummy.scale.set(s,s*.06,s*.38);dummy.rotation.set(rand()*3,rand()*6,rand()*3);dummy.updateMatrix();leaves.setMatrixAt(li,dummy.matrix);leaves.setColorAt(li,new T.Color().setHSL(.22+rand()*.1,.22+rand()*.2,.17+rand()*.17));li++;}
function branch(a,b,r){const v=b.clone().sub(a),m=mesh(new T.CylinderGeometry(r*.35,r,v.length(),7),wood);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());}
for(let i=0;i<16;i++){const x=(i%2?1:-1)*(12+rand()*7),z=-19+rand()*38,h=3+rand()*4;branch(new T.Vector3(x,0,z),new T.Vector3(x,h,z),.14);for(let k=0;k<8;k++){const a=k*2.4,r=1+rand(),end=new T.Vector3(x+Math.cos(a)*r,h+rand()*1.2,z+Math.sin(a)*r);branch(new T.Vector3(x,h*.7,z),end,.045);for(let j=0;j<42;j++){const aa=rand()*Math.PI*2,rr=Math.sqrt(rand())*.9;leaf(end.x+Math.cos(aa)*rr,end.y+rand()*.65,end.z+Math.sin(aa)*rr,.12+rand()*.14);}}}
for(let i=li;i<6200;i++){const x=(i%2?1:-1)*(7.6+rand()*4),z=-15+rand()*29;leaf(x,.2+rand()*.55,z,.13+rand()*.1);}leaves.instanceMatrix.needsUpdate=true;
// Pool house, open pergola, and restrained furniture frame the south terrace.
box(8,3.5,4,-9,1.65,19,new T.MeshStandardMaterial({color:'#d6cebb',roughness:.95}));box(8.7,.22,4.8,-9,3.5,19,wood);for(const x of [-11,-8])box(1.9,2.6,.08,x,1.3,16.95,new T.MeshPhysicalMaterial({color:'#314e49',roughness:.14,metalness:.3}));
for(const x of [4,11])for(const z of [14.6,20])box(.19,3.3,.19,x,1.55,z,wood);for(let x=3.5;x<12;x+=.42)box(.12,.2,6.3,x,3.2,17.4,wood);
const fabric=new T.MeshStandardMaterial({color:'#d7d4bd',roughness:1});for(const x of [-10,10])for(const z of [2,6,10]){box(.85,.13,2,x,.4,z,fabric);const back=box(.85,.13,.9,x,.7,z-.9,fabric);back.rotation.x=.55;for(const dz of [-.6,.6])box(.65,.4,.07,x,.15,z+dz,wood);}
// A smooth flume curves down from a platform and empties above the real pool.
const slidePath=new T.CatmullRomCurve3([new T.Vector3(11,5,-3),new T.Vector3(9,4.7,0),new T.Vector3(10,3,4),new T.Vector3(7,1.7,6),new T.Vector3(4,.15,5)]);
const pos=[],uv=[],idx=[];for(let i=0;i<=100;i++){const t=i/100,p=slidePath.getPoint(t),v=slidePath.getTangent(t),n=new T.Vector3(v.z,0,-v.x).normalize();for(let j=0;j<=20;j++){const a=j/20*Math.PI,q=p.clone().addScaledVector(n,Math.cos(a)*.62);q.y+=.62-Math.sin(a)*.62;pos.push(q.x,q.y,q.z);uv.push(t*12,j/20);if(i<100&&j<20){const k=i*21+j;idx.push(k,k+21,k+1,k+1,k+21,k+22);}}}const flume=new T.BufferGeometry();flume.setAttribute('position',new T.Float32BufferAttribute(pos,3));flume.setAttribute('uv',new T.Float32BufferAttribute(uv,2));flume.setIndex(idx);flume.computeVertexNormals();mesh(flume,new T.MeshPhysicalMaterial({color:'#759f95',roughness:.24,clearcoat:1,side:T.DoubleSide}));box(2,.22,2,11,4.9,-3,wood);for(const t of [0,.3,.6]){const p=slidePath.getPoint(t);mesh(new T.CylinderGeometry(.09,.12,p.y,12),metal,p.x,p.y/2,p.z);}for(let i=0;i<16;i++)box(1,.12,.33,12,.3+i*.3,-3-i*.26,stone);
const ring=mesh(new T.TorusGeometry(.48,.14,16,48),new T.MeshPhysicalMaterial({color:'#e2c381',roughness:.35,clearcoat:.7}),1,.02,3);ring.rotation.x=Math.PI/2;
let mode='overview',yaw=.62,pitch=.73,distance=43,focus=new T.Vector3(0,0,-1),elapsed=0,start=0;
function choose(m){mode=m;start=elapsed;for(const id of ['overview','edge','float','slide'])$(id).setAttribute('aria-pressed',String(id===m));if(m==='overview'){focus.set(0,0,-1);distance=43;pitch=.73;yaw=.62;}if(m==='edge'){focus.set(0,-.1,-5);distance=12;pitch=.09;yaw=.2;}$('status').textContent=m==='float'?'Floating beneath the grotto. Choose a view to step out.':m==='slide'?'Down the flume and into the pool.':'Drag to look around. Scroll or pinch to move closer.';}
for(const m of ['overview','edge','float','slide'])$(m).onclick=()=>choose(m);
const pointers=new Map();let pinch=0;renderer.domElement.onpointerdown=e=>{renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);};renderer.domElement.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);if(pointers.size===1){yaw-=(e.clientX-old[0])*.006;pitch=T.MathUtils.clamp(pitch+(e.clientY-old[1])*.005,.035,1.4);}pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(pinch)distance=T.MathUtils.clamp(distance*pinch/d,3,65);pinch=d;}};for(const evt of ['onpointerup','onpointercancel'])renderer.domElement[evt]=e=>{pointers.delete(e.pointerId);pinch=0;};renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=T.MathUtils.clamp(distance*Math.exp(e.deltaY*.001),3,65);},{passive:false});
window.SFX?.bind($('parkSound'));$('parkSound').setAttribute('aria-label','Toggle park sound');window.SFX?.ambience('water');parkAmbience();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.getDrawingBufferSize(screenSize);refraction.setSize(Math.round(innerWidth*.65),Math.round(innerHeight*.65));});
let previous=0;function animate(ms){requestAnimationFrame(animate);const dt=Math.min((ms-previous)/1000,.05);previous=ms;if(document.hidden)return;elapsed+=dt;for(const mat of [tile,waterMat])if(mat.userData.shader)mat.userData.shader.uniforms.clock.value=elapsed;ring.position.y=.03+Math.sin(elapsed*1.2)*.025;
if(mode==='float'){const t=((elapsed-start)*.045)%1,z=6-t*17;camera.position.set(Math.sin(t*4)*.8,.38,z);camera.lookAt(0,.5,z-4);ring.position.set(camera.position.x,-.02,z-.3);}else if(mode==='slide'){const t=Math.min((elapsed-start)/7,1);camera.position.copy(slidePath.getPoint(t)).add(new T.Vector3(0,.48,0));camera.lookAt(slidePath.getPoint(Math.min(t+.07,1)).add(new T.Vector3(-.05,.1,-.1)));if(t===1)choose('float');}else{camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance).add(focus);camera.lookAt(focus);}const bg=scene.background;water.visible=false;scene.background=new T.Color('#2e8487');renderer.clippingPlanes=[clipUnderwater];renderer.setRenderTarget(refraction);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.clippingPlanes=[];scene.background=bg;water.visible=true;renderer.render(scene,camera);}
requestAnimationFrame(animate);
