import * as T from './vendor/three.module.js';
import {makeModel,mesh,block,orb} from './chilltopia-models.js?v=estates4';
import {attraction,animateAttraction} from './park-attractions.js?v=estates4';
import {makeCar} from './driving-car.js?v=handling3';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,canvases=[...document.querySelectorAll('[data-world],#heroWorld')];let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true});}catch{for(const c of canvases){const ctx=c.getContext('2d');ctx.font='90px sans-serif';ctx.fillText(c.dataset.world==='drive'?'🏎️':'🐠',70,130);}}
if(renderer){renderer.setPixelRatio(1);renderer.setSize(680,500);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
function make(kind){const scene=new T.Scene(),group=new T.Group();scene.add(group);scene.add(new T.HemisphereLight('#fffbed','#629e9e',3));const sun=new T.DirectionalLight('#fff4da',4);sun.position.set(-5,10,8);scene.add(sun);const camera=new T.PerspectiveCamera(36,680/500,.1,100);camera.position.set(6,5,8);camera.lookAt(0,.8,0);let animals=[],animated=[];
if(kind==='reef'||kind==='hero'){mesh(group,new T.CylinderGeometry(3.3,3,1,64),'#c1b995',0,-.5,0);mesh(group,new T.CylinderGeometry(3.1,3.1,.09,64),'#b8dccd',0,.04,0);for(const [id,x,z,s] of [['reefarch',0,-.8,1.1],['coralgarden',-1.5,.6,1],['grass',1.9,-.5,1],['pineapplehome',1.3,1,1]]){const o=makeModel(id);o.position.set(x,0,z);o.scale.setScalar(s);group.add(o);}for(let i=0;i<5;i++){const f=makeModel(i%2?'tang':'clown');f.scale.setScalar(.8);group.add(f);animals.push(f);}camera.position.set(7,6,10);camera.lookAt(0,.9,0);}
if(kind==='park'){mesh(group,new T.CylinderGeometry(4,3.8,.5,64),'#dce1b7',0,-.25,0);const pool=attraction('pool');pool.scale.setScalar(.6);pool.position.set(1,0,1);group.add(pool);const tower=attraction('bucket');tower.scale.setScalar(.6);tower.position.set(-1,0,-.5);group.add(tower);animated.push(tower,pool);const palm=attraction('palm');palm.scale.setScalar(.55);palm.position.set(2,0,-1.8);group.add(palm);camera.position.set(8,6,10);camera.lookAt(0,1.2,0);}
if(kind==='drive'){mesh(group,new T.CylinderGeometry(3.5,3.3,.4,64),'#626e79',0,-.24,0);const car=makeCar().car;car.rotation.y=-.4;group.add(car);camera.position.set(5,2.9,6.7);camera.lookAt(0,.7,0);}
if(kind==='blocks'){mesh(group,new T.CylinderGeometry(3,2.9,.4,64),'#aba4c0',0,-.25,0);for(let y=0;y<4;y++)for(let x=0;x<3;x++){block(group,['#e9ba61','#81b9b6','#b399d3','#e69588'][(x+y)%4],x-1,y*.55+.25,0,.95,.5,1.5);for(const z of [-.45,0,.45])mesh(group,new T.CylinderGeometry(.14,.14,.09,12),'#f4e6ad',x-1,y*.55+.54,z);}camera.position.set(6,4,7);camera.lookAt(0,.8,0);}
if(kind==='town'){mesh(group,new T.CylinderGeometry(3.4,3.2,.4,48),'#a9c296',0,-.25,0);const cottage=makeModel('townhouse');cottage.position.set(0,0,-.3);group.add(cottage);for(const x of [-2,2]){const tree=makeModel('tree');tree.position.set(x,0,-1);tree.scale.setScalar(.8);group.add(tree);}block(group,'#e7d6b0',0,.02,1.5,5,.08,.65);camera.position.set(7,5,9);camera.lookAt(0,1,0);}
if(kind==='seafood'){mesh(group,new T.CylinderGeometry(3,2.8,.5,64),'#a9cebd',0,-.25,0);const a=makeModel('lobster');a.scale.setScalar(1.8);group.add(a);const b=makeModel('redcrab');b.position.set(-1.2,0,1.2);b.scale.setScalar(1.5);group.add(b);const c=makeModel('reefledge');c.position.set(0,0,-1.5);group.add(c);camera.position.set(5,5,7);camera.lookAt(0,.5,0);}
return{scene,group,camera,animals,animated};}
const views=canvases.map(canvas=>({...make(canvas.dataset.world||'hero'),canvas,ctx:canvas.getContext('2d'),visible:false}));const observer=new IntersectionObserver(entries=>{for(const entry of entries){const v=views.find(v=>v.canvas===entry.target);v.visible=entry.isIntersecting;}},{rootMargin:'100px'});views.forEach(v=>{v.canvas.width=680;v.canvas.height=500;observer.observe(v.canvas);});let last=0;function frame(now){requestAnimationFrame(frame);if(document.hidden||now-last<100)return;last=now;for(const v of views){if(!v.visible)continue;const t=reduced?1:now/1000;v.group.rotation.y=Math.sin(t*.18)*.12;v.animals.forEach((f,i)=>{const a=t*.25+i*1.4;f.position.set(Math.cos(a)*2,1.15+Math.sin(a+i)*.25,Math.sin(a)*1.6);f.rotation.y=-a-Math.PI/2;});for(const a of v.animated)animateAttraction(a,t);renderer.render(v.scene,v.camera);v.ctx.clearRect(0,0,680,500);v.ctx.drawImage(renderer.domElement,0,0);}}requestAnimationFrame(frame);}
const stage=document.querySelector('#piggyStage'),demo=stage?.querySelector('.home-save-guide');function guide(){const coin=stage?.querySelector('.dbill,.dcoin'),pig=stage?.querySelector('.piggy-svg');if(!coin||!pig||!demo)return;const a=stage.getBoundingClientRect(),b=coin.getBoundingClientRect(),p=pig.getBoundingClientRect();demo.style.left=b.left-a.left+b.width/2+'px';demo.style.top=b.top-a.top+'px';demo.style.setProperty('--dx',p.left+p.width*.45-b.left-b.width/2+'px');demo.style.setProperty('--dy',p.top+p.height*.24-b.top+'px');demo.querySelector('span').textContent=coin.textContent.replace(/[^0-9]/g,'')||'1';}if(stage){stage.style.position='relative';new ResizeObserver(guide).observe(stage);new MutationObserver(guide).observe(document.querySelector('#billTray'),{childList:true});document.addEventListener('piggy-saved',()=>{stage.classList.remove('just-saved');void stage.offsetWidth;stage.classList.add('just-saved');setTimeout(()=>stage.classList.remove('just-saved'),1000);});guide();}
