import {pinballAudio} from './pinball-audio.js';
import {W,H,R,BUMPERS,WALLS,newGame,launch,step,TARGETS,nudge} from './pinball-physics.js?v=3';
const $=s=>document.querySelector(s),canvas=$('#board'),ctx=canvas.getContext('2d'),SFX=window.SFX,input={left:false,right:false},reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const audio=pinballAudio(SFX),art=new Image();art.src='assets/pinball/playfield.jpg';let spinnerAngle=0,spinnerSpeed=0,callout='',calloutTime=0;
let game=newGame(),paused=false,last=0,accumulator=0,particles=[],flashes=[0,0,0],trail=[],best=0;
try{best=Number(localStorage.getItem('cb:pinball:best:v2'))||0;}catch{}
SFX.bind($('#sound'));$('#best').textContent=best.toLocaleString();
function message(text){$('#message').textContent=text;}
function saveBest(){if(game.score>best){best=game.score;$('#best').textContent=best.toLocaleString();try{localStorage.setItem('cb:pinball:best:v2',String(best));}catch{}}}
function paintScore(){$('#score').textContent=game.score.toLocaleString();$('#balls').textContent=game.little?'∞':game.balls;$('#ballLabel').textContent=game.little?'PLAY':'BALLS';}
function release(){input.left=input.right=false;for(const id of ['left','right'])$('#'+id).classList.remove('held');}
function reset(little){saveBest();game=newGame(little);particles=[];trail=[];spinnerAngle=spinnerSpeed=calloutTime=0;callout='';flashes=[0,0,0];release();paused=false;$('#pause').textContent='Pause';$('#pause').setAttribute('aria-pressed','false');$('#little').setAttribute('aria-pressed',little);$('#arcade').setAttribute('aria-pressed',!little);$('#modeHelp').textContent=little?'Flippers help you, and the ball always comes back. Tap Launch to play!':'Three balls. Seven seconds of ball save after launch. How high can you score?';$('#startCard').hidden=false;$('#startCard h2').textContent='Ready to roll?';$('#start').textContent='Launch ball ↗';paintScore();message('A whole pocketful of fun.');}
function start(){SFX.unlock();if(game.over)reset(game.little);if(paused)togglePause();if(launch(game)){$('#startCard').hidden=true;message('Hit the golden coins!');}}
function togglePause(){paused=!paused;release();$('#pause').textContent=paused?'Resume':'Pause';$('#pause').setAttribute('aria-pressed',paused);message(paused?'Taking a little break.':'Back to the fun!');}
$('#nudge').onclick=()=>{if(!paused)nudge(game);};$('#start').onclick=start;$('#launch').onclick=start;$('#pause').onclick=togglePause;$('#little').onclick=()=>reset(true);$('#arcade').onclick=()=>reset(false);
for(const side of ['left','right']){const button=$('#'+side),ids=new Set();button.onpointerdown=e=>{e.preventDefault();ids.add(e.pointerId);button.setPointerCapture(e.pointerId);if(!input[side])audio.flipper();input[side]=true;button.classList.add('held');};const end=e=>{ids.delete(e.pointerId);if(!ids.size){input[side]=false;button.classList.remove('held');}};button.onpointerup=end;button.onpointercancel=end;button.onlostpointercapture=end;}
window.addEventListener('keydown',e=>{if(['BUTTON','A','INPUT'].includes(e.target.tagName)&&e.key===' ')return;const side=e.key==='ArrowLeft'?'left':e.key==='ArrowRight'?'right':null;if(side){e.preventDefault();if(!input[side])audio.flipper();input[side]=true;$('#'+side).classList.add('held');}if(e.code==='Space'){e.preventDefault();if(!e.repeat)start();}if(e.key==='ArrowUp'){e.preventDefault();if(!paused)nudge(game);}if(e.key==='p'&&!e.repeat)togglePause();});
window.addEventListener('keyup',e=>{const side=e.key==='ArrowLeft'?'left':e.key==='ArrowRight'?'right':null;if(side){input[side]=false;$('#'+side).classList.remove('held');}});window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();last=0;accumulator=0;if(document.hidden&&!paused)togglePause();});
function events(){for(const e of game.events){
 if(['target','spinner','gold','bonus'].includes(e.type)){if(e.type==='spinner'){spinnerSpeed=24;audio.spinner();}else if(e.type==='target')audio.target();else audio.jackpot();if(e.type!=='spinner'){callout=e.type==='gold'?'GOLD RUSH · 3×':e.type==='bonus'?'PIGGY JACKPOT!':'+'+e.points;calloutTime=1.6;}}
 if(e.type==='gold')message('Gold Rush! Triple points for 20 seconds!');if(e.type==='sling')audio.bumper(e.index);if(e.type==='nudge')audio.nudge();
 if(e.type==='bumper'){flashes[e.index]=1;audio.bumper(e.index);if(!reduced)for(let i=0;i<12;i++){const a=i/12*Math.PI*2;particles.push({x:e.x,y:e.y,vx:Math.cos(a)*110,vy:Math.sin(a)*110,life:1});}}if(e.type==='launch')audio.launch();if(e.type==='bonus'){message('PIGGY BONUS! '+e.points.toLocaleString()+' points!');}if(e.type==='save'){audio.save();}if(e.type==='save')message('Ball saved! Here it comes again!');if(e.type==='unstick')message('A little nudge. Keep rolling!');if(e.type==='drain')message('Nice playing! Tap Launch for the next ball.');if(e.type==='over'){$('#startCard').hidden=false;$('#startCard h2').textContent='Lovely playing!';$('#start').textContent='Play again ↗';message('Final score: '+game.score.toLocaleString()+'. Try another round!');audio.jackpot();}}if(game.events.length){paintScore();saveBest();}game.events.length=0;}
function circle(x,y,r,fill,stroke,line=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=line;ctx.stroke();}}
function line(x1,y1,x2,y2,color,width){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineWidth=width;ctx.strokeStyle=color;ctx.lineCap='round';ctx.stroke();}
function text(t,x,y,size,color='#f9df92'){ctx.fillStyle=color;ctx.font=`900 ${size}px 'Trebuchet MS',sans-serif`;ctx.textAlign='center';ctx.fillText(t,x,y);}
function draw(dt){
 const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#236668');bg.addColorStop(.5,'#12464d');bg.addColorStop(1,'#092e3b');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);if(art.complete&&art.naturalWidth){ctx.drawImage(art,0,0,W,H);ctx.fillStyle='#07333766';ctx.fillRect(0,0,W,H);}
 // Etched sunburst and brass perimeter give the table a physical cabinet finish.
 ctx.save();ctx.globalAlpha=.13;for(let i=0;i<24;i++){const a=i*Math.PI/12;line(205,310,205+Math.cos(a)*640,310+Math.sin(a)*640,'#b8dfba',1);}ctx.restore();
 for(const wall of WALLS){line(...wall,'#061e29',14);line(wall[0],wall[1]-2,wall[2],wall[3]-2,'#af9863',9);line(wall[0],wall[1]-4,wall[2],wall[3]-4,'#ffe3a0',2);}
 text('CHILLION BUCKS',207,88,20);text('PIGGY POP',207,111,11,'#b5d5bd');
 // Ten bulbs fill toward the piggy bonus.
 for(let i=0;i<10;i++){const a=Math.PI+(i/9)*Math.PI;circle(205+Math.cos(a)*102,175+Math.sin(a)*39,4.5,i<game.hits%10?'#fff0a8':'#31595a',i<game.hits%10?'#ffe797':'#527a71',2);}
 for(let i=0;i<BUMPERS.length;i++){const p=BUMPERS[i];flashes[i]=Math.max(0,flashes[i]-dt*3);circle(p.x+2,p.y+8,p.r+5,'#001e2b88');circle(p.x,p.y,p.r+6,'#779f91','#bce5bc',2);const fill=ctx.createRadialGradient(p.x-10,p.y-12,1,p.x,p.y,p.r);fill.addColorStop(0,flashes[i]?'#fffddd':'#fff2aa');fill.addColorStop(.6,'#e5bd5e');fill.addColorStop(1,'#987033');circle(p.x,p.y,p.r,fill,'#ffde87',3);circle(p.x,p.y,p.r-7,'#e6b958','#fff0a6',1.5);text('c',p.x,p.y+12,38,'#8f6a2e');text('100',p.x,p.y+p.r+23,10,'#b9d7c5');if(flashes[i]&&!reduced){ctx.save();ctx.globalAlpha=flashes[i];circle(p.x,p.y,p.r+12+(1-flashes[i])*16,'transparent','#ffec9b',2);ctx.restore();}}
 // Lit target banks, a physical spinner, and an illuminated mission panel.
 for(let i=0;i<TARGETS.length;i++){const p=TARGETS[i],lit=game.targets[i];circle(p.x+2,p.y+4,14,'#031d28');circle(p.x,p.y,12,lit?'#fff0a0':'#d27898',lit?'#ffe090':'#f5bad0',3);text(lit?'★':'●',p.x,p.y+4,11,lit?'#96702f':'#813b62');}
 spinnerAngle+=spinnerSpeed*dt;spinnerSpeed*=Math.exp(-dt*1.8);line(167,145,243,145,'#c5d5c5',3);ctx.save();ctx.translate(205,145);ctx.scale(1,Math.max(.14,Math.abs(Math.cos(spinnerAngle))));ctx.fillStyle='#e7bc67';ctx.fillRect(-22,-12,44,24);text('SPIN',0,4,10,'#624b2f');ctx.restore();
 ctx.fillStyle='#072f39d9';ctx.beginPath();ctx.roundRect(116,477,178,68,12);ctx.fill();text(game.gold>0?'GOLD RUSH 3×':game.combo>1?game.combo+'× COMBO':'LIGHT ALL SIX',205,503,16);text(game.gold>0?Math.ceil(game.gold)+' SECONDS':game.targets.filter(Boolean).length+' / 6 TARGETS',205,526,11,'#c5dfc9');
 if(calloutTime>0){calloutTime-=dt;ctx.fillStyle='#123b3dea';ctx.beginPath();ctx.roundRect(78,382,254,49,12);ctx.fill();text(callout,205,413,19,'#fff0a1');}
 for(const side of [0,1]){const x=side?308:112,a=game.flips[side],ex=x+Math.cos(a)*83,ey=636+Math.sin(a)*83;line(x,642,ex,ey+6,'#00192699',22);line(x,636,ex,ey,'#a67537',18);line(x,633,ex,ey-3,'#f5d982',12);circle(x,635,7,'#ecf2dc','#778b75',2);}
 for(let i=0;i<3;i++){text('⌃',205,557+i*18,18,'#739d85');}
 text(game.little?'HAPPY RETURNS':game.saveTime>0?'BALL SAVE ON':'KEEP IT ROLLING',205,704,10,'#a8c9b0');line(384,724,384,702,'#edc773',6);
 const b=game.ball;if(!reduced){trail.push({x:b.x,y:b.y});if(trail.length>10)trail.shift();trail.forEach((p,i)=>circle(p.x,p.y,R*i/15,`rgba(223,236,219,${i/70})`));}
 circle(b.x+3,b.y+7,R,'#001b2780');const metal=ctx.createRadialGradient(b.x-3,b.y-4,1,b.x,b.y,R);metal.addColorStop(0,'#ffffff');metal.addColorStop(.28,'#ecf5f1');metal.addColorStop(.55,'#95b2bc');metal.addColorStop(.8,'#405d70');metal.addColorStop(1,'#d9e6de');circle(b.x,b.y,R,metal,'#c8dbd6',.7);
 for(const p of particles){p.life-=dt*2;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;ctx.globalAlpha=Math.max(0,p.life);circle(p.x,p.y,3,'#ffe89e');}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);
}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}resize();window.addEventListener('resize',resize);
function frame(now){const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(!paused&&!document.hidden){accumulator+=dt;while(accumulator>=1/120){step(game,1/120,input);accumulator-=1/120;}events();}draw(paused?0:dt);requestAnimationFrame(frame);}paintScore();requestAnimationFrame(frame);
