import * as T from './vendor/three.module.js';
import {townBlueprint,hasBlueprint} from './town-models.js?v=homes4';
export {hasBlueprint};
export function createPropertyBuilder({host,scene,camera,canvas,onProgress,onView,onClose,thumbnail,reduced=false}){
 const panel=document.createElement('section');panel.className='property-rulebook';panel.hidden=true;panel.setAttribute('aria-label','Property building rulebook');
 panel.innerHTML='<div class="rulebook-top"><strong>MY BUILDING BOOK</strong><button class="book-close" aria-label="Save and close building book">✕</button></div><h2></h2><p class="book-instruction" role="status" aria-live="polite"></p><progress max="1" value="0" aria-label="Property construction progress"></progress><div class="book-piece-row"><button class="book-piece" aria-label="Drag the next building piece"><img alt=""><span></span></button><span class="book-arrow" aria-hidden="true">➜</span><span class="book-example">Match the<br>glowing shape</span></div><button class="book-snap">Snap highlighted piece</button><details><summary>See the whole rulebook</summary><ol class="book-steps"></ol></details>';
 const target=document.createElement('button');target.className='property-drop-target';target.hidden=true;target.setAttribute('aria-label','Place piece on highlighted spot');target.textContent='＋';host.append(panel,target);
 const drag=document.createElement('img');drag.className='property-drag-piece';drag.hidden=true;drag.alt='';document.body.append(drag);
 const ghostMaterial=new T.MeshBasicMaterial({color:'#b4f365',transparent:true,opacity:.27,depthWrite:false,side:T.DoubleSide}),ghost=new T.Group();scene.add(ghost);
 let current=null,parts=[],step=0,held=false,motion=null,lastFrame=0,selectedPiece=false;
 const pieceButton=panel.querySelector('.book-piece'),snapButton=panel.querySelector('.book-snap'),instruction=panel.querySelector('.book-instruction');
 function disposeGhost(){ghost.clear();}
 function paint(){pieceButton.disabled=!!motion;snapButton.disabled=!!motion;target.disabled=!!motion;disposeGhost();const complete=step>=parts.length;panel.querySelector('progress').max=parts.length;panel.querySelector('progress').value=step;pieceButton.hidden=complete;snapButton.hidden=complete;panel.querySelector('.book-arrow').hidden=complete;panel.querySelector('.book-example').hidden=complete;target.hidden=complete;panel.querySelector('.book-steps').replaceChildren();parts.forEach((p,i)=>{const li=document.createElement('li');li.textContent=(i<step?'✓ ':i===step?'→ ':'')+p.name;li.classList.toggle('current',i===step);panel.querySelector('.book-steps').append(li);});
  if(complete){instruction.textContent='You built it! Your property is ready to explore.';return;}
  const part=parts[step];instruction.textContent='Step '+(step+1)+' of '+parts.length+'. Drag this piece onto the glowing spot.';pieceButton.querySelector('span').textContent=part.name;const preview=thumbnail(part.model,part.id+current.kind);pieceButton.querySelector('img').src=preview;drag.src=preview;
  const m=part.model.clone();m.traverse(o=>{if(o.isMesh){o.material=ghostMaterial;o.castShadow=false;o.receiveShadow=false;}});ghost.add(m);ghost.position.set(current.x,current.y,current.z);ghost.rotation.y=current.rot;ghost.scale.setScalar(current.s);ghost.updateMatrixWorld(true);target.setAttribute('aria-label','Place '+part.name+' on highlighted spot');selectedPiece=false;target.classList.remove('ready');
 }
 function start(item,name){close(false);current=item;parts=townBlueprint(item.kind);if(!parts)return;step=Number.isFinite(item.constructionStep)?Math.min(parts.length,Math.max(0,Math.floor(item.constructionStep))):0;current.constructionStep=step;onProgress(current,step);panel.querySelector('h2').textContent=name;panel.hidden=false;host.classList.add('building-property');onView(item);paint();}
 function snap(){if(!current||step>=parts.length||motion)return;const item=current,part=parts[step];disposeGhost();step++;item.constructionStep=step;const root=onProgress(item,step);const added=root.children.at(-1);if(added&&!reduced){added.position.y=.7;motion={node:added,left:.28};}window.SFX?.snap?.();paint();}
 function close(notify=true){held=false;drag.hidden=true;if(motion){motion.node.position.y=0;motion=null;}current=null;parts=[];panel.hidden=true;target.hidden=true;disposeGhost();host.classList.remove('building-property');if(notify)onClose();}
 pieceButton.onpointerdown=e=>{if(!current||step>=parts.length)return;e.preventDefault();held=true;selectedPiece=true;target.classList.add('ready');pieceButton.setPointerCapture(e.pointerId);drag.hidden=false;drag.style.left=e.clientX+'px';drag.style.top=e.clientY+'px';};
 pieceButton.onpointermove=e=>{if(!held)return;drag.style.left=e.clientX+'px';drag.style.top=e.clientY+'px';const r=target.getBoundingClientRect();target.classList.toggle('over',e.clientX>=r.left-35&&e.clientX<=r.right+35&&e.clientY>=r.top-35&&e.clientY<=r.bottom+35);};
 pieceButton.onpointerup=e=>{if(!held)return;held=false;drag.hidden=true;const r=target.getBoundingClientRect();target.classList.remove('over');if(e.clientX>=r.left-35&&e.clientX<=r.right+35&&e.clientY>=r.top-35&&e.clientY<=r.bottom+35)snap();else instruction.textContent='Bring the piece to the glowing +. Or tap the + to snap it.';};
 pieceButton.onpointercancel=()=>{held=false;drag.hidden=true;target.classList.remove('over');};pieceButton.onclick=()=>{selectedPiece=true;target.classList.add('ready');};
 target.onclick=snap;snapButton.onclick=snap;panel.querySelector('.book-close').onclick=()=>close();
 function update(now){const dt=Math.min(.05,(now-lastFrame)/1000||0);lastFrame=now;if(motion){motion.left-=dt;motion.node.position.y=Math.max(0,.7*(motion.left/.28)**2);if(motion.left<=0){motion.node.position.y=0;motion=null;pieceButton.disabled=false;snapButton.disabled=false;target.disabled=false;}}
  if(!current||step>=parts.length)return;ghostMaterial.opacity=reduced?.3:.22+Math.sin(now*.003)*.07;const p=ghost.localToWorld(parts[step].center.clone());p.project(camera);const rect=canvas.getBoundingClientRect(),base=host.getBoundingClientRect();target.style.left=(rect.left-base.left+(p.x+1)*rect.width/2)+'px';target.style.top=(rect.top-base.top+(1-p.y)*rect.height/2)+'px';target.hidden=p.z>1||p.z< -1;}
 return {start,close,update,get active(){return !!current;},get item(){return current;}};
}
