import * as T from './vendor/three.module.js';
import {constructionFootprint,projectConstructionFootprint,acceptsConstructionDrop} from './property-drop-area.js?v=drop2';
import {isBuildableCar} from './town-cars.js?v=garage2';
import {townBlueprint,hasBlueprint,supportsHomeLesson,ESTATE_STYLES} from './town-models.js?v=garage2';
export {hasBlueprint};
export function createPropertyBuilder({host,scene,camera,canvas,onProgress,onView,onClose,thumbnail,reduced=false}){
 const panel=document.createElement('section');panel.className='property-rulebook';panel.hidden=true;panel.setAttribute('aria-label','Property building rulebook');
 panel.innerHTML='<div class="rulebook-top"><strong>MY BUILDING BOOK</strong><button class="book-close" aria-label="Save and close building book">✕</button></div><h2></h2><div class="book-view"><button class="book-overhead">Overhead view</button><button class="book-angle">3D view</button></div><p class="book-instruction" role="status" aria-live="polite"></p><p class="book-lesson"></p><button class="book-read" aria-label="Read this construction step aloud">Listen</button><label class="book-detail"><input type="checkbox" checked> Build smaller pieces</label><progress max="1" value="0" aria-label="Property construction progress"></progress><div class="book-piece-row"><button class="book-piece" aria-label="Drag the next building piece"><img alt=""><span></span></button><span class="book-arrow" aria-hidden="true">➜</span><span class="book-example">Drop inside<br>the outline</span></div><button class="book-snap">Place this piece</button><button class="book-upgrade" hidden>Start the new construction lesson</button><details><summary>See the whole rulebook</summary><ol class="book-steps"></ol></details><details class="book-reference"><summary>About this home and lesson</summary><p></p></details>';
 // A thin, non-interactive outline leaves all construction details visible.
 const outline=document.createElementNS('http://www.w3.org/2000/svg','svg');outline.classList.add('property-drop-outline');outline.setAttribute('hidden','');outline.setAttribute('aria-hidden','true');
 const border=document.createElementNS('http://www.w3.org/2000/svg','polygon');outline.append(border);host.append(panel,outline);
 const drag=document.createElement('img');drag.className='property-drag-piece';drag.hidden=true;drag.alt='';document.body.append(drag);
 const ghostMaterial=new T.MeshBasicMaterial({color:'#b4f365',transparent:true,opacity:.27,depthWrite:false,side:T.DoubleSide}),ghost=new T.Group();scene.add(ghost);
 let current=null,parts=[],step=0,held=false,motion=null,lastFrame=0,footprint=null;
 const pieceButton=panel.querySelector('.book-piece'),snapButton=panel.querySelector('.book-snap'),instruction=panel.querySelector('.book-instruction');
 function nextPart(){const stage=parts[step];return current?.constructionDetail&&stage?.pieces?.length?stage.pieces[current.constructionPieces||0]||stage:stage;}
 function disposeGhost(){ghost.clear();}
 function paint(){pieceButton.disabled=!!motion;snapButton.disabled=!!motion;disposeGhost();const complete=step>=parts.length;panel.querySelector('progress').max=parts.length;panel.querySelector('progress').value=step+(current.constructionDetail&&parts[step]?.pieces?.length?(current.constructionPieces||0)/parts[step].pieces.length:0);pieceButton.hidden=complete;snapButton.hidden=complete;panel.querySelector('.book-arrow').hidden=complete;panel.querySelector('.book-example').hidden=complete;outline.toggleAttribute('hidden',complete);panel.querySelector('.book-steps').replaceChildren();parts.forEach((p,i)=>{const li=document.createElement('li');li.textContent=(i<step?'✓ ':i===step?'→ ':'')+p.name;li.classList.toggle('current',i===step);panel.querySelector('.book-steps').append(li);});
  panel.querySelector('.book-lesson').textContent=complete?(isBuildableCar(current.kind)?'Your chassis, suspension, engine, drivetrain, and body now work together.':'Foundations, pipes, framing, weather protection, and finishes all work together.'):parts[step].lesson||'';
  if(complete){instruction.textContent=isBuildableCar(current.kind)?'You built your car! Close the book to explore.':'You built it! Your property is ready to explore.';return;}
  const part=nextPart(),pieces=current.constructionDetail?parts[step].pieces:[];instruction.textContent='Step '+(step+1)+' of '+parts.length+(pieces?.length?', piece '+((current.constructionPieces||0)+1)+' of '+pieces.length:'')+'. Drag this piece anywhere inside the property outline.';pieceButton.querySelector('span').textContent=part.name;const preview=thumbnail(part.model,part.id+current.kind);pieceButton.querySelector('img').src=preview;drag.src=preview;
  const m=part.model.clone();m.traverse(o=>{if(o.isMesh){o.material=ghostMaterial;o.castShadow=false;o.receiveShadow=false;}});ghost.add(m);ghost.position.set(current.x,current.y,current.z);ghost.rotation.y=current.rot;ghost.scale.setScalar(current.s);ghost.updateMatrixWorld(true);outline.classList.remove('over');
 }
 function start(item,name){close(false);current=item;if(!Number.isFinite(item.constructionStep))item.constructionVersion=supportsHomeLesson(item.kind)?2:1;parts=townBlueprint(item.kind,item.constructionVersion);if(!parts)return;footprint=constructionFootprint(parts);step=Number.isFinite(item.constructionStep)?Math.min(parts.length,Math.max(0,Math.floor(item.constructionStep))):0;current.constructionStep=step;current.constructionDetail=item.constructionVersion===2&&(item.constructionDetail??true);current.constructionPieces=Math.max(0,Math.min(parts[step]?.pieces?.length-1||0,Math.floor(item.constructionPieces)||0));panel.querySelector('.book-detail').hidden=item.constructionVersion!==2;panel.querySelector('.book-detail input').checked=current.constructionDetail;onProgress(current,step);panel.querySelector('h2').textContent=name;panel.querySelector('.book-upgrade').hidden=!supportsHomeLesson(item.kind)||item.constructionVersion===2;panel.querySelector('.book-reference').hidden=isBuildableCar(item.kind);panel.querySelector('.book-reference p').textContent=(item.kind==='allentownHome'?'Allentown: exterior proportions informed by a public aerial photo, floor plan, and the owner’s walkthrough video.':item.kind==='chatsboroHome'?'Chatsboro: the exterior uses the original 1987 city site sketch, overhead references, and the owner’s front photo. No verified interior floor plan was available.':ESTATE_STYLES[item.kind]?.note||'An original home inspired by Woodland Hills estate architecture.')+' Dimensions are approximate. Pipes, studs, and wiring are simplified teaching layouts, not this home’s actual engineering plans. Inspections and sequencing vary by project.';panel.hidden=false;host.classList.add('building-property');onView(item);paint();}
 function snap(){if(!current||step>=parts.length||motion)return;const item=current,part=nextPart(),stage=parts[step];disposeGhost();if(item.constructionDetail&&stage.pieces?.length&&(item.constructionPieces||0)+1<stage.pieces.length){item.constructionPieces=(item.constructionPieces||0)+1;}else{step++;item.constructionPieces=0;}item.constructionStep=step;const root=onProgress(item,step);const added=root.children.find(n=>n.userData.lessonPart===part.id||n.userData.lessonPart===stage.id)||(current.constructionVersion!==2?root.children.at(-1):null);if(added&&!reduced){added.position.y=.7;motion={node:added,left:.28};}window.SFX?.snap?.();paint();}
 function close(notify=true){window.speechSynthesis?.cancel();stopDrag();if(motion){motion.node.position.y=0;motion=null;}current=null;parts=[];panel.hidden=true;outline.setAttribute('hidden','');disposeGhost();host.classList.remove('building-property');if(notify)onClose();}
 function dropArea(){const rect=canvas.getBoundingClientRect();return {rect,polygon:projectConstructionFootprint(footprint,current,camera,rect)};}
 function accepts(e){if(!current||!footprint)return false;const {rect,polygon}=dropArea(),r=panel.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)return false;return acceptsConstructionDrop({x:e.clientX,y:e.clientY},polygon,rect);}
 function stopDrag(){held=false;drag.hidden=true;outline.classList.remove('dragging','over');}
 pieceButton.onpointerdown=e=>{if(e.button>0||!current||step>=parts.length||motion)return;e.preventDefault();held=true;outline.classList.add('dragging');pieceButton.setPointerCapture(e.pointerId);drag.hidden=false;drag.style.left=e.clientX+'px';drag.style.top=e.clientY+'px';};
 pieceButton.onpointermove=e=>{if(!held)return;drag.style.left=e.clientX+'px';drag.style.top=e.clientY+'px';outline.classList.toggle('over',accepts(e));};
 pieceButton.onpointerup=e=>{if(!held)return;const valid=accepts(e);stopDrag();if(valid)snap();else instruction.textContent='Drop anywhere inside the property outline. Your piece is ready to try again.';};
 pieceButton.onpointercancel=stopDrag;pieceButton.onlostpointercapture=stopDrag;
 // Enter and Space provide the same placement for players who cannot drag.
 pieceButton.onclick=e=>{if(e.detail===0)snap();};
 panel.querySelector('.book-overhead').onclick=()=>{if(current)onView(current,'overhead');};panel.querySelector('.book-angle').onclick=()=>{if(current)onView(current,'angle');};panel.querySelector('.book-upgrade').onclick=()=>{const item=current,name=panel.querySelector('h2').textContent;item.constructionVersion=2;item.constructionStep=0;start(item,name);};panel.querySelector('.book-read').hidden=!('speechSynthesis' in window);panel.querySelector('.book-read').onclick=()=>{window.speechSynthesis?.cancel();const text=step<parts.length?parts[step].name+'. '+(parts[step].lesson||instruction.textContent):instruction.textContent;const speech=new SpeechSynthesisUtterance(text);speech.rate=.88;window.speechSynthesis.speak(speech);};
 panel.querySelector('.book-detail input').onchange=e=>{if(!current)return;current.constructionDetail=e.target.checked;current.constructionPieces=0;if(motion){motion.node.position.y=0;motion=null;}onProgress(current,step);paint();};
 snapButton.onclick=snap;panel.querySelector('.book-close').onclick=()=>close();
 function update(now){const dt=Math.min(.05,(now-lastFrame)/1000||0);lastFrame=now;if(motion){motion.left-=dt;motion.node.position.y=Math.max(0,.7*(motion.left/.28)**2);if(motion.left<=0){motion.node.position.y=0;motion=null;pieceButton.disabled=false;snapButton.disabled=false;}}
  if(!current||step>=parts.length)return;ghostMaterial.opacity=reduced?.22:.17+Math.sin(now*.003)*.04;
  const {rect,polygon}=dropArea(),base=host.getBoundingClientRect();outline.style.left=(rect.left-base.left)+'px';outline.style.top=(rect.top-base.top)+'px';outline.style.width=rect.width+'px';outline.style.height=rect.height+'px';outline.setAttribute('viewBox','0 0 '+rect.width+' '+rect.height);border.setAttribute('points',polygon.map(p=>(p.x-rect.left)+','+(p.y-rect.top)).join(' '));outline.toggleAttribute('hidden',polygon.some(p=>!Number.isFinite(p.x+p.y+p.depth)||Math.abs(p.depth)>1));}

 return {start,close,update,get active(){return !!current;},get item(){return current;}};
}
