import * as T from './vendor/three.module.js';
import {townBlueprint,hasBlueprint,supportsHomeLesson} from './town-models.js?v=allentown-video1';
export {hasBlueprint};
export function createPropertyBuilder({host,scene,camera,canvas,onProgress,onView,onClose,thumbnail,reduced=false}){
 const panel=document.createElement('section');panel.className='property-rulebook';panel.hidden=true;panel.setAttribute('aria-label','Property building rulebook');
 panel.innerHTML='<div class="rulebook-top"><strong>MY BUILDING BOOK</strong><button class="book-close" aria-label="Save and close building book">✕</button></div><h2></h2><div class="book-view"><button class="book-overhead">Overhead view</button><button class="book-angle">3D view</button></div><p class="book-instruction" role="status" aria-live="polite"></p><p class="book-lesson"></p><button class="book-read" aria-label="Read this construction step aloud">Listen</button><label class="book-detail"><input type="checkbox" checked> Build smaller pieces</label><progress max="1" value="0" aria-label="Property construction progress"></progress><div class="book-piece-row"><button class="book-piece" aria-label="Drag the next building piece"><img alt=""><span></span></button><span class="book-arrow" aria-hidden="true">➜</span><span class="book-example">Match the<br>glowing shape</span></div><button class="book-snap">Snap highlighted piece</button><button class="book-upgrade" hidden>Start the new construction lesson</button><details><summary>See the whole rulebook</summary><ol class="book-steps"></ol></details><details class="book-reference"><summary>About this home and lesson</summary><p></p></details>';
 const target=document.createElement('button');target.className='property-drop-target';target.hidden=true;target.setAttribute('aria-label','Place piece on highlighted spot');target.textContent='＋';host.append(panel,target);
 const drag=document.createElement('img');drag.className='property-drag-piece';drag.hidden=true;drag.alt='';document.body.append(drag);
 const ghostMaterial=new T.MeshBasicMaterial({color:'#b4f365',transparent:true,opacity:.27,depthWrite:false,side:T.DoubleSide}),ghost=new T.Group();scene.add(ghost);
 let current=null,parts=[],step=0,held=false,motion=null,lastFrame=0,selectedPiece=false;
 const pieceButton=panel.querySelector('.book-piece'),snapButton=panel.querySelector('.book-snap'),instruction=panel.querySelector('.book-instruction');
 function nextPart(){const stage=parts[step];return current?.constructionDetail&&stage?.pieces?.length?stage.pieces[current.constructionPieces||0]||stage:stage;}
 function disposeGhost(){ghost.clear();}
 function paint(){pieceButton.disabled=!!motion;snapButton.disabled=!!motion;target.disabled=!!motion;disposeGhost();const complete=step>=parts.length;panel.querySelector('progress').max=parts.length;panel.querySelector('progress').value=step+(current.constructionDetail&&parts[step]?.pieces?.length?(current.constructionPieces||0)/parts[step].pieces.length:0);pieceButton.hidden=complete;snapButton.hidden=complete;panel.querySelector('.book-arrow').hidden=complete;panel.querySelector('.book-example').hidden=complete;target.hidden=complete;panel.querySelector('.book-steps').replaceChildren();parts.forEach((p,i)=>{const li=document.createElement('li');li.textContent=(i<step?'✓ ':i===step?'→ ':'')+p.name;li.classList.toggle('current',i===step);panel.querySelector('.book-steps').append(li);});
  panel.querySelector('.book-lesson').textContent=complete?'Foundations, pipes, framing, weather protection, and finishes all work together.':parts[step].lesson||'';
  if(complete){instruction.textContent='You built it! Your property is ready to explore.';return;}
  const part=nextPart(),pieces=current.constructionDetail?parts[step].pieces:[];instruction.textContent='Step '+(step+1)+' of '+parts.length+(pieces?.length?', piece '+((current.constructionPieces||0)+1)+' of '+pieces.length:'')+'. Drag this piece onto the glowing spot.';pieceButton.querySelector('span').textContent=part.name;const preview=thumbnail(part.model,part.id+current.kind);pieceButton.querySelector('img').src=preview;drag.src=preview;
  const m=part.model.clone();m.traverse(o=>{if(o.isMesh){o.material=ghostMaterial;o.castShadow=false;o.receiveShadow=false;}});ghost.add(m);ghost.position.set(current.x,current.y,current.z);ghost.rotation.y=current.rot;ghost.scale.setScalar(current.s);ghost.updateMatrixWorld(true);target.setAttribute('aria-label','Place '+part.name+' on highlighted spot');selectedPiece=false;target.classList.remove('ready');
 }
 function start(item,name){close(false);current=item;if(!Number.isFinite(item.constructionStep))item.constructionVersion=supportsHomeLesson(item.kind)?2:1;parts=townBlueprint(item.kind,item.constructionVersion);if(!parts)return;step=Number.isFinite(item.constructionStep)?Math.min(parts.length,Math.max(0,Math.floor(item.constructionStep))):0;current.constructionStep=step;current.constructionDetail=item.constructionVersion===2&&(item.constructionDetail??true);current.constructionPieces=Math.max(0,Math.min(parts[step]?.pieces?.length-1||0,Math.floor(item.constructionPieces)||0));panel.querySelector('.book-detail').hidden=item.constructionVersion!==2;panel.querySelector('.book-detail input').checked=current.constructionDetail;onProgress(current,step);panel.querySelector('h2').textContent=name;panel.querySelector('.book-upgrade').hidden=!supportsHomeLesson(item.kind)||item.constructionVersion===2;panel.querySelector('.book-reference p').textContent=(item.kind==='allentownHome'?'Allentown: exterior proportions informed by a public aerial photo, floor plan, and the owner’s walkthrough video.':item.kind==='chatsboroHome'?'Chatsboro: exterior footprint informed by a satellite view and front photo. A verified floor plan was not available.':'An original home inspired by Woodland Hills estate architecture.')+' Dimensions are approximate. Pipes, studs, and wiring are simplified teaching layouts, not this home’s actual engineering plans. Inspections and sequencing vary by project.';panel.hidden=false;host.classList.add('building-property');onView(item);paint();}
 function snap(){if(!current||step>=parts.length||motion)return;const item=current,part=nextPart(),stage=parts[step];disposeGhost();if(item.constructionDetail&&stage.pieces?.length&&(item.constructionPieces||0)+1<stage.pieces.length){item.constructionPieces=(item.constructionPieces||0)+1;}else{step++;item.constructionPieces=0;}item.constructionStep=step;const root=onProgress(item,step);const added=root.children.find(n=>n.userData.lessonPart===part.id||n.userData.lessonPart===stage.id)||(current.constructionVersion!==2?root.children.at(-1):null);if(added&&!reduced){added.position.y=.7;motion={node:added,left:.28};}window.SFX?.snap?.();paint();}
 function close(notify=true){window.speechSynthesis?.cancel();held=false;drag.hidden=true;if(motion){motion.node.position.y=0;motion=null;}current=null;parts=[];panel.hidden=true;target.hidden=true;disposeGhost();host.classList.remove('building-property');if(notify)onClose();}
 pieceButton.onpointerdown=e=>{if(!current||step>=parts.length)return;e.preventDefault();held=true;selectedPiece=true;target.classList.add('ready');pieceButton.setPointerCapture(e.pointerId);drag.hidden=false;drag.style.left=e.clientX+'px';drag.style.top=e.clientY+'px';};
 pieceButton.onpointermove=e=>{if(!held)return;drag.style.left=e.clientX+'px';drag.style.top=e.clientY+'px';const r=target.getBoundingClientRect();target.classList.toggle('over',e.clientX>=r.left-35&&e.clientX<=r.right+35&&e.clientY>=r.top-35&&e.clientY<=r.bottom+35);};
 pieceButton.onpointerup=e=>{if(!held)return;held=false;drag.hidden=true;const r=target.getBoundingClientRect();target.classList.remove('over');if(e.clientX>=r.left-35&&e.clientX<=r.right+35&&e.clientY>=r.top-35&&e.clientY<=r.bottom+35)snap();else instruction.textContent='Bring the piece to the glowing +. Or tap the + to snap it.';};
 pieceButton.onpointercancel=()=>{held=false;drag.hidden=true;target.classList.remove('over');};pieceButton.onclick=()=>{selectedPiece=true;target.classList.add('ready');};
 panel.querySelector('.book-overhead').onclick=()=>{if(current)onView(current,'overhead');};panel.querySelector('.book-angle').onclick=()=>{if(current)onView(current,'angle');};panel.querySelector('.book-upgrade').onclick=()=>{const item=current,name=panel.querySelector('h2').textContent;item.constructionVersion=2;item.constructionStep=0;start(item,name);};panel.querySelector('.book-read').hidden=!('speechSynthesis' in window);panel.querySelector('.book-read').onclick=()=>{window.speechSynthesis?.cancel();const text=step<parts.length?parts[step].name+'. '+(parts[step].lesson||instruction.textContent):instruction.textContent;const speech=new SpeechSynthesisUtterance(text);speech.rate=.88;window.speechSynthesis.speak(speech);};
 panel.querySelector('.book-detail input').onchange=e=>{if(!current)return;current.constructionDetail=e.target.checked;current.constructionPieces=0;if(motion){motion.node.position.y=0;motion=null;}onProgress(current,step);paint();};
 target.onclick=snap;snapButton.onclick=snap;panel.querySelector('.book-close').onclick=()=>close();
 function update(now){const dt=Math.min(.05,(now-lastFrame)/1000||0);lastFrame=now;if(motion){motion.left-=dt;motion.node.position.y=Math.max(0,.7*(motion.left/.28)**2);if(motion.left<=0){motion.node.position.y=0;motion=null;pieceButton.disabled=false;snapButton.disabled=false;target.disabled=false;}}
  if(!current||step>=parts.length)return;ghostMaterial.opacity=reduced?.3:.22+Math.sin(now*.003)*.07;const p=ghost.localToWorld(nextPart().center.clone());p.project(camera);const rect=canvas.getBoundingClientRect(),base=host.getBoundingClientRect();target.style.left=(rect.left-base.left+(p.x+1)*rect.width/2)+'px';target.style.top=(rect.top-base.top+(1-p.y)*rect.height/2)+'px';target.hidden=p.z>1||p.z< -1;}
 return {start,close,update,get active(){return !!current;},get item(){return current;}};
}
