import * as T from './vendor/three.module.js';
import {RGBELoader} from './vendor/RGBELoader.js';
import {Water} from './vendor/Water.js';
const loader=new T.TextureLoader(),textures=new Map(),materials=new Map();
function texture(asset,channel,repeat){const key=asset+channel+repeat;if(textures.has(key))return textures.get(key);const t=loader.load('assets/realism/'+asset+'_'+channel+'.jpg');t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(...repeat);t.anisotropy=4;if(channel==='Diffuse')t.colorSpace=T.SRGBColorSpace;textures.set(key,t);return t;}
export function scannedMaterial(asset,repeat=[1,1],color='#ffffff'){const key=asset+repeat+color;if(materials.has(key))return materials.get(key);const m=new T.MeshStandardMaterial({color,map:texture(asset,'Diffuse',repeat),normalMap:texture(asset,'nor_gl',repeat),roughnessMap:texture(asset,'Rough',repeat),roughness:1,normalScale:new T.Vector2(.45,.45),side:T.DoubleSide});m.userData.shared=true;materials.set(key,m);return m;}
export function worldUV(geo,scale=1){const p=geo.attributes.position,uv=[];for(let i=0;i<p.count;i++)uv.push(p.getX(i)*scale,p.getZ(i)*scale);geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));return geo;}
export function loadLighting(renderer,scene,kind,onReady=()=>{}){const file=kind==='studio'?'studio_small_08':'kloofendal_48d_partly_cloudy_puresky';new RGBELoader().load('assets/realism/'+file+'_hdri.hdr',hdr=>{hdr.mapping=T.EquirectangularReflectionMapping;const generator=new T.PMREMGenerator(renderer),target=generator.fromEquirectangular(hdr);generator.dispose();scene.environment=target.texture;scene.environmentIntensity=kind==='studio'?.6:.8;if(kind!=='studio'){scene.background=hdr;scene.backgroundIntensity=.85;scene.backgroundBlurriness=.035;}else hdr.dispose();onReady();},undefined,()=>onReady());}
let normals;
function normalTexture(){if(normals)return normals;const n=128,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const u=x/n*Math.PI*2,v=y/n*Math.PI*2,a=.3*Math.cos(u*7+Math.sin(v*5))+.2*Math.sin(u*13+v*11),b=.3*Math.cos(v*8+Math.sin(u*4))+.2*Math.sin(v*17-u*9),normal=new T.Vector3(-a,-b,1).normalize(),i=(y*n+x)*4;data[i]=(normal.x*.5+.5)*255;data[i+1]=(normal.y*.5+.5)*255;data[i+2]=(normal.z*.5+.5)*255;data[i+3]=255;}normals=new T.DataTexture(data,n,n);normals.wrapS=normals.wrapT=T.RepeatWrapping;normals.magFilter=T.LinearFilter;normals.minFilter=T.LinearMipmapLinearFilter;normals.generateMipmaps=true;normals.needsUpdate=true;return normals;}
export function reflectiveWater(geometry,{aquarium=false,sun=new T.Vector3(-.55,.8,.35)}={}){geometry.rotateX(Math.PI/2);const size=innerWidth<650?256:512,water=new Water(geometry,{textureWidth:size,textureHeight:size,waterNormals:normalTexture(),sunDirection:sun.clone().normalize(),sunColor:'#fff4dc',waterColor:aquarium?'#29968c':'#4fe2db',distortionScale:aquarium?.22:.48,alpha:aquarium?.18:.72,fog:true});water.rotation.x=-Math.PI/2;water.material.uniforms.size.value=8;water.material.side=T.DoubleSide;water.material.transparent=true;water.material.depthWrite=false;water.renderOrder=3;water.material.fragmentShader=water.material.fragmentShader.replace('float rf0 = 0.3;','float rf0 = 0.025;').replace('float shiny,','float shiny,');const reflect=water.onBeforeRender;let last=-1000;water.onBeforeRender=function(...args){const now=performance.now();if(now-last>(innerWidth<650?100:45)){last=now;reflect.apply(this,args);}};water.userData.tick=time=>{water.material.uniforms.time.value=time*.18;};return water;}
