import * as T from './vendor/three.module.js';
import {scannedMaterial} from './realism.js?v=estates4';
const supported=new Set(['rock','grass','pinkcoral','fan','anemone']),cache=new Map(),mats=new Map();
function mat(color){if(!mats.has(color)){const m=new T.MeshStandardMaterial({color,roughness:.84});m.userData.shared=true;mats.set(color,m);}return mats.get(color);}
function add(g,geo,color){const m=new T.Mesh(geo,typeof color==='string'?mat(color):color);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function tube(g,pts,r,color){return add(g,new T.TubeGeometry(new T.CatmullRomCurve3(pts.map(p=>new T.Vector3(...p))),10,r,6,false),color);}
function sphere(g,x,y,z,r,color){const o=add(g,new T.SphereGeometry(r,8,6),color);o.position.set(x,y,z);return o;}
function merge(g){g.updateMatrixWorld(true);const buckets=new Map();g.traverse(o=>{if(!o.isMesh)return;const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(o.matrixWorld);let b=buckets.get(o.material);if(!b)buckets.set(o.material,b={p:[],n:[],uv:[]});for(const v of geo.attributes.position.array)b.p.push(v);for(const v of geo.attributes.normal.array)b.n.push(v);for(const v of geo.attributes.uv.array)b.uv.push(v);geo.dispose();o.geometry.dispose();});const out=new T.Group();for(const [m,b] of buckets){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(b.p,3));geo.setAttribute('normal',new T.Float32BufferAttribute(b.n,3));geo.setAttribute('uv',new T.Float32BufferAttribute(b.uv,2));geo.userData.shared=true;add(out,geo,m);}return out;}
export function reefHabitat(id){if(!supported.has(id))return null;if(cache.has(id))return cache.get(id).clone();const g=new T.Group();
 if(id==='rock'){const stone=scannedMaterial('coast_sand_01',[2,2],'#74867d');for(let k=0;k<4;k++){const geo=new T.IcosahedronGeometry(1,3),p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),n=1+.13*Math.sin(x*7+z*8)*Math.cos(y*6-z*5)+.04*Math.sin(x*23+y*17);p.setXYZ(i,x*n,y*n,z*n);}geo.computeVertexNormals();const m=add(g,geo,stone);m.position.set((k%2-.5)*.62,.22+(k%2)*.1,(Math.floor(k/2)-.5)*.55);m.scale.set(.55,.35,.46);m.rotation.set(k*.2,k*1.3,k*.1);}}
 if(id==='grass'){for(let k=0;k<18;k++){const a=k*2.4,h=.7+(k%5)*.16,p=[],ix=[];for(let j=0;j<=14;j++){const q=j/14,bend=q*q*.34,w=Math.sin(q*Math.PI)*.045+.008;for(const side of [-1,1])p.push(Math.cos(a)*(.12+bend)+Math.sin(a)*w*side,q*h,Math.sin(a)*(.12+bend)-Math.cos(a)*w*side);if(j<14){const n=j*2;ix.push(n,n+1,n+2,n+1,n+3,n+2);}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(p,3));geo.setIndex(ix);geo.computeVertexNormals();geo.setAttribute('uv',new T.Float32BufferAttribute(Array(p.length/3*2).fill(0),2));const leafmat=mat(k%2?'#488349':'#71974a');leafmat.side=T.DoubleSide;add(g,geo,leafmat);}}
 if(id==='pinkcoral'){for(let k=0;k<9;k++){const a=k*2.4,x=Math.cos(a)*.34,z=Math.sin(a)*.28,h=.55+(k%4)*.15;tube(g,[[0,.02,0],[x*.7,h*.45,z*.7],[x,h,z]],.055,k%2?'#bd826c':'#c99380');for(let j=0;j<3;j++){const tx=x+Math.cos(a+j*2)*.2,tz=z+Math.sin(a+j*2)*.2,ty=h+.17+(j%2)*.1;tube(g,[[x*.7,h*.55,z*.7],[x,h*.8,z],[tx,ty,tz]],.033,'#c99380');sphere(g,tx,ty,tz,.04,'#e6c3a6');}}}
 if(id==='fan'){function branch(x,y,angle,len,depth){const tx=x+Math.sin(angle)*len,ty=y+Math.cos(angle)*len;tube(g,[[x,y,0],[(x+tx)/2,(y+ty)/2,.02],[tx,ty,0]],.009+depth*.005,depth>2?'#9c6b59':'#b88669');if(depth>0){branch(tx,ty,angle-.38,len*.7,depth-1);branch(tx,ty,angle+.38,len*.7,depth-1);}}branch(0,.03,0,.38,4);}
 if(id==='anemone'){sphere(g,0,.11,0,.35,'#98795e').scale.set(1,.3,1);for(let k=0;k<48;k++){const a=k*2.4,r=.12+(k%5)*.06,h=.32+(k%7)*.04,x=Math.cos(a)*r,z=Math.sin(a)*r;tube(g,[[x,.08,z],[x*1.15,h*.65,z*1.15],[x*1.35+.045*Math.sin(k),h,z*1.35]],.023,k%2?'#a9a477':'#c1b893');sphere(g,x*1.35+.045*Math.sin(k),h,z*1.35,.031,'#d5c5a0');}}
 const model=merge(g);cache.set(id,model);return model.clone();}
