import * as T from './vendor/three.module.js';
import {makeModel,mesh,block,orb,disposeModel} from './chilltopia-models.js?v=20260907-release3';
// One WebGL renderer supplies all visible display tanks, including the inspection tank.
let renderer,last=0,entries=[],inspection=null,onChoose;
const dialog=document.createElement('dialog');dialog.id='fishShopDetail';dialog.className='fish-detail';document.body.append(dialog);
const observer=new IntersectionObserver(es=>{for(const e of es){const item=entries.find(i=>i.canvas===e.target);if(item)item.visible=e.isIntersecting;}});
function ensureRenderer(){if(renderer)return;renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(480,300);renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;}
function tank(d,canvas){const scene=new T.Scene();scene.background=new T.Color('#093b48');scene.fog=new T.Fog('#093b48',7,16);scene.add(new T.HemisphereLight('#b8f6ff','#8f8359',2));const light=new T.DirectionalLight('#defaff',3.2);light.position.set(-2,4,3);scene.add(light);const room=new T.Group();scene.add(room);
 block(room,'#082936',0,1,-1,4.1,2.6,.1);block(room,'#d6caa1',0,-.13,0,4.1,.18,2);for(const x of [-2,2])block(room,'#173b3f',x,1,0,.06,2.5,2.1);for(const y of [-.15,2.25])block(room,'#203f42',0,y,0,4.15,.09,2.1);
 block(room,new T.MeshBasicMaterial({color:'#cafbff'}),0,2.15,-.15,3.3,.03,.07);
 for(let i=0;i<16;i++)orb(room,i%2?'#c1b180':'#eee2ba',Math.sin(i*12.9)*1.7,-.015,Math.cos(i*9.1)*.7,.04,.03,.04);
 const plant=makeModel('grass');plant.scale.setScalar(.65);plant.position.set(-1.5,0,-.6);room.add(plant);const rock=makeModel('rock');rock.scale.setScalar(.5);rock.position.set(1.3,0,-.45);room.add(rock);
 const model=makeModel(d.id);room.add(model);const box=new T.Box3().setFromObject(model),size=box.getSize(new T.Vector3());const scale=Math.min(1.4,2.2/Math.max(size.x,size.y,size.z));model.scale.setScalar(scale);model.position.y=d.fish&&!d.crawler?1.05:.02;model.rotation.y=-.25;
 const camera=new T.PerspectiveCamera(33,1.6,.1,30);camera.position.set(.25,1.6,5.1);camera.lookAt(0,1,0);return {scene,room,model,camera,canvas,ctx:canvas.getContext('2d'),d,visible:true};}
function discard(t){if(t)disposeModel(t.room);}
export function clearTanks(){observer.disconnect();entries.forEach(discard);entries=[];}
function habitat(d){return d.habitat||(d.id.includes('cray')?'Freshwater color variety':d.fish?'Crustacean display':'Aquarium decoration');}
export function displayTank(d,choose){ensureRenderer();onChoose=choose;const card=document.createElement('button');card.className='card display-tank';card.setAttribute('aria-label','Inspect '+d.name);const canvas=document.createElement('canvas');canvas.width=480;canvas.height=300;canvas.setAttribute('aria-hidden','true');const title=document.createElement('span');title.className='card-name';title.textContent=d.name;const label=document.createElement('small');label.className='tank-label';label.textContent=habitat(d);const price=document.createElement('span');price.className='card-price';price.textContent=d.price?d.price+' bucks':'FREE TO BUILD';const inspect=document.createElement('span');inspect.className='tank-inspect';inspect.textContent='🔍 Look closer';card.append(canvas,title,label,price,inspect);const entry=tank(d,canvas);entries.push(entry);observer.observe(canvas);render(entry,0);card.onclick=()=>inspectTank(d,choose);return card;}
function inspectTank(d,choose){discard(inspection);dialog.replaceChildren();const top=document.createElement('div');top.className='sheet-top';const tag=document.createElement('span');tag.className='eyebrow';tag.textContent='CHILLTOPIA AQUATICS';const close=document.createElement('button');close.textContent='✕';close.setAttribute('aria-label','Leave display tank');close.onclick=()=>dialog.close();top.append(tag,close);const canvas=document.createElement('canvas');canvas.width=480;canvas.height=300;canvas.className='inspection-tank';const title=document.createElement('h2');title.textContent=d.name;const latin=document.createElement('p');latin.className='species-latin';latin.textContent=d.latin||habitat(d);const note=document.createElement('p');note.textContent=d.note||(d.crawler?'Watch its jointed legs and claws as it explores the floor.':'Turn this display to look at your next aquarium decoration.');const controls=document.createElement('div');controls.className='tank-controls';const turn=document.createElement('button');turn.textContent='↻ Turn view';turn.onclick=()=>{if(inspection)inspection.model.rotation.y+=.65;};const buy=document.createElement('button');buy.className='wide-button';buy.textContent=d.price?'＋ Bring home · '+d.price+' bucks':'＋ Bring home · free';buy.onclick=()=>{dialog.close();choose(d.id);document.querySelector('#game').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};controls.append(turn,buy);const small=document.createElement('p');small.className='note';small.textContent=habitat(d)+'. Pretend bucks. Choose a spot at home to finish adding it.';dialog.append(top,title,canvas,latin,note,controls,small);inspection=tank(d,canvas);render(inspection,0);dialog.showModal();}
dialog.addEventListener('close',()=>{discard(inspection);inspection=null;});
function render(e,time){if(e.d.fish&&!e.d.crawler){e.model.position.x=Math.sin(time*.6)*.22;e.model.position.y=1.05+Math.sin(time*1.1)*.055;if(e.model.userData.tail)e.model.userData.tail.rotation.y=Math.sin(time*6)*.23;}if(e.model.userData.legs)e.model.userData.legs.forEach((leg,i)=>leg.rotation.y=Math.sin(time*6+i)*.1);e.model.userData.fins?.forEach((f,i)=>f.rotation.y=(i?1:-1)*(.6+Math.sin(time*5)*.15));renderer.render(e.scene,e.camera);e.ctx.drawImage(renderer.domElement,0,0,480,300);}
export function tickTanks(now,paused){if(!renderer||now-last<120)return;last=now;for(const e of entries)if(e.visible)render(e,paused?0:now/1000);if(inspection)render(inspection,paused?0:now/1000);}
