import * as T from './vendor/three.module.js';
import {makeModel,orb,block,mesh,disposeModel} from './chilltopia-models.js?v=reef3';
import {scannedMaterial,loadLighting} from './realism.js';
const $=s=>document.querySelector(s),TOTAL=5,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let paused=false;
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶ Keep playing':'⏸ Pause';$('#pause').setAttribute('aria-pressed',String(paused));$('#clawButton').disabled=paused||!(phase==='holding'||phase==='open'&&selectedAnimal&&!selectedAnimal.done);};window.SFX?.bind($('#sound'));window.SFX?.ambience('water');
let renderer;try{renderer=new T.WebGLRenderer({antialias:true});}catch{$('#loading').innerHTML='This device could not start 3D. <a href="build.html">Return to your aquarium</a>';throw Error('WebGL unavailable');}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Underwater catching cove. Tap an animal to close the claw, then tap again to open.');$('#view').append(renderer.domElement);$('#loading').remove();
const scene=new T.Scene();scene.background=new T.Color('#168fa7');scene.fog=new T.FogExp2('#208d9e',.022);const camera=new T.PerspectiveCamera(45,1,.1,100);camera.position.set(0,12,16);camera.lookAt(0,.4,0);scene.add(new T.HemisphereLight('#c6ffff','#55776e',2.2));const light=new T.DirectionalLight('#effff0',2.8);light.position.set(-5,16,8);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-13,right:13,top:13,bottom:-13});light.shadow.normalBias=.04;scene.add(light);loadLighting(renderer,scene,'studio');
const floor=mesh(scene,new T.PlaneGeometry(100,100),scannedMaterial('coast_sand_01',[14,14],'#e9e5ca'),0,-.1,0);floor.rotation.x=-Math.PI/2;
for(let i=0;i<16;i++){const a=i/16*Math.PI*2,x=Math.sin(a)*(9+(i%3)),z=Math.cos(a)*7;const g=makeModel(i%3===0?'rock':i%3===1?'grass':'pinkcoral');g.position.set(x,0,z);g.scale.setScalar(i%3===0?1.8:1.1);scene.add(g);}
const claw=new T.Group();scene.add(claw);claw.position.set(0,4.4,0);const metal=new T.MeshStandardMaterial({color:'#d5e8e5',metalness:.75,roughness:.22}),gold=new T.MeshStandardMaterial({color:'#ffd05f',metalness:.5,roughness:.3});mesh(claw,new T.CylinderGeometry(.55,.65,.65,24),gold,0,.2,0);const cable=mesh(claw,new T.CylinderGeometry(.045,.045,15,8),'#234c59',0,8,0);orb(claw,'#89f0e8',0,.7,0,.25);
const fingers=[];for(let i=0;i<3;i++){const pivot=new T.Group();pivot.rotation.y=i/3*Math.PI*2;claw.add(pivot);const hinge=new T.Group();hinge.position.set(0,-.1,.38);pivot.add(hinge);block(hinge,metal,0,-.48,.1,.16,1,.18);const tip=block(hinge,metal,0,-1,.02,.16,.3,.5);tip.rotation.x=-.5;orb(hinge,gold,0,0,0,.14);fingers.push(hinge);}
const ring=mesh(scene,new T.TorusGeometry(1,.045,8,48),new T.MeshBasicMaterial({color:'#a5ff73'}),0,.05,0);ring.rotation.x=-Math.PI/2;
const bubbleGeo=new T.SphereGeometry(.07,8,6),bubbleMat=new T.MeshBasicMaterial({color:'#bcf8ff',transparent:true,opacity:.45});const bubbles=[];for(let i=0;i<40;i++){const b=mesh(scene,bubbleGeo,bubbleMat,(i*7%23)-11,(i*.7)%10,(i*11%19)-9);b.castShadow=false;bubbles.push(b);}
// An open woven basket makes the destination visible in the 3D scene.
const basket=new T.Group();basket.position.set(3.8,0,4);scene.add(basket);
block(basket,'#99734e',0,.12,0,2.7,.2,2.05);
for(const side of [-1,1])for(let i=0;i<9;i++)block(basket,'#c5a171',-1.23+i*.307,.55,side*.98,.15,1,.11);
for(const side of [-1,1])for(let i=0;i<7;i++)block(basket,'#c5a171',side*1.3,.55,-.92+i*.307,.11,1,.15);
for(const y of [.27,.58,.9]){for(const z of [-1.02,1.02])block(basket,'#e1bf84',0,y,z,2.78,.08,.08);for(const x of [-1.34,1.34])block(basket,'#e1bf84',x,y,0,.08,.08,2.1);}
const basketCatches=[];
function showBasketCatch(index,kind){const g=makeModel(kind);g.scale.setScalar(.42);g.position.set(-.75+(index%3)*.7,.25+Math.floor(index/3)*.25,-.4+Math.floor(index/3)*.7);g.rotation.y=index*1.7;basket.add(g);basketCatches.push(g);}

const catchGroup=new T.Group();scene.add(catchGroup);const animals=[];let selectedAnimal=null,aimPosition=new T.Vector3(0,4.4,0);let phase='open',timer=0,caught=0,held=null,from=new T.Vector3(),destination=new T.Vector3(),last=0,time=0,paying=false;
function stock(){for(const a of animals){catchGroup.remove(a.g);disposeModel(a.g);}animals.length=0;const locations=[[-4,1.6],[0,-2.4],[4,1.4],[-3,-2.4],[2.8,-2.2]];locations.forEach(([x,z],i)=>{const g=makeModel(i%2?'redcrab':'lobster');g.position.set(x,0,z);g.scale.setScalar(1.25);g.rotation.y=(i%2?.4:-.3);catchGroup.add(g);animals.push({g,x,z,kind:i%2?'redcrab':'lobster',done:false,phase:i*2.3});});}
function terms(){const info=Wallet.workInfo('seafood');$('#pay').textContent=info.left?'Five catches · earn 10 bucks':'Free practice · today’s paid work is finished';}terms();document.addEventListener('wallet',terms);
function aim(){const left=animals.filter(a=>!a.done);if(!left.length)return null;return left.reduce((best,a)=>a.g.position.distanceTo(claw.position)<best.g.position.distanceTo(claw.position)?a:best,left[0]);}
function act(animal=selectedAnimal){if(paused)return;window.SFX?.unlock();if(phase==='open'){held=animal;if(!held||held.done){$('#hint').textContent='Choose an animal first. Tap it, or move the claw with the arrows.';return;}phase='lowering';timer=0;from.copy(claw.position);destination.copy(held.g.position);destination.y=1.65;$('#clawButton').disabled=true;$('#clawButton').textContent='🫧 Catching…';$('#hint').textContent='Down goes the claw. Snap!';}else if(phase==='holding'){phase='releasing';timer=0;$('#clawButton').disabled=true;$('#clawButton').textContent='🧺 Into the basket…';window.SFX?.splash();}}
function selectAnimal(a){selectedAnimal=a;if(a){aimPosition.set(a.g.position.x,4.4,a.g.position.z);$('#clawButton').disabled=false;$('#clawButton').textContent='🦞 👍 Catch this one!';$('#hint').textContent='Your claw is lined up. Press Catch!';}else{$('#clawButton').disabled=true;$('#clawButton').textContent='👆 Pick an animal first';$('#hint').textContent='Tap the animal you want, or move the claw with the arrows.';}}
$('#clawButton').onclick=()=>act();const ray=new T.Raycaster(),pointer=new T.Vector2();renderer.domElement.addEventListener('click',e=>{if(paused)return;if(phase==='holding'){act();return;}if(phase!=='open')return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(animals.filter(a=>!a.done).map(a=>a.g),true)[0];if(hit){const a=animals.find(a=>{let o=hit.object;while(o){if(o===a.g)return true;o=o.parent;}return false;});if(a)selectAnimal(a);}else{$('#hint').textContent='Tap right on a crab or lobster to choose your catch.';}});
for(const button of document.querySelectorAll('[data-move]'))button.onclick=()=>{if(paused||phase!=='open')return;const d=button.dataset.move;aimPosition.x=Math.max(-6,Math.min(6,aimPosition.x+(d==='left'?-1:d==='right'?1:0)));aimPosition.z=Math.max(-4,Math.min(4,aimPosition.z+(d==='up'?-1:d==='down'?1:0)));claw.position.copy(aimPosition);selectedAnimal=null;let near=null,best=1.2;for(const a of animals){const distance=Math.hypot(a.g.position.x-claw.position.x,a.g.position.z-claw.position.z);if(!a.done&&distance<best){near=a;best=distance;}}if(near)selectAnimal(near);else selectAnimal(null);};

async function finish(){if(paying)return;paying=true;phase='finished';$('#clawButton').hidden=true;$('#hint').textContent='Five catches! Checking your paycheck…';const pay=await Wallet.completeWork('seafood');$('#hint').textContent=pay?'🎉 Five catches! You earned 10 bucks. Put your paycheck in the piggy!':'🌟 Five catches! Great scooping. Today’s paid work is finished.';const bankLink=$('#finish a');bankLink.href=pay?'build.html?bank=1':'build.html';bankLink.textContent=pay?'🐷 Save my paycheck':'🐠 Back to aquarium';$('#finish').hidden=false;window.SFX?.fanfare();}
$('#again').onclick=()=>{paused=false;$('#pause').textContent='⏸ Pause';$('#pause').setAttribute('aria-pressed','false');for(const g of basketCatches){basket.remove(g);disposeModel(g);}basketCatches.length=0;caught=0;paying=false;held=null;phase='open';timer=0;stock();aimPosition.set(0,4.4,0);claw.position.copy(aimPosition);selectedAnimal=null;$('#count').textContent='0 / 5';$('#finish').hidden=true;$('#clawButton').hidden=false;selectAnimal(null);terms();};
function resize(){const w=$('#view').clientWidth,h=$('#view').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(0,innerWidth<600?20:12,innerWidth<600?24:16);camera.updateProjectionMatrix();camera.lookAt(0,.5,0);}new ResizeObserver(resize).observe($('#view'));
function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-last)/1000||0,.05);last=now;if(document.hidden)return;if(paused){renderer.render(scene,camera);return;}time+=dt;timer+=dt;for(const a of animals){if(reduced||a.done||a===held&&phase!=='lowering')continue;if(phase==='lowering'&&a===held)continue;a.g.position.set(a.x+Math.sin(time*.35+a.phase)*.3,.05,a.z+Math.cos(time*.25+a.phase)*.2);const legs=a.g.userData.legs;if(legs)legs.forEach((l,i)=>l.rotation.y=Math.sin(time*3+i)*.12);}
 let close=0;if(phase==='lowering'){const t=Math.min(1,timer/1.2),smooth=t*t*(3-2*t);claw.position.lerpVectors(from,destination,smooth);close=Math.max(0,(t-.65)/.35);if(t>=1){phase='lifting';timer=0;from.copy(claw.position);destination.copy(from);destination.y=4.4;window.SFX?.snap();}}
 if(phase==='lifting'){close=1;const t=Math.min(1,timer/1.1);claw.position.lerpVectors(from,destination,t*t*(3-2*t));held.g.position.copy(claw.position).add(new T.Vector3(0,-1.35,0));if(t>=1){phase='holding';$('#clawButton').disabled=false;$('#clawButton').textContent='🖐️ 👍 Open claw!';$('#hint').textContent='You caught one! Tap again to open the claw.';}}
 if(phase==='holding'){close=1;held.g.position.copy(claw.position).add(new T.Vector3(0,-1.35,0));}
 if(phase==='releasing'){close=Math.max(0,1-timer/.5);held.g.position.x+=(3.8-held.g.position.x)*dt*3;held.g.position.z+=(4-held.g.position.z)*dt*3;held.g.position.y=Math.max(0,held.g.position.y-dt*3);held.g.scale.setScalar(Math.max(.05,1.25-timer*.8));if(timer>1.4){held.done=true;held.g.visible=false;showBasketCatch(caught,held.kind);caught++;$('#count').textContent=caught+' / '+TOTAL;held=null;if(caught===TOTAL)finish();else{phase='open';selectAnimal(null);$('#hint').textContent='In the basket! Tap the next animal you want.';}}}
 fingers.forEach(f=>f.rotation.x=-.7+close*.85);if(phase==='open')claw.position.lerp(aimPosition,1-Math.exp(-dt*8));const next=held||selectedAnimal;ring.visible=!!next&&phase==='open';if(next){ring.position.set(next.g.position.x,.08,next.g.position.z);ring.scale.setScalar(reduced?1:1+Math.sin(time*2)*.05);}for(const b of bubbles){b.position.y+=reduced?0:dt*.5;if(b.position.y>12)b.position.y=0;}renderer.render(scene,camera);}
stock();resize();requestAnimationFrame(tick);
