import {resortPromenade} from './resort-scenery.js?v=cabana1';
import {mountSavings} from './savings-ui.js';
import * as T from './vendor/three.module.js';
import {makeModel,makePerson,mesh,orb,block,disposeModel} from './chilltopia-models.js?v=estates4';
import {attraction,animateAttraction,ATTRACTIONS,palm,surfaceTexture} from './park-attractions.js?v=estates4';
import {WIDTH,START_ROUTE,curveFor,frame,validateRoute,ribbon,slideCurve} from './park-geometry.js?v=20260907-sunlit';
import {scannedMaterial,worldUV,loadLighting,reflectiveWater} from './realism.js?v=estates4';
const $=s=>document.querySelector(s),KEY='cb:waterpark:v1',clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
window.SFX?.bind($('#parkSound'));window.SFX?.ambience('water');
const SLIDES=['straight','wave','spiral','tube','raft','speed'],TYPES=[...SLIDES,'bridge','tree','flowers','bench',...Object.keys(ATTRACTIONS)];
const names={...ATTRACTIONS,tube:'Tunnel slide',raft:'Family raft slide',speed:'Sky drop slide',straight:'Straight slide',wave:'Wavy slide',spiral:'Spiral slide',bridge:'Bridge',tree:'Shade tree',flowers:'Flower patch',bench:'Chill bench'};
const fresh=()=>({v:2,adventures:{},route:START_ROUTE.map(p=>p.map(v=>v*1.6)),items:[{type:'wave',t:.06},{type:'spiral',t:.25},{type:'tube',t:.44},{type:'speed',t:.59},{type:'bridge',t:.77},{type:'bucket',x:-4,z:0},{type:'mushroom',x:4,z:-1},{type:'pool',x:-10,z:12},{type:'icecream',x:1,z:14},{type:'burger',x:6,z:14},{type:'jets',x:12,z:8},{type:'umbrella',x:2,z:9},...Array.from({length:10},(_,i)=>({type:'palm',x:Math.cos(i*2.4)*17,z:Math.sin(i*2.4)*17,rot:i}))]});
function load(){try{const raw=localStorage.getItem(KEY),s=JSON.parse(raw);if(![1,2].includes(s?.v)||!Array.isArray(s.route)||!Array.isArray(s.items))return fresh();if(s.v===1){if(!localStorage.getItem('cb:waterpark:before-expansion'))localStorage.setItem('cb:waterpark:before-expansion',raw);s.route=s.route.map(p=>p.map(v=>v*1.5));s.items.forEach(i=>{if(Number.isFinite(i.x))i.x*=1.5;if(Number.isFinite(i.z))i.z*=1.5;});s.items.push({type:'bucket',x:-4,z:0},{type:'icecream',x:2,z:15},{type:'burger',x:7,z:15},{type:'mushroom',x:4,z:0},{type:'pool',x:-12,z:13});s.v=2;}if(validateRoute(s.route)){if(raw)localStorage.setItem('cb:waterpark:recovery',raw);return fresh();}s.adventures=s.adventures||{};s.items=s.items.filter(i=>TYPES.includes(i.type)).slice(0,90).map(i=>({...i,t:clamp(Number(i.t)||0,0,.99999),x:clamp(Number(i.x)||0,-20,20),z:clamp(Number(i.z)||0,-20,20),rot:Number(i.rot)||0}));return s;}catch{return fresh();}}
let state=load(),curve=curveFor(state.route),draft=null,bend=0,pending=null,selected=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,care=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='Saved on this device';}catch{$('#saveStatus').textContent='Could not save. Keep this tab open.';}}
const tell=t=>{$('#hint').textContent=t;};
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{$('#loading').innerHTML='3D is unavailable. <a href="classic.html">Open Classic</a>';throw Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;$('#parkViewport').append(renderer.domElement);$('#loading').remove();
const scene=new T.Scene();scene.background=new T.Color('#a5cede');scene.fog=new T.Fog('#bed6d7',55,160);scene.add(new T.HemisphereLight('#dfedf3','#556343',.45));const sun=new T.DirectionalLight('#fff0d0',2.4);sun.position.set(-22,32,14);sun.castShadow=true;sun.shadow.mapSize.set(innerWidth<650?1024:2048,innerWidth<650?1024:2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,far:85});sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;scene.add(sun);
const sky=new T.Mesh(new T.SphereGeometry(90,32,16),new T.ShaderMaterial({side:T.BackSide,uniforms:{},vertexShader:'varying vec3 dir;void main(){dir=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 dir;void main(){vec3 n=normalize(dir);float h=max(n.y,0.0);vec3 col=mix(vec3(.76,.85,.86),vec3(.20,.47,.68),pow(h,.55));float sun=pow(max(0.0,dot(n,normalize(vec3(-.55,.8,.35)))),500.0);gl_FragColor=vec4(col+vec3(5.0,4.1,2.6)*sun,1.0);}'}));scene.add(sky);const environmentScene=new T.Scene();environmentScene.add(sky.clone());const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(environmentScene,.025,.1,150).texture;pmrem.dispose();
const camera=new T.PerspectiveCamera(48,1,.1,200);let yaw=.25,pitch=.6,distance=innerWidth<600?48:39,viewMode='overview',rideTarget=null;const walker={x:-6,z:17,angle:Math.PI,look:0};const walkKeys=new Set(),viewFocus=new T.Vector3();
const land=new T.Group(),riverGroup=new T.Group(),pieces=new T.Group(),ridersGroup=new T.Group(),visitorsGroup=new T.Group();scene.add(land,riverGroup,pieces,ridersGroup,visitorsGroup);land.add(resortPromenade(()=>{renderer.shadowMap.needsUpdate=true;}));
const grass=scannedMaterial('leafy_grass',[1,1],'#a7b493');const ground=mesh(land,worldUV(new T.PlaneGeometry(180,180).rotateX(-Math.PI/2),.18),grass,0,-.32,0);const pathMaterial=scannedMaterial('concrete_pavement',[1,1],'#e7e1cb');loadLighting(renderer,scene,'park',()=>{scene.remove(sky);renderer.shadowMap.needsUpdate=true;});
for(let i=0;i<27;i++){const a=i*2.4,r=20+(i%4)*2;if(Math.sin(a)*r>19&&Math.abs(Math.cos(a)*r)<14)continue;const tree=palm();tree.position.set(Math.cos(a)*r,-.2,Math.sin(a)*r);tree.scale.setScalar(.8+(i%3)*.2);tree.rotation.y=i;land.add(tree);}for(let i=0;i<18;i++){const a=i*2.4;if(Math.sin(a)*20>18&&Math.abs(Math.cos(a)*22)<14)continue;const rock=mesh(land,new T.DodecahedronGeometry(1,1),'#889183',Math.cos(a)*22,.2,Math.sin(a)*20,1.2,.7,.9);rock.rotation.y=i;}
// Entrance promenade, food court paving, and loungers give visitors places to explore.
block(land,pathMaterial,3,-.19,14,19,.12,8);for(const x of [-3,11]){block(land,'#9b8971',x,1.8,18,.3,4,.3);}block(land,'#366d61',4,3.4,18,14,.8,.3);
const visitors=[];for(let i=0;i<12;i++){const g=makePerson(i);g.scale.setScalar(.95);g.traverse(o=>o.castShadow=false);visitorsGroup.add(g);visitors.push({g,t:i/12,speed:.18+(i%3)*.05});}
// Bank edges and the water share one closed curve. Arc-distance motion stays continuous after edits.
const waterMaterial=new T.MeshPhysicalMaterial({color:'#289cad',roughness:.16,metalness:.03,clearcoat:1,clearcoatRoughness:.1,envMapIntensity:1.3,transparent:true,opacity:.89,side:T.DoubleSide});waterMaterial.onBeforeCompile=s=>{s.uniforms.flowTime={value:0};waterMaterial.userData.shader=s;s.vertexShader='varying vec2 riverUv;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <uv_vertex>','#include <uv_vertex>\nriverUv=uv;');s.fragmentShader='uniform float flowTime;varying vec2 riverUv;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_begin>','#include <normal_fragment_begin>\nnormal=normalize(normal+vec3(sin(riverUv.x*5.0-flowTime*1.5)*.12,cos(riverUv.y*18.0+flowTime)*.08,0.0));');s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat ripple=pow(max(0.0,sin(riverUv.x*6.0-flowTime*1.1)*cos(riverUv.y*15.0+flowTime*.5)),12.0);diffuseColor.rgb+=vec3(ripple*.07);');};
const poolBedMaterial=new T.MeshStandardMaterial({color:'#d1ece4',roughness:.6,side:T.DoubleSide});poolBedMaterial.userData.shared=true;poolBedMaterial.onBeforeCompile=s=>{s.uniforms.poolTime={value:0};poolBedMaterial.userData.shader=s;s.vertexShader='varying vec3 poolP;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\npoolP=position;');s.fragmentShader='uniform float poolTime;varying vec3 poolP;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nvec2 tile=fract(poolP.xz*5.0);float grout=step(.035,min(tile.x,tile.y));diffuseColor.rgb*=mix(.82,1.0,grout);float wave=sin(poolP.x*8.0+sin(poolP.z*6.0+poolTime)) * sin(poolP.z*8.0+sin(poolP.x*5.0-poolTime*.7));diffuseColor.rgb+=vec3(pow(abs(wave),9.0)*.3);');};
const riders=[];let slides=[],riverWater=null;
function clearGroup(g){disposeModel(g);}
function buildRiver(){// Keep the shared water material alive when replacing its mesh.
 for(const child of [...riverGroup.children]){riverGroup.remove(child);child.disposeReflection?.();child.geometry?.dispose();if(child.material!==waterMaterial&&child.material!==pathMaterial&&child.material!==poolBedMaterial)child.material?.dispose();}
 const walkway=new T.Mesh(worldUV(ribbon(curve,WIDTH/2+1.6,-.24),.45),pathMaterial);walkway.receiveShadow=true;riverGroup.add(walkway);const bank=new T.Mesh(ribbon(curve,WIDTH/2+.3,-.18),new T.MeshStandardMaterial({color:'#cbbda3',side:T.DoubleSide,roughness:.7}));bank.receiveShadow=true;riverGroup.add(bank);
 const bed=new T.Mesh(ribbon(curve,WIDTH/2,-.16),poolBedMaterial);bed.receiveShadow=true;riverGroup.add(bed);riverWater=reflectiveWater(ribbon(curve,WIDTH/2),{sun:sun.position});riverWater.receiveShadow=true;riverGroup.add(riverWater);
 for(const side of [-1,1]){const ps=Array.from({length:161},(_,i)=>{const {p,n}=frame(curve,i/160);return p.addScaledVector(n,side*(WIDTH/2+.11)).add(new T.Vector3(0,.03,0));});mesh(riverGroup,new T.TubeGeometry(new T.CatmullRomCurve3(ps),180,.12,12,false),'#e9dfbe');}
 $('#riverStatus').textContent=Math.round(curve.getLength())+' meters of connected lazy river';buildPieces();}
function slideMesh(c,color,type){const g=new T.Group(),positions=[],indices=[],steps=72;for(let i=0;i<=steps;i++){const p=c.getPoint(i/steps),v=c.getTangent(i/steps),n=new T.Vector3(-v.z,0,v.x).normalize();for(let j=0;j<=8;j++){const a=j/8*Math.PI;const q=p.clone().addScaledVector(n,Math.cos(a)*(type==='raft'?.68:.42));q.y+=(1-Math.sin(a))*.32;positions.push(q.x,q.y,q.z);}if(i<steps)for(let j=0;j<8;j++){const k=i*9+j;indices.push(k,k+9,k+1,k+1,k+9,k+10);}}
 const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(positions,3));geom.setIndex(indices);geom.computeVertexNormals();mesh(g,geom,new T.MeshStandardMaterial({color,side:T.DoubleSide,roughness:.19,metalness:.02}));if(type==='tube')mesh(g,new T.TubeGeometry(c,80,.48,12,false),new T.MeshPhysicalMaterial({color:'#4a94ad',transparent:true,opacity:.32,roughness:.18,side:T.DoubleSide}));for(let i=0;i<5;i++){const p=c.getPoint(i/5);block(g,'#acbd8c',p.x,p.y/2-.1,p.z,.1,Math.max(.1,p.y),.1);}const top=c.getPoint(0);block(g,'#edce79',top.x,top.y-.15,top.z,1.1,.16,1.1);for(let i=0;i<12;i++)block(g,'#d6b56c',top.x,top.y*i/12,top.z+.53,.7,.05,.12);return g;}
function makeParkPiece(item,river=curve){let g,track=null;if(SLIDES.includes(item.type)){const c=slideCurve(river,item.t,item.type);g=slideMesh(c,item.type==='spiral'?'#d9794d':item.type==='wave'?'#d8b437':item.type==='speed'?'#468f87':'#4899b4',item.type);track=c;}else if(item.type==='bridge'){const {p,v}=frame(river,item.t);g=new T.Group();const width=WIDTH+.95;for(let j=0;j<13;j++)block(g,'#b59c70',0,.62,(j-6)*width/12,.95,.1,width/12*.88);for(const x of [-.49,.49]){block(g,'#e3ce9a',x,1.03,0,.055,.055,width);for(const z of [-width/2,0,width/2])block(g,'#bda77c',x,.82,z,.065,.65,.065);}for(const z of [-1,1]){const ramp=block(g,'#b59c70',0,.24,z*(width/2+.5),.95,.08,1.05);ramp.rotation.x=z*.65;}g.position.set(p.x,0,p.z);g.rotation.y=Math.atan2(-v.z,v.x);}else{g=ATTRACTIONS[item.type]?attraction(item.type):makeModel(item.type);g.position.set(item.x,0,item.z);g.rotation.y=item.rot||0;}return {g,track};}
function buildPieces(){riders.forEach(r=>{if(r.slide){r.t=r.slide.item.t;r.slide=null;window.SFX?.splash();}});clearGroup(pieces);slides=[];state.items.forEach((item,i)=>{const {g,track}=makeParkPiece(item);if(track)slides.push({curve:track,item});g.userData.index=i;g.traverse(o=>o.userData.index=i);pieces.add(g);});renderer.shadowMap.needsUpdate=true;renderPieces();}
function renderPieces(){$('#pieces').replaceChildren();state.items.forEach((it,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+'. '+names[it.type];$('#pieces').append(o)});selected=clamp(selected,0,Math.max(0,state.items.length-1));$('#pieces').value=selected;}
function makeRider(offset=0,slide=null){const g=new T.Group();mesh(g,new T.TorusGeometry(.27,.095,8,18),'#edbf57',0,.09,0).rotation.x=Math.PI/2;const person=makePerson();person.scale.setScalar(.36);person.position.y=.02;g.add(person);ridersGroup.add(g);const rider={g,t:offset,slide,progress:0};riders.push(rider);if(riders.length>20){const old=riders.shift();ridersGroup.remove(old.g);disposeModel(old.g);}return rider;}
function animateRider(r,dt){if(r.slide){r.progress+=dt/5;if(r.progress>=1){r.t=r.slide.item.t;r.slide=null;window.SFX?.splash();}else{const p=r.slide.curve.getPoint(r.progress),v=r.slide.curve.getTangent(r.progress);r.g.position.copy(p).add(new T.Vector3(0,.1,0));r.g.rotation.y=Math.atan2(v.x,v.z);return;}}r.t=(r.t+dt*.8/curve.getLength())%1;const {p,v}=frame(curve,r.t);r.g.position.copy(p).add(new T.Vector3(0,.06,0));r.g.rotation.y=Math.atan2(v.x,v.z);}
function resize(){const r=$('#parkViewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=viewMode==='overview'?(r.width<600?58:48):68;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('#parkViewport'));
let ghost=null,previewPoint=null;const previewCards=[];let thumbnailRenderer=null,lastThumb=0;let last=0,time=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(document.hidden)return;if(!paused){time+=dt;riverWater?.userData.tick(time);if(poolBedMaterial.userData.shader)poolBedMaterial.userData.shader.uniforms.poolTime.value=time;if(waterMaterial.userData.shader)waterMaterial.userData.shader.uniforms.flowTime.value=time;riders.forEach(r=>animateRider(r,dt));for(const g of pieces.children)animateAttraction(g,time);for(const visitor of visitors){visitor.t=(visitor.t+dt*visitor.speed/curve.getLength())%1;const {p,v,n}=frame(curve,visitor.t);visitor.g.position.copy(p.addScaledVector(n,-WIDTH/2-1));visitor.g.position.y=-.12;visitor.g.rotation.y=Math.atan2(v.x,v.z);const gait=visitor.g.userData.gait;if(gait){gait.legs.forEach((leg,i)=>leg.rotation.x=Math.sin(time*3+i*Math.PI)*.2);gait.arms.forEach((arm,i)=>arm.rotation.x=-Math.sin(time*3+i*Math.PI)*.2);}}}updateView(dt);scene.updateMatrixWorld();positionMarkers();if(ghost?.userData.track&&!paused){const track=ghost.userData.track,q=(time%5)/5;ghost.userData.rider.position.copy(track.getPoint(q)).add(new T.Vector3(0,.1,0));}const canvasRect=renderer.domElement.getBoundingClientRect();if(canvasRect.bottom>0&&canvasRect.top<innerHeight)renderer.render(scene,camera);animateCards(now);}
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);function point(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);return ray.ray.intersectPlane(plane,new T.Vector3());}
function nearest(p){let best=0,d=Infinity;for(let i=0;i<400;i++){const q=curve.getPointAt(i/400),n=q.distanceTo(p);if(n<d){d=n;best=i/400;}}return {t:best,d};}
function place(p,confirmed=false){if(draft){draft[bend]=[clamp(p.x,-20,20),clamp(p.z,-20,20)];preview();return;}if(!pending)return;if(!confirmed)clearPlacement();const type=pending.type,attachment=SLIDES.includes(type)||type==='bridge',near=nearest(p);if(attachment&&near.d>2.8){tell('Tap close to the river. The exit or bridge needs to connect to its banks.');return;}if(attachment&&state.items.some((other,i)=>{if(pending.moving&&i===selected)return false;if(!SLIDES.includes(other.type)&&other.type!=='bridge')return false;const gap=Math.abs(other.t-near.t);return Math.min(gap,1-gap)*curve.getLength()<(type==='spiral'||other.type==='spiral'?3.8:2.2);})){tell('Give this connection more space from the next slide or bridge.');return;}if(!attachment&&near.d<WIDTH/2+landRadius(type)){tell('This needs more dry space. Tap farther from the river.');return;}if(!attachment&&state.items.some((other,i)=>!(pending.moving&&i===selected)&&!SLIDES.includes(other.type)&&other.type!=='bridge'&&Math.hypot(p.x-other.x,p.z-other.z)<landRadius(type)+landRadius(other.type))){tell('Give this piece its own space. Tap another spot.');return;}const it={type,t:near.t,x:clamp(p.x,-20,20),z:clamp(p.z,-20,20),rot:pending.moving?(state.items[selected].rot||0):0};if(!confirmed){showPlacement(it,p);return;}clearPlacement();if(pending.moving){it.rot=state.items[selected].rot||0;state.items[selected]=it;}else{if(state.items.length>=90){tell('Your park has 90 pieces. Put one away to make room.');return;}state.items.push(it);selected=state.items.length-1;}pending=null;buildPieces();save();window.SFX?.snap();tell(attachment?'Connected! Try sending a rider down a slide.':'Placed. Select a piece below to move or turn it.');}
let down=null,pointers=new Map(),pinch=0;renderer.domElement.onpointerdown=e=>{renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);down={x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY,moved:false};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);down.moved=true;}};
renderer.domElement.onpointermove=e=>{if(!down||!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],n=Math.hypot(a[0]-b[0],a[1]-b[1]);distance=clamp(distance+(pinch-n)*.05,8,72);pinch=n;down.moved=true;return;}if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)down.moved=true;if(down.moved&&viewMode==='guest'){walker.angle-=(e.clientX-down.lx)*.006;walker.look=clamp(walker.look-(e.clientY-down.ly)*.004,-.6,.6);}else if(down.moved){yaw-=(e.clientX-down.lx)*.007;pitch=clamp(pitch+(e.clientY-down.ly)*.006,.25,1.4);}down.lx=e.clientX;down.ly=e.clientY;};
renderer.domElement.onpointerup=e=>{pointers.delete(e.pointerId);if(down&&!down.moved&&!pointers.size){const p=point(e);if(pending||draft){if(p)place(p);}else{const hit=ray.intersectObjects(pieces.children,true)[0];if(hit){selected=hit.object.userData.index;renderPieces();if(viewMode==='guest')$('#interact').click();else tell(names[state.items[selected].type]+' selected. Tap Play with selected attraction below.');}}}down=null;};renderer.domElement.onpointercancel=()=>{down=null;pointers.clear();};renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance+e.deltaY*.025,8,72)},{passive:false});
function markers(){const group=$('#routeMarkers');group.replaceChildren();const pts=draft||[];pts.forEach((p,i)=>{const b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-label','Select river bend '+(i+1));b.classList.toggle('selected',i===bend);b.onclick=()=>{bend=i;$('#bend').value=i;markers();};b.dataset.x=p[0];b.dataset.z=p[1];group.append(b);});if(care)for(const i of care.remaining){const {p}=frame(curve,i/6);const b=document.createElement('button');b.className='drain';b.textContent='♻';b.setAttribute('aria-label','Clear park filter '+(i+1));b.dataset.x=p.x;b.dataset.z=p.z;b.onclick=()=>cleanFilter(i);group.append(b);}}
function positionMarkers(){const rect=renderer.domElement.getBoundingClientRect();for(const b of $('#routeMarkers').children){const p=new T.Vector3(Number(b.dataset.x),.6,Number(b.dataset.z)).project(camera);b.style.left=(p.x+1)*rect.width/2+'px';b.style.top=(1-p.y)*rect.height/2+'px';b.hidden=Math.abs(p.x)>1||Math.abs(p.y)>1||p.z>1;}}
function preview(){const error=validateRoute(draft);$('#routeFeedback').textContent=error||'Connected loop looks good. Save to open the new route.';$('#applyRoute').disabled=!!error;$('#bend').replaceChildren();draft.forEach((_,i)=>{const o=document.createElement('option');o.value=i;o.textContent='Bend '+(i+1);$('#bend').append(o)});$('#bend').value=bend;if(!error){curve=curveFor(draft);riders.forEach(r=>r.slide=null);buildRiver();}markers();}
$('#edit').onclick=()=>{if(care){tell('Finish park care before building.');return;}clearPlacement();pending=null;draft=state.route.map(p=>[...p]);bend=0;$('#routeEditor').hidden=false;preview();tell('Select a bend. Tap the grass to move it, or use the direction buttons below.');};$('#bend').onchange=e=>{bend=Number(e.target.value);markers();};
for(const b of document.querySelectorAll('[data-nudge]'))b.onclick=()=>{const [x,z]=b.dataset.nudge.split(',').map(Number);draft[bend]=[clamp(draft[bend][0]+x*.65,-20,20),clamp(draft[bend][1]+z*.65,-20,20)];preview();};
$('#addBend').onclick=()=>{if(draft.length>=18){tell('18 bends is the limit for this park.');return;}const a=draft[bend],b=draft[(bend+1)%draft.length];draft.splice(bend+1,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);bend++;preview();};$('#removeBend').onclick=()=>{if(draft.length<=4){tell('Keep at least four bends for a loop.');return;}draft.splice(bend,1);bend=Math.min(bend,draft.length-1);preview();};
function endEdit(commit){if(commit){const err=validateRoute(draft);if(err){tell(err);return;}state.route=draft.map(p=>[...p]);markAdventure('design');save();}draft=null;curve=curveFor(state.route);riders.forEach(r=>r.slide=null);buildRiver();markers();$('#routeEditor').hidden=true;tell(commit?'River saved. Slides and bridges have followed the new route.':'Previous route restored.');}
$('#applyRoute').onclick=()=>endEdit(true);$('#cancelRoute').onclick=()=>endEdit(false);
for(const b of document.querySelectorAll('[data-add]'))b.onclick=()=>{if(draft||care){tell('Finish the river edit or park care first.');return;}clearPlacement();viewMode='overview';viewFocus.set(0,0,0);$('#walkPad').hidden=true;resize();pending={type:b.dataset.add};window.SFX?.tap();for(const card of previewCards)card.button.classList.toggle('chosen',card.type===pending.type);const spot=suggestSpot(pending.type);if(spot){place(spot);$('#parkViewport').scrollIntoView({behavior:'auto',block:'center'});}else tell('Choose a spot in your park. You can move another piece to make room.');};
$('#placePosition').onclick=()=>{if(!pending){tell('Choose a construction tool or Move selected piece first.');return;}if(SLIDES.includes(pending.type)||pending.type==='bridge'){const t=Number($('#riverPosition').value)/100;place(frame(curve,t).p);}else place(new T.Vector3(Number($('#landX').value)||0,0,Number($('#landZ').value)||0));};
$('#pieces').onchange=e=>selected=Number(e.target.value);$('#move').onclick=()=>{if(draft||care||!state.items[selected])return;clearPlacement();pending={type:state.items[selected].type,moving:true};tell('Tap a new place. Connected pieces must stay beside the river.');};$('#turn').onclick=()=>{const it=state.items[selected];if(!it||draft||care)return;if(SLIDES.includes(it.type)||it.type==='bridge'){tell('This piece turns automatically to match the river.');return;}it.rot=(it.rot||0)+Math.PI/4;buildPieces();save();};$('#remove').onclick=()=>{if(draft||care||!state.items.length)return;state.items.splice(selected,1);pending=null;riders.forEach(r=>r.slide=null);buildPieces();save();};
$('#quickRide').onclick=()=>$('#ride').click();
$('#ride').onclick=()=>{if(draft){tell('Save or cancel your route before riding.');return;}const selectedSlide=slides.find(s=>s.item===state.items[selected]);const slide=selectedSlide||slides[Math.floor(Math.random()*slides.length)]||null;rideTarget=makeRider(0,slide);viewMode='ride';$('#parkViewport').scrollIntoView({behavior:'auto',block:'center'});resize();markAdventure('ride');window.SFX?.whoosh();paused=false;$('#pause').textContent='Pause';tell(slide?'Down the slide and into the lazy river!':'Floating around your complete river loop.');};$('#pause').textContent=paused?'Resume':'Pause';$('#pause').onclick=()=>{$('#pause').textContent=(paused=!paused)?'Resume':'Pause';};$('#view').onclick=()=>{viewFocus.set(0,0,0);viewMode='overview';$('#walkPad').hidden=true;yaw=.25;pitch=.6;distance=innerWidth<600?48:39;resize();};$('#zoomIn').onclick=()=>distance=clamp(distance-3,8,72);$('#zoomOut').onclick=()=>distance=clamp(distance+3,8,72);$('#rotate').onclick=()=>yaw-=.4;
function sheet(html){$('#sheetBody').innerHTML=html;$('#sheet').showModal();}$('#closeSheet').onclick=()=>$('#sheet').close();function balance(){$('#balance').textContent=Wallet.get()+' bucks';}document.addEventListener('wallet',balance);
$('#bank').onclick=()=>{sheet('<div id="savingsGame"></div>');mountSavings($('#savingsGame'),Wallet,window.SFX);};
$('#help').onclick=()=>sheet('<h2>Connected creative play</h2><p>The river is a closed circuit. Slides empty into it, floaters follow its route, and bridges connect both banks. This is a simplified play simulation, not an engineering or swimming-safety model.</p><p>All construction is free. Park work pays 10 pretend bucks once per day, either after six filters are cleared or a three-order food shift is completed. Savings are shared with your aquarium and town. No penalty for taking a break.</p><p>Touch: tap a tool, then tap the world. Drag to orbit, and pinch to zoom. River bends also have numbered selectors and direction buttons.</p><p>Everything is saved in this browser on this device. No accounts or uploads.</p>');
$('#care').onclick=()=>{if(draft||pending){tell('Finish building before starting park care.');return;}if(care){tell('Tap the six gold filter markers around the river.');return;}if(!Wallet.canWork('park')){tell('Park care is finished for today. Enjoy building and riding!');return;}care={remaining:new Set([0,1,2,3,4,5]),started:Date.now()};markers();tell('Clear six filter baskets so the water can keep circulating.');};
async function cleanFilter(i){if(!care||!care.remaining.has(i))return;care.remaining.delete(i);window.SFX?.pop();markers();tell((6-care.remaining.size)+' of 6 filters cleared.');if(!care.remaining.size){const active=care;const finish=async()=>{if(care!==active)return;const paid=await Wallet.completeWork('park');care=null;markAdventure('care');if(paid)window.SFX?.cheer();markers();tell(paid?'You cleared every filter. 10 bucks earned! Open your piggy bank to save.':'Park care is already paid today. Thanks for keeping the water clear.');};const remaining=Math.max(0,12000-(Date.now()-care.started));if(remaining)tell('Filters clear. Checking the circulation...');setTimeout(finish,remaining);}}
addEventListener('keydown',e=>{if(e.key==='Escape'){clearPlacement();pending=null;tell('Placement canceled.');}});


function landRadius(type){return ({pool:4.2,bucket:3,mushroom:2.7,jets:2.7,icecream:2,burger:2,umbrella:2,palm:.7,tree:.7,bench:.8,flowers:.45})[type]||.7;}
function suggestSpot(type){if(SLIDES.includes(type)||type==='bridge'){for(let i=0;i<100;i++){const t=(i*.61803398875)%1;if(state.items.every(other=>{if(!SLIDES.includes(other.type)&&other.type!=='bridge')return true;const gap=Math.abs(other.t-t);return Math.min(gap,1-gap)*curve.getLength()>4.2;}))return frame(curve,t).p;}return null;}const candidates=[];for(let x=-16;x<=16;x+=2)for(let z=-16;z<=16;z+=2)candidates.push(new T.Vector3(x,0,z));candidates.sort((a,b)=>a.lengthSq()-b.lengthSq());return candidates.find(p=>nearest(p).d>WIDTH/2+landRadius(type)+.25&&state.items.every(other=>SLIDES.includes(other.type)||other.type==='bridge'||Math.hypot(p.x-other.x,p.z-other.z)>landRadius(type)+landRadius(other.type)+.3));}
$('#buildPark').onclick=()=>{document.querySelector('[aria-label="Construction tools"]').scrollIntoView({behavior:'auto',block:'start'});document.querySelector('[data-add]').focus({preventScroll:true});window.SFX?.tap();};

function clearPlacement(){if(ghost){scene.remove(ghost);disposeModel(ghost);ghost=null;}previewPoint=null;$('#placementPreview').hidden=true;}
function showPlacement(item,p){clearPlacement();const result=makeParkPiece(item);ghost=result.g;ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.55;o.material.depthWrite=false;}});if(result.track){const r=new T.Group();mesh(r,new T.TorusGeometry(.27,.095,8,18),'#edbf57',0,.09,0).rotation.x=Math.PI/2;const person=makePerson();person.scale.setScalar(.36);r.add(person);ghost.add(r);ghost.userData.rider=r;ghost.userData.track=result.track;}scene.add(ghost);previewPoint=p.clone();viewFocus.copy(p);pitch=.6;distance=24;$('#previewName').textContent=names[item.type]+' preview';$('#placementPreview').hidden=false;tell('👍 Like this spot? Tap the big green button! Tap the ground to move it.');}
$('#confirmPlacement').onclick=()=>{if(previewPoint)place(previewPoint.clone(),true);};$('#cancelPlacement').onclick=()=>{clearPlacement();pending=null;tell('Preview canceled. Nothing added.');};
function prepareCards(){
 try{thumbnailRenderer=new T.WebGLRenderer({alpha:true,antialias:true});thumbnailRenderer.setSize(240,180);thumbnailRenderer.setPixelRatio(1);thumbnailRenderer.outputColorSpace=T.SRGBColorSpace;thumbnailRenderer.toneMapping=T.ACESFilmicToneMapping;thumbnailRenderer.toneMappingExposure=1.25;}catch{return;}
 const demo=curveFor(START_ROUTE);
 for(const button of document.querySelectorAll('[data-add]')){
  const type=button.dataset.add,label=button.textContent;button.setAttribute('aria-label',label);button.classList.add('preview-card');button.replaceChildren();const badge=document.createElement('span');badge.className='add-badge';badge.textContent='＋';badge.setAttribute('aria-hidden','true');button.append(badge);
  const canvas=document.createElement('canvas');canvas.width=240;canvas.height=180;canvas.setAttribute('aria-hidden','true');const name=document.createElement('strong');name.textContent=names[type];const sub=document.createElement('small');sub.textContent=SLIDES.includes(type)?'Watch it ride · FREE':'Explore in 3D · FREE';button.append(canvas,name,sub);
  const display=new T.Scene();display.add(new T.HemisphereLight('#ffffff','#7a9465',3));const light=new T.DirectionalLight('#fff4d5',3);light.position.set(-4,8,7);display.add(light);
  const item={type,t:0,x:0,z:0,rot:0},result=makeParkPiece(item,demo),root=new T.Group();root.add(result.g);
  if(result.track){const end=result.track.getPoint(1);mesh(root,new T.CylinderGeometry(.8,.9,.12,24),'#69cabc',end.x,end.y-.09,end.z);}
  const box=new T.Box3().setFromObject(root),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());root.position.sub(center);display.add(root);
  let rider=null;if(result.track){rider=new T.Group();mesh(rider,new T.TorusGeometry(.23,.08,8,14),'#e8b84f',0,0,0).rotation.x=Math.PI/2;const person=makePerson();person.scale.setScalar(.32);rider.add(person);root.add(rider);}
  const camera=new T.PerspectiveCamera(36,240/180,.1,60),dist=Math.max(size.x,size.y*1.1,size.z)*1.7;
  previewCards.push({button,type,canvas,ctx:canvas.getContext('2d'),display,root,rider,track:result.track,camera,dist,visible:true});
 }
 if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries){const card=previewCards.find(c=>c.button===entry.target);if(card)card.visible=entry.isIntersecting;}});previewCards.forEach(c=>observer.observe(c.button));}
 animateCards(1000,true);
}
function animateCards(now,force=false){if(!thumbnailRenderer||(!force&&now-lastThumb<100))return;lastThumb=now;for(const c of previewCards){if(!force&&!c.visible)continue;const a=paused?1.7:1.7+Math.sin(now*.00035)*.55;c.camera.position.set(Math.sin(a)*c.dist,c.dist*.55,Math.cos(a)*c.dist);c.camera.lookAt(0,0,0);if(!paused)animateAttraction(c.root.children[0],now/1000);if(c.rider){const t=paused?.35:(now*.00018)%1;c.rider.position.copy(c.track.getPoint(t)).add(new T.Vector3(0,.1,0));const v=c.track.getTangent(t);c.rider.rotation.y=Math.atan2(v.x,v.z);}thumbnailRenderer.render(c.display,c.camera);c.ctx.clearRect(0,0,240,180);c.ctx.drawImage(thumbnailRenderer.domElement,0,0);}}

function markAdventure(kind){state.adventures[kind]=true;save();$('#parkDay').textContent=Object.keys(state.adventures).length+' park adventures completed';}
function bridgeHeight(x,z){for(const item of state.items){if(item.type!=='bridge')continue;const {p,v,n}=frame(curve,item.t),delta=new T.Vector3(x,0,z).sub(p);const along=Math.abs(delta.dot(v)),across=Math.abs(delta.dot(n));if(along<.48&&across<WIDTH/2+1.35)return .62*Math.min(1,Math.max(0,(WIDTH/2+1.35-across)/.95));}return null;}
function updateView(dt){if(viewMode==='guest'){const turn=(walkKeys.has('left')?1:0)-(walkKeys.has('right')?1:0),step=(walkKeys.has('forward')?1:0)-(walkKeys.has('back')?1:0);walker.angle+=turn*dt*1.8;const x=walker.x+Math.sin(walker.angle)*step*dt*3.2,z=walker.z+Math.cos(walker.angle)*step*dt*3.2;const bridge=bridgeHeight(x,z);if(step&&(bridge!==null||nearest(new T.Vector3(x,0,z)).d>WIDTH/2+.25)&&!state.items.some(it=>['icecream','burger'].includes(it.type)&&Math.abs(x-it.x)<2&&Math.abs(z-it.z)<1.5)){walker.x=clamp(x,-23,23);walker.z=clamp(z,-23,23);}const height=1.65+(bridgeHeight(walker.x,walker.z)||0);camera.position.set(walker.x,height,walker.z);camera.lookAt(walker.x+Math.sin(walker.angle)*8,height+walker.look*8,walker.z+Math.cos(walker.angle)*8);}else if(viewMode==='ride'&&rideTarget){const r=rideTarget,pos=r.g.position.clone().add(new T.Vector3(0,.7,0));const v=r.slide?r.slide.curve.getTangent(r.progress):frame(curve,r.t).v;camera.position.lerp(pos,.15);camera.lookAt(pos.clone().addScaledVector(v,5).add(new T.Vector3(0,-.1,0)));}else{camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.position.add(viewFocus);camera.lookAt(viewFocus.clone().add(new T.Vector3(0,1,0)));}}
$('#guestView').onclick=()=>{viewMode=viewMode==='guest'?'overview':'guest';$('#walkPad').hidden=viewMode!=='guest';resize();tell(viewMode==='guest'?'Welcome inside. Use the arrows to walk, and drag to look around.':'Back to the builder view.');};
const directions={ArrowUp:'forward',w:'forward',ArrowDown:'back',s:'back',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};addEventListener('keydown',e=>{if(viewMode==='guest'&&directions[e.key]&&!e.target.matches('input,select,textarea,[contenteditable]')&&!$('#sheet').open){e.preventDefault();walkKeys.add(directions[e.key]);}});addEventListener('keyup',e=>walkKeys.delete(directions[e.key]));addEventListener('blur',()=>walkKeys.clear());document.addEventListener('visibilitychange',()=>walkKeys.clear());for(const b of document.querySelectorAll('[data-walk]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);walkKeys.add(b.dataset.walk);};b.onpointerup=b.onpointercancel=()=>walkKeys.delete(b.dataset.walk);}
$('#interact').onclick=()=>{if(care||draft){tell('Finish park care or the river edit first.');return;}const item=state.items[selected];if(!item)return;if(SLIDES.includes(item.type)){$('#ride').click();return;}if(item.type==='icecream'||item.type==='burger'){serveStand(item.type);return;}const g=pieces.children[selected];if(['bucket','mushroom','jets','pool'].includes(item.type)){g.userData.offset=13-time;markAdventure('splash');window.SFX?.splash();tell(item.type==='bucket'?'Watch the bucket tip! More water will fill it for the next splash.':'Splash time! Your attraction is open.');viewFocus.copy(g.position);yaw=.5;pitch=.35;viewMode='overview';$('#walkPad').hidden=true;distance=13;resize();return;}tell('Select a slide, splash attraction, or food stand to play with it.');};
function serveStand(type){const orders=type==='burger'?['🍔','🥤','🍔']:['🍦','🍧','🍦'];let count=0,busy=false,lastServe=0;sheet('<h2>Serve your visitors</h2><p>Match each visitor’s order. Three happy visitors complete a shift.</p><div class="customer-order" id="order"></div><div class="food-choices" id="foodChoices"></div><p id="serviceStatus" role="status"></p>');const choices=type==='burger'?['🍔','🥤','🍟']:['🍦','🍧','🥤'];const paint=()=>{$('#order').textContent='🧒  '+orders[count];$('#serviceStatus').textContent=count+' of 3 orders served';};choices.forEach(food=>{const b=document.createElement('button');b.textContent=food;b.setAttribute('aria-label','Serve '+food);b.onclick=async()=>{if(busy)return;if(Date.now()-lastServe<2500){$('#serviceStatus').textContent='Let this visitor collect their food first.';return;}if(food!==orders[count]){$('#serviceStatus').textContent='Look at the order bubble and try that food.';window.SFX?.tap();return;}lastServe=Date.now();count++;window.SFX?.pop();if(count<3){paint();return;}busy=true;markAdventure('serve');const paid=await Wallet.completeWork('park');$('#order').textContent='🧒 😊 🧒 😊 🧒 😊';$('#serviceStatus').textContent=paid?'Three orders matched. 10 bucks earned! Save your paycheck in the piggy.':'Three happy visitors! Park work is already paid today. You can keep playing.';if(paid)window.SFX?.cheer();};$('#foodChoices').append(b);});paint();}
buildRiver();for(let i=0;i<5;i++)makeRider(i/5);balance();resize();save();$('#parkDay').textContent=Object.keys(state.adventures).length+' park adventures completed';prepareCards();requestAnimationFrame(animate);

$('#cabanaView').onclick=()=>{if(draft||pending||care){tell('Finish your current activity before visiting the cabanas.');return;}viewMode='overview';viewFocus.set(0,0,23);yaw=.25;pitch=.32;distance=11;$('#walkPad').hidden=true;$('#parkViewport').scrollIntoView({behavior:'auto',block:'center'});resize();tell('A quiet place to relax. Drag to look around the cabanas.');};
