import * as T from './vendor/three.module.js';
import {makeModel,makePerson,mesh,orb,block,disposeModel} from './chilltopia-models.js?v=20260907-expansion';
import {WIDTH,START_ROUTE,curveFor,frame,validateRoute,ribbon,slideCurve} from './park-geometry.js?v=20260907-expansion';
const $=s=>document.querySelector(s),KEY='cb:waterpark:v1',clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
window.SFX?.bind($('#parkSound'));window.SFX?.ambience('water');
const TYPES=['straight','wave','spiral','bridge','tree','flowers','bench'],SLIDES=['straight','wave','spiral'];
const names={straight:'Straight slide',wave:'Wavy slide',spiral:'Spiral slide',bridge:'Bridge',tree:'Cloud tree',flowers:'Flower patch',bench:'Chill bench'};
const fresh=()=>({v:1,route:START_ROUTE.map(p=>[...p]),items:[{type:'wave',t:.08},{type:'spiral',t:.43},{type:'bridge',t:.77},...Array.from({length:9},(_,i)=>({type:'tree',x:Math.cos(i*2.4)*9,z:Math.sin(i*2.4)*8,rot:0})),{type:'flowers',x:0,z:1},{type:'bench',x:1,z:0}]});
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.v!==1||validateRoute(s.route)||!Array.isArray(s.items))return fresh();s.items=s.items.filter(i=>TYPES.includes(i.type)).slice(0,60).map(i=>({...i,t:clamp(Number(i.t)||0,0,.99999),x:clamp(Number(i.x)||0,-10,10),z:clamp(Number(i.z)||0,-10,10),rot:Number(i.rot)||0}));return s;}catch{return fresh();}}
let state=load(),curve=curveFor(state.route),draft=null,bend=0,pending=null,selected=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,care=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='Saved on this device';}catch{$('#saveStatus').textContent='Could not save. Keep this tab open.';}}
const tell=t=>{$('#hint').textContent=t;};
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{$('#loading').innerHTML='3D is unavailable. <a href="classic.html">Open Classic</a>';throw Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;$('#parkViewport').append(renderer.domElement);$('#loading').remove();
const scene=new T.Scene();scene.background=new T.Color('#c9e3bd');scene.fog=new T.Fog('#c9e3bd',45,100);scene.add(new T.HemisphereLight('#ffffe4','#649770',3));const sun=new T.DirectionalLight('#fff4d8',3);sun.position.set(-5,12,8);scene.add(sun);
const camera=new T.PerspectiveCamera(42,1,.1,120);let yaw=.25,pitch=.77,distance=innerWidth<600?40:33;
const land=new T.Group(),riverGroup=new T.Group(),pieces=new T.Group(),ridersGroup=new T.Group();scene.add(land,riverGroup,pieces,ridersGroup);
block(land,'#718e60',0,-.65,0,24,.6,24);block(land,'#a8c684',0,-.3,0,23.8,.14,23.8);const ground=mesh(land,new T.PlaneGeometry(200,200),'#bdd5a8',0,-1,0);ground.rotation.x=-Math.PI/2;
// Bank edges and the water share one closed curve. Arc-distance motion stays continuous after edits.
const waterMaterial=new T.MeshStandardMaterial({color:'#47c5bc',roughness:.3,metalness:.12,side:T.DoubleSide});waterMaterial.onBeforeCompile=s=>{s.uniforms.flowTime={value:0};waterMaterial.userData.shader=s;s.vertexShader='varying vec2 riverUv;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <uv_vertex>','#include <uv_vertex>\nriverUv=uv;');s.fragmentShader='uniform float flowTime;varying vec2 riverUv;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat rip=pow(max(0.0,sin(riverUv.x*3.0-flowTime*2.0+sin(riverUv.y*14.0))),14.0);diffuseColor.rgb+=vec3(rip*.18);');};
const riders=[];let slides=[];
function clearGroup(g){disposeModel(g);}
function buildRiver(){// Keep the shared water material alive when replacing its mesh.
 for(const child of [...riverGroup.children]){riverGroup.remove(child);child.geometry?.dispose();if(child.material!==waterMaterial)child.material?.dispose();}
 const bank=new T.Mesh(ribbon(curve,WIDTH/2+.34,-.1),new T.MeshStandardMaterial({color:'#e5d7ae',side:T.DoubleSide}));riverGroup.add(bank);
 const water=new T.Mesh(ribbon(curve,WIDTH/2),waterMaterial);riverGroup.add(water);
 for(const side of [-1,1]){const ps=Array.from({length:161},(_,i)=>{const {p,n}=frame(curve,i/160);return p.addScaledVector(n,side*(WIDTH/2+.11)).add(new T.Vector3(0,.03,0));});mesh(riverGroup,new T.TubeGeometry(new T.CatmullRomCurve3(ps),180,.12,6,false),'#e9dfbe');}
 $('#riverStatus').textContent=Math.round(curve.getLength())+' meters of connected lazy river';buildPieces();}
function slideMesh(c,color){const g=new T.Group(),positions=[],indices=[],steps=72;for(let i=0;i<=steps;i++){const p=c.getPoint(i/steps),v=c.getTangent(i/steps),n=new T.Vector3(-v.z,0,v.x).normalize();for(let j=0;j<=8;j++){const a=j/8*Math.PI;const q=p.clone().addScaledVector(n,Math.cos(a)*.36);q.y+=(1-Math.sin(a))*.32;positions.push(q.x,q.y,q.z);}if(i<steps)for(let j=0;j<8;j++){const k=i*9+j;indices.push(k,k+9,k+1,k+1,k+9,k+10);}}
 const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(positions,3));geom.setIndex(indices);geom.computeVertexNormals();mesh(g,geom,new T.MeshStandardMaterial({color,side:T.DoubleSide,roughness:.35}));for(let i=0;i<5;i++){const p=c.getPoint(i/5);block(g,'#acbd8c',p.x,p.y/2-.1,p.z,.1,Math.max(.1,p.y),.1);}const top=c.getPoint(0);block(g,'#edce79',top.x,top.y-.15,top.z,1.1,.16,1.1);for(let i=0;i<12;i++)block(g,'#d6b56c',top.x,top.y*i/12,top.z+.53,.7,.05,.12);return g;}
function makeParkPiece(item,river=curve){let g,track=null;if(SLIDES.includes(item.type)){const c=slideCurve(river,item.t,item.type);g=slideMesh(c,item.type==='spiral'?'#e49b6e':item.type==='wave'?'#ead366':'#7eabb5');track=c;}else if(item.type==='bridge'){const {p,v}=frame(river,item.t);g=new T.Group();const width=WIDTH+.95;for(let j=0;j<13;j++)block(g,'#b59c70',0,.62,(j-6)*width/12,.95,.1,width/12*.88);for(const x of [-.49,.49]){block(g,'#e3ce9a',x,1.03,0,.055,.055,width);for(const z of [-width/2,0,width/2])block(g,'#bda77c',x,.82,z,.065,.65,.065);}for(const z of [-1,1]){const ramp=block(g,'#b59c70',0,.24,z*(width/2+.5),.95,.08,1.05);ramp.rotation.x=z*.65;}g.position.set(p.x,0,p.z);g.rotation.y=Math.atan2(-v.z,v.x);}else{g=makeModel(item.type);g.position.set(item.x,0,item.z);g.rotation.y=item.rot||0;}return {g,track};}
function buildPieces(){riders.forEach(r=>{if(r.slide){r.t=r.slide.item.t;r.slide=null;window.SFX?.splash();}});clearGroup(pieces);slides=[];state.items.forEach((item,i)=>{const {g,track}=makeParkPiece(item);if(track)slides.push({curve:track,item});g.userData.index=i;g.traverse(o=>o.userData.index=i);pieces.add(g);});renderPieces();}
function renderPieces(){$('#pieces').replaceChildren();state.items.forEach((it,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+'. '+names[it.type];$('#pieces').append(o)});selected=clamp(selected,0,Math.max(0,state.items.length-1));$('#pieces').value=selected;}
function makeRider(offset=0,slide=null){const g=new T.Group();mesh(g,new T.TorusGeometry(.27,.095,8,18),'#edbf57',0,.09,0).rotation.x=Math.PI/2;const person=makePerson();person.scale.setScalar(.36);person.position.y=.02;g.add(person);ridersGroup.add(g);const rider={g,t:offset,slide,progress:0};riders.push(rider);if(riders.length>12){const old=riders.shift();ridersGroup.remove(old.g);disposeModel(old.g);}return rider;}
function animateRider(r,dt){if(r.slide){r.progress+=dt/5;if(r.progress>=1){r.t=r.slide.item.t;r.slide=null;window.SFX?.splash();}else{const p=r.slide.curve.getPoint(r.progress),v=r.slide.curve.getTangent(r.progress);r.g.position.copy(p).add(new T.Vector3(0,.1,0));r.g.rotation.y=Math.atan2(v.x,v.z);return;}}r.t=(r.t+dt*.8/curve.getLength())%1;const {p,v}=frame(curve,r.t);r.g.position.copy(p).add(new T.Vector3(0,.06,0));r.g.rotation.y=Math.atan2(v.x,v.z);}
function resize(){const r=$('#parkViewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=r.width<600?52:42;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('#parkViewport'));
let ghost=null,previewPoint=null;const previewCards=[];let thumbnailRenderer=null,lastThumb=0;let last=0,time=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(document.hidden)return;if(!paused){time+=dt;if(waterMaterial.userData.shader)waterMaterial.userData.shader.uniforms.flowTime.value=time;riders.forEach(r=>animateRider(r,dt));}camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,.2,0);scene.updateMatrixWorld();positionMarkers();if(ghost?.userData.track&&!paused){const track=ghost.userData.track,q=(time%5)/5;ghost.userData.rider.position.copy(track.getPoint(q)).add(new T.Vector3(0,.1,0));}const canvasRect=renderer.domElement.getBoundingClientRect();if(canvasRect.bottom>0&&canvasRect.top<innerHeight)renderer.render(scene,camera);animateCards(now);}
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);function point(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);return ray.ray.intersectPlane(plane,new T.Vector3());}
function nearest(p){let best=0,d=Infinity;for(let i=0;i<400;i++){const q=curve.getPointAt(i/400),n=q.distanceTo(p);if(n<d){d=n;best=i/400;}}return {t:best,d};}
function place(p,confirmed=false){if(draft){draft[bend]=[clamp(p.x,-10,10),clamp(p.z,-10,10)];preview();return;}if(!pending)return;if(!confirmed)clearPlacement();const type=pending.type,attachment=SLIDES.includes(type)||type==='bridge',near=nearest(p);if(attachment&&near.d>2.8){tell('Tap close to the river. The exit or bridge needs to connect to its banks.');return;}if(attachment&&state.items.some((other,i)=>{if(pending.moving&&i===selected)return false;if(!SLIDES.includes(other.type)&&other.type!=='bridge')return false;const gap=Math.abs(other.t-near.t);return Math.min(gap,1-gap)*curve.getLength()<(type==='spiral'||other.type==='spiral'?3.8:2.2);})){tell('Give this connection more space from the next slide or bridge.');return;}if(!attachment&&near.d<WIDTH/2+.6){tell('Plant and decorate on the grass, outside the water.');return;}const it={type,t:near.t,x:clamp(p.x,-10,10),z:clamp(p.z,-10,10),rot:pending.moving?(state.items[selected].rot||0):0};if(!confirmed){showPlacement(it,p);return;}clearPlacement();if(pending.moving){it.rot=state.items[selected].rot||0;state.items[selected]=it;}else{if(state.items.length>=60){tell('Your park has 60 pieces. Put one away to make room.');return;}state.items.push(it);selected=state.items.length-1;}pending=null;buildPieces();save();window.SFX?.snap();tell(attachment?'Connected! Try sending a rider down a slide.':'Placed. Select a piece below to move or turn it.');}
let down=null,pointers=new Map(),pinch=0;renderer.domElement.onpointerdown=e=>{renderer.domElement.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);down={x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY,moved:false};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a[0]-b[0],a[1]-b[1]);down.moved=true;}};
renderer.domElement.onpointermove=e=>{if(!down||!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const [a,b]=[...pointers.values()],n=Math.hypot(a[0]-b[0],a[1]-b[1]);distance=clamp(distance+(pinch-n)*.05,12,55);pinch=n;down.moved=true;return;}if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)down.moved=true;if(down.moved){yaw-=(e.clientX-down.lx)*.007;pitch=clamp(pitch+(e.clientY-down.ly)*.006,.25,1.4);}down.lx=e.clientX;down.ly=e.clientY;};
renderer.domElement.onpointerup=e=>{pointers.delete(e.pointerId);if(down&&!down.moved&&!pointers.size){const p=point(e);if(p){if(pending||draft)place(p);else{const hit=ray.intersectObjects(pieces.children,true)[0];if(hit){selected=hit.object.userData.index;renderPieces();tell(names[state.items[selected].type]+' selected. Use Move or Put away below.');}}}}down=null;};renderer.domElement.onpointercancel=()=>{down=null;pointers.clear();};renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=clamp(distance+e.deltaY*.025,12,55)},{passive:false});
function markers(){const group=$('#routeMarkers');group.replaceChildren();const pts=draft||[];pts.forEach((p,i)=>{const b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-label','Select river bend '+(i+1));b.classList.toggle('selected',i===bend);b.onclick=()=>{bend=i;$('#bend').value=i;markers();};b.dataset.x=p[0];b.dataset.z=p[1];group.append(b);});if(care)for(const i of care.remaining){const {p}=frame(curve,i/6);const b=document.createElement('button');b.className='drain';b.textContent='♻';b.setAttribute('aria-label','Clear park filter '+(i+1));b.dataset.x=p.x;b.dataset.z=p.z;b.onclick=()=>cleanFilter(i);group.append(b);}}
function positionMarkers(){const rect=renderer.domElement.getBoundingClientRect();for(const b of $('#routeMarkers').children){const p=new T.Vector3(Number(b.dataset.x),.6,Number(b.dataset.z)).project(camera);b.style.left=(p.x+1)*rect.width/2+'px';b.style.top=(1-p.y)*rect.height/2+'px';b.hidden=Math.abs(p.x)>1||Math.abs(p.y)>1||p.z>1;}}
function preview(){const error=validateRoute(draft);$('#routeFeedback').textContent=error||'Connected loop looks good. Save to open the new route.';$('#applyRoute').disabled=!!error;$('#bend').replaceChildren();draft.forEach((_,i)=>{const o=document.createElement('option');o.value=i;o.textContent='Bend '+(i+1);$('#bend').append(o)});$('#bend').value=bend;if(!error){curve=curveFor(draft);riders.forEach(r=>r.slide=null);buildRiver();}markers();}
$('#edit').onclick=()=>{if(care){tell('Finish park care before building.');return;}clearPlacement();pending=null;draft=state.route.map(p=>[...p]);bend=0;$('#routeEditor').hidden=false;preview();tell('Select a bend. Tap the grass to move it, or use the direction buttons below.');};$('#bend').onchange=e=>{bend=Number(e.target.value);markers();};
for(const b of document.querySelectorAll('[data-nudge]'))b.onclick=()=>{const [x,z]=b.dataset.nudge.split(',').map(Number);draft[bend]=[clamp(draft[bend][0]+x*.65,-10,10),clamp(draft[bend][1]+z*.65,-10,10)];preview();};
$('#addBend').onclick=()=>{if(draft.length>=18){tell('18 bends is the limit for this park.');return;}const a=draft[bend],b=draft[(bend+1)%draft.length];draft.splice(bend+1,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);bend++;preview();};$('#removeBend').onclick=()=>{if(draft.length<=4){tell('Keep at least four bends for a loop.');return;}draft.splice(bend,1);bend=Math.min(bend,draft.length-1);preview();};
function endEdit(commit){if(commit){const err=validateRoute(draft);if(err){tell(err);return;}state.route=draft.map(p=>[...p]);save();}draft=null;curve=curveFor(state.route);riders.forEach(r=>r.slide=null);buildRiver();markers();$('#routeEditor').hidden=true;tell(commit?'River saved. Slides and bridges have followed the new route.':'Previous route restored.');}
$('#applyRoute').onclick=()=>endEdit(true);$('#cancelRoute').onclick=()=>endEdit(false);
for(const b of document.querySelectorAll('[data-add]'))b.onclick=()=>{if(draft||care){tell('Finish the river edit or park care first.');return;}clearPlacement();pending={type:b.dataset.add};window.SFX?.tap();for(const card of previewCards)card.button.classList.toggle('chosen',card.type===pending.type);tell(SLIDES.includes(pending.type)||pending.type==='bridge'?'Tap beside the river to connect your '+names[pending.type].toLowerCase()+'.':'Tap the grass to place your '+names[pending.type].toLowerCase()+'.');};
$('#placePosition').onclick=()=>{if(!pending){tell('Choose a construction tool or Move selected piece first.');return;}if(SLIDES.includes(pending.type)||pending.type==='bridge'){const t=Number($('#riverPosition').value)/100;place(frame(curve,t).p);}else place(new T.Vector3(Number($('#landX').value)||0,0,Number($('#landZ').value)||0));};
$('#pieces').onchange=e=>selected=Number(e.target.value);$('#move').onclick=()=>{if(draft||care||!state.items[selected])return;clearPlacement();pending={type:state.items[selected].type,moving:true};tell('Tap a new place. Connected pieces must stay beside the river.');};$('#turn').onclick=()=>{const it=state.items[selected];if(!it||draft||care)return;if(SLIDES.includes(it.type)||it.type==='bridge'){tell('This piece turns automatically to match the river.');return;}it.rot=(it.rot||0)+Math.PI/4;buildPieces();save();};$('#remove').onclick=()=>{if(draft||care||!state.items.length)return;state.items.splice(selected,1);pending=null;riders.forEach(r=>r.slide=null);buildPieces();save();};
$('#ride').onclick=()=>{if(draft){tell('Save or cancel your route before riding.');return;}const selectedSlide=slides.find(s=>s.item===state.items[selected]);const slide=selectedSlide||slides[Math.floor(Math.random()*slides.length)]||null;makeRider(0,slide);window.SFX?.whoosh();paused=false;$('#pause').textContent='Pause';tell(slide?'Down the slide and into the lazy river!':'Floating around your complete river loop.');};$('#pause').textContent=paused?'Resume':'Pause';$('#pause').onclick=()=>{$('#pause').textContent=(paused=!paused)?'Resume':'Pause';};$('#view').onclick=()=>{yaw=.25;pitch=.77;distance=innerWidth<600?40:33;};$('#zoomIn').onclick=()=>distance=clamp(distance-3,12,55);$('#zoomOut').onclick=()=>distance=clamp(distance+3,12,55);$('#rotate').onclick=()=>yaw-=.4;
function sheet(html){$('#sheetBody').innerHTML=html;$('#sheet').showModal();}$('#closeSheet').onclick=()=>$('#sheet').close();function balance(){$('#balance').textContent=Wallet.get()+' bucks';}document.addEventListener('wallet',balance);
$('#bank').onclick=()=>{sheet('<h2>Your piggy bank</h2><p id="parkSavings"></p><div class="piggy">🐷<small>Drag your paycheck here, or tap its Deposit button</small></div><div id="parkBills"></div>');const show=()=>{$('#parkSavings').textContent=Wallet.get()+' bucks saved';$('#parkBills').replaceChildren();for(const [kind,n] of Object.entries(Wallet.bills())){if(!n||!Wallet.BILLS[kind])continue;const b=document.createElement('button');b.className='wide-button bill';b.textContent='Deposit '+Wallet.BILLS[kind].v+' bucks ('+n+' waiting)';b.onclick=()=>{Wallet.depositBill(kind);window.SFX?.chaChing();show();};b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);let moved=false;const x=e.clientX,y=e.clientY;const move=ev=>{moved ||= Math.hypot(ev.clientX-x,ev.clientY-y)>8;if(moved)b.style.translate=(ev.clientX-x)+'px '+(ev.clientY-y)+'px';};const up=ev=>{b.removeEventListener('pointermove',move);b.removeEventListener('pointerup',up);b.removeEventListener('pointercancel',up);b.style.translate='';if(moved){const r=$('#sheet .piggy').getBoundingClientRect();if(ev.type==='pointerup'&&ev.clientX>=r.left&&ev.clientX<=r.right&&ev.clientY>=r.top&&ev.clientY<=r.bottom){Wallet.depositBill(kind);window.SFX?.chaChing();show();}b.onclick=ev=>ev.preventDefault();setTimeout(()=>{b.onclick=()=>{Wallet.depositBill(kind);window.SFX?.chaChing();show();};},0);}};b.addEventListener('pointermove',move);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);};$('#parkBills').append(b);}if(!$('#parkBills').children.length)$('#parkBills').textContent='No bills waiting. Park care earns a paycheck.';};show();};
$('#help').onclick=()=>sheet('<h2>Connected creative play</h2><p>The river is a closed circuit. Slides empty into it, floaters follow its route, and bridges connect both banks. This is a simplified play simulation, not an engineering or swimming-safety model.</p><p>All construction is free. Park care pays 10 pretend bucks once per day, after six filters are cleared. Savings are shared with your aquarium and town. No penalty for taking a break.</p><p>Touch: tap a tool, then tap the world. Drag to orbit, and pinch to zoom. River bends also have numbered selectors and direction buttons.</p><p>Everything is saved in this browser on this device. No accounts or uploads.</p>');
$('#care').onclick=()=>{if(draft||pending){tell('Finish building before starting park care.');return;}if(care){tell('Tap the six gold filter markers around the river.');return;}if(!Wallet.canWork('park')){tell('Park care is finished for today. Enjoy building and riding!');return;}care={remaining:new Set([0,1,2,3,4,5]),started:Date.now()};markers();tell('Clear six filter baskets so the water can keep circulating.');};
async function cleanFilter(i){if(!care||!care.remaining.has(i))return;care.remaining.delete(i);window.SFX?.pop();markers();tell((6-care.remaining.size)+' of 6 filters cleared.');if(!care.remaining.size){const active=care;const finish=async()=>{if(care!==active)return;const paid=await Wallet.completeWork('park');care=null;if(paid)window.SFX?.cheer();markers();tell(paid?'You cleared every filter. 10 bucks earned! Open your piggy bank to save.':'Park care is already paid today. Thanks for keeping the water clear.');};const remaining=Math.max(0,12000-(Date.now()-care.started));if(remaining)tell('Filters clear. Checking the circulation...');setTimeout(finish,remaining);}}
addEventListener('keydown',e=>{if(e.key==='Escape'){clearPlacement();pending=null;tell('Placement canceled.');}});

function clearPlacement(){if(ghost){scene.remove(ghost);disposeModel(ghost);ghost=null;}previewPoint=null;$('#placementPreview').hidden=true;}
function showPlacement(item,p){clearPlacement();const result=makeParkPiece(item);ghost=result.g;ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.55;o.material.depthWrite=false;}});if(result.track){const r=new T.Group();mesh(r,new T.TorusGeometry(.27,.095,8,18),'#edbf57',0,.09,0).rotation.x=Math.PI/2;const person=makePerson();person.scale.setScalar(.36);r.add(person);ghost.add(r);ghost.userData.rider=r;ghost.userData.track=result.track;}scene.add(ghost);previewPoint=p.clone();$('#previewName').textContent=names[item.type]+' preview';$('#placementPreview').hidden=false;tell('Preview only. Tap another spot to move it, then Add it here.');}
$('#confirmPlacement').onclick=()=>{if(previewPoint)place(previewPoint.clone(),true);};$('#cancelPlacement').onclick=()=>{clearPlacement();pending=null;tell('Preview canceled. Nothing added.');};
function prepareCards(){
 try{thumbnailRenderer=new T.WebGLRenderer({alpha:true,antialias:true});thumbnailRenderer.setSize(240,180);thumbnailRenderer.setPixelRatio(1);thumbnailRenderer.outputColorSpace=T.SRGBColorSpace;thumbnailRenderer.toneMapping=T.ACESFilmicToneMapping;thumbnailRenderer.toneMappingExposure=1.25;}catch{return;}
 const demo=curveFor(START_ROUTE);
 for(const button of document.querySelectorAll('[data-add]')){
  const type=button.dataset.add,label=button.textContent;button.setAttribute('aria-label',label);button.classList.add('preview-card');button.replaceChildren();
  const canvas=document.createElement('canvas');canvas.width=240;canvas.height=180;canvas.setAttribute('aria-hidden','true');const name=document.createElement('strong');name.textContent=names[type];const sub=document.createElement('small');sub.textContent=SLIDES.includes(type)?'Watch it ride · FREE':'Explore in 3D · FREE';button.append(canvas,name,sub);
  const display=new T.Scene();display.add(new T.HemisphereLight('#ffffff','#7a9465',3));const light=new T.DirectionalLight('#fff4d5',3);light.position.set(-4,8,7);display.add(light);
  const item={type,t:0,x:0,z:0,rot:0},result=makeParkPiece(item,demo),root=new T.Group();root.add(result.g);
  if(result.track){const end=result.track.getPoint(1);mesh(root,new T.CylinderGeometry(.8,.9,.12,24),'#69cabc',end.x,end.y-.09,end.z);}
  const box=new T.Box3().setFromObject(root),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());root.position.sub(center);display.add(root);
  let rider=null;if(result.track){rider=new T.Group();mesh(rider,new T.TorusGeometry(.23,.08,8,14),'#e8b84f',0,0,0).rotation.x=Math.PI/2;const person=makePerson();person.scale.setScalar(.32);rider.add(person);root.add(rider);}
  const camera=new T.PerspectiveCamera(36,240/180,.1,60),dist=Math.max(size.x,size.y*1.1,size.z)*1.7;
  previewCards.push({button,type,canvas,ctx:canvas.getContext('2d'),display,root,rider,track:result.track,camera,dist,visible:true});
 }
 if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries){const card=previewCards.find(c=>c.button===entry.target);if(card)card.visible=entry.isIntersecting;}});previewCards.forEach(c=>observer.observe(c.button));}
 animateCards(1000,true);
}
function animateCards(now,force=false){if(!thumbnailRenderer||(!force&&now-lastThumb<100))return;lastThumb=now;for(const c of previewCards){if(!force&&!c.visible)continue;const a=paused?1.7:1.7+Math.sin(now*.00035)*.55;c.camera.position.set(Math.sin(a)*c.dist,c.dist*.55,Math.cos(a)*c.dist);c.camera.lookAt(0,0,0);if(c.rider){const t=paused?.35:(now*.00018)%1;c.rider.position.copy(c.track.getPoint(t)).add(new T.Vector3(0,.1,0));const v=c.track.getTangent(t);c.rider.rotation.y=Math.atan2(v.x,v.z);}thumbnailRenderer.render(c.display,c.camera);c.ctx.clearRect(0,0,240,180);c.ctx.drawImage(thumbnailRenderer.domElement,0,0);}}
buildRiver();for(let i=0;i<5;i++)makeRider(i/5);balance();resize();save();prepareCards();requestAnimationFrame(animate);
