import assert from 'node:assert/strict';import fs from 'node:fs';
import * as T from '../vendor/three.module.js';import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {createSeatedBody} from '../family-body.js';import {addNismoSeats,replaceableCabinGeometry} from '../skyline-cabin.js';import {trimBust} from '../family-avatar.js';
global.document={createElement:()=>({getContext:()=>({fillRect(){},fillText(){},clearRect(){},measureText:()=>({width:230})})})};global.ProgressEvent=class{constructor(t,p){Object.assign(this,p);}};
for(const child of [false,true]){const {group}=createSeatedBody(child),names=[];let count=0;group.traverse(o=>{names.push(o.name);if(o.isMesh){count+=o.geometry.attributes.position.count;assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));}});assert.equal(names.filter(n=>n==='thumb').length,2);assert.equal(names.filter(n=>/^finger /.test(n)).length,8);for(const name of ['left trouser leg','right trouser leg','left sneaker','right sneaker','shoulder seat belt','lap seat belt'])assert.ok(names.includes(name));assert.ok(count<70000,'Keep body geometry within the mobile budget');}
const seats=addNismoSeats(new T.Group());assert.equal(seats.children.length,2);assert.deepEqual(seats.children.map(s=>s.position.x),[-.39,.39]);for(const s of seats.children){assert.ok(new T.Box3().setFromObject(s).max.y<1.27,'Seat stays below the roof');assert.ok(s.name.includes('Nismo'));assert.equal(s.getObjectsByProperty('name','carbon shell with two harness openings').length,1);assert.equal(s.getObjectsByProperty('name','red seat cushion').length,1);}
async function geometryOnly(file){const b=fs.readFileSync(new URL(file,import.meta.url)),n=b.readUInt32LE(12),j=JSON.parse(b.subarray(20,20+n));j.buffers[0].uri='data:application/octet-stream;base64,'+b.subarray(28+n).toString('base64');delete j.images;delete j.textures;delete j.samplers;function clean(o){for(const k of Object.keys(o)){if(k.endsWith('Texture'))delete o[k];else if(o[k]&&typeof o[k]==='object')clean(o[k]);}}clean(j.materials);const {scene}=await new GLTFLoader().parseAsync(JSON.stringify(j),'');scene.updateMatrixWorld(true);return scene;}
const scene=await geometryOnly('../assets/cars/skyline-r34.glb'),box=new T.Box3().setFromObject(scene),center=box.getCenter(new T.Vector3()),scale=4.6/box.getSize(new T.Vector3()).z,transform=new T.Matrix4().makeScale(scale,scale,scale).multiply(new T.Matrix4().makeTranslation(-center.x,-box.min.y,-center.z));
const counts={};scene.traverse(o=>{if(!o.isMesh||!/(InteriorA_Material1$|^seat$|TexturedA_Material1$)/.test(o.material.name))return;let g=o.geometry.clone().applyMatrix4(transform.clone().multiply(o.matrixWorld));if(g.index)g=g.toNonIndexed();const before=g.attributes.position.array.slice(),retained=replaceableCabinGeometry(g,o.material.name);counts[o.material.name]=[before.length/3,retained.attributes.position.count];
 if(o.material.name==='seat'){const p=retained.attributes.position;assert.ok(p.count>0,'Rear bench survives');for(let i=0;i<p.count;i++)assert.ok(p.getZ(i)<-.46,'Original front Sparco seat is removed');}
 if(o.material.name.endsWith('InteriorA_Material1')){const seen=new Set();const p=retained.attributes.position;for(let i=0;i<p.count;i++)seen.add([p.getX(i),p.getY(i),p.getZ(i)].join(','));for(let i=0;i<before.length;i+=3)if(before[i+2]>.29)assert.ok(seen.has([...before.subarray(i,i+3)].join(',')),'Dashboard and steering wheel remain intact');}
});assert.equal(counts.rNissan_SkylineGTRR34F2_1999TexturedA_Material1[1],0,'Nitrous cylinders no longer occupy Leo’s seat');
for(const child of [false,true]){const head=await geometryOnly('../assets/family/'+(child?'leo':'artin')+'-head.glb'),b=new T.Box3().setFromObject(head),c=b.getCenter(new T.Vector3()),s=(child?.5:.37)/b.getSize(new T.Vector3()).y,boundary=c.y+((child?.91:.935)-(child?1.02:1.09))/s;let trimmed=0;head.traverse(o=>{if(!o.isMesh)return;const old=o.geometry.index?o.geometry.toNonIndexed():o.geometry,p=old.attributes.position;const clean=trimBust(o.geometry,o.matrixWorld,boundary),q=clean.attributes.position,kept=new Set();for(let i=0;i<q.count;i++)kept.add([q.getX(i),q.getY(i),q.getZ(i)].join(','));for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i);if(v.clone().applyMatrix4(o.matrixWorld).y>boundary+1e-5)assert.ok(kept.has(v.toArray().join(',')),'Accepted face positions must not move');else trimmed++;}});assert.ok(trimmed>0,'Only the cropped bust base is replaced');}
console.log('PASS: complete bodies and fingers, two Nismo seats below roof, rear bench/dashboard/wheel retained, original front seat and nitrous removed, and facial vertices unchanged.');
